-- Add 16 new Consciousness Coaching knowledge base entries for Dr. Kai Nakamura

INSERT INTO coach_knowledge_base (coach_id, title, content, type, priority, expertise_area, tags) VALUES 

-- Consciousness Coaching Framework (4 entries)
('kai', 'Consciousness Coaching Grundlagen', 'Das Consciousness Coaching-Framework basiert auf der Prämisse, dass nachhaltige Transformation durch Bewusstseinserweiterung entsteht. Es verbindet die vier Bewusstseinsebenen: 1) Unbewusste Inkompetenz (nicht wissen, dass man nicht weiß), 2) Bewusste Inkompetenz (wissen, dass man nicht weiß), 3) Bewusste Kompetenz (bewusst anwenden), 4) Unbewusste Kompetenz (automatische Meisterschaft). Der Coach führt den Klienten systematisch durch diese Ebenen mittels Bewusstseins-aktivierender Fragen und Selbstreflexions-Prozessen. Zentral ist die Erkenntnis, dass Menschen oft in automatischen Reaktionsmustern gefangen sind, ohne sich dessen bewusst zu sein. Durch gezielte Bewusstmachung dieser Muster können neue Wahlmöglichkeiten entstehen.', 'framework', 4, 'Psychology', ARRAY['consciousness', 'awareness', 'transformation', 'competence-levels']),

('kai', 'Bewusstseins-aktivierende Fragen', 'Spezielle Frage-Techniken zur Bewusstseinserweiterung: "Was nimmst du in dieser Situation wahr?" führt zu Selbstbeobachtung. "Welcher deiner Kernwerte ist hier berührt?" verbindet mit innerem Kompass. "Wo siehst du deine Gestaltungsmacht?" aktiviert Verantwortungsbewusstsein. "Wie würdest du das aus Sicht deines zukünftigen Selbst betrachten?" ermöglicht Perspektivenwechsel. "Welche innere Stimme hörst du in solchen Momenten?" exploriert Glaubenssätze. Diese Fragen führen von oberflächlichen Symptomen zu tiefen Ursachen und aktivieren das Schöpfer-Bewusstsein.', 'technique', 4, 'Psychology', ARRAY['questions', 'awareness', 'self-reflection', 'empowerment']),

('kai', 'Vier-Quadranten + Consciousness Integration', 'Die Integration von Consciousness Coaching mit dem Vier-Quadranten-Modell: ICH (Bewusstsein, Werte, Glaubenssätze), ES (Verhalten, Gewohnheiten, Körper), WIR (Beziehungen, Kommunikation, soziale Systeme), SIE (Strukturen, Organisationen, Umwelt). Consciousness Coaching erweitert jede Perspektive: ICH durch Selbsterkenntnis und Werte-Klärung, ES durch bewusste Verhaltensänderungen, WIR durch authentische Kommunikation, SIE durch systemisches Denken. Diese ganzheitliche Sicht ermöglicht nachhaltige Transformation auf allen Ebenen.', 'framework', 4, 'Psychology', ARRAY['four-quadrants', 'consciousness', 'integration', 'holistic']),

('kai', 'Von Opfer zu Schöpfer-Bewusstsein', 'Der fundamentale Shift von Opferhaltung zu Schöpfer-Bewusstsein ist zentral für Empowerment. Opferhaltung manifestiert sich durch: "Das passiert mir", "Ich kann nichts daran ändern", "Die anderen sind schuld". Schöpfer-Bewusstsein zeigt sich durch: "Ich erschaffe meine Erfahrungen", "Ich habe Wahlmöglichkeiten", "Ich übernehme Verantwortung für meine Reaktionen". Der Übergang erfolgt durch Bewusstmachung der eigenen Gestaltungsmacht, Identifikation von Handlungsoptionen und Übernahme von Verantwortung für Gedanken, Gefühle und Handlungen.', 'concept', 4, 'Psychology', ARRAY['empowerment', 'responsibility', 'mindset-shift', 'creator-consciousness']),

-- Fünf Kernwerte-System (3 entries)
('kai', 'Die Fünf Consciousness Coaching Kernwerte', 'Das Werte-System des Consciousness Coaching umfasst fünf fundamentale Prinzipien: 1) INTEGRITÄT - Übereinstimmung zwischen Werten und Handeln, Wort geben und halten als Vertrauensbasis. 2) VOLLSTÄNDIGE KOMMUNIKATION - Authentische, ehrliche Verbindung statt oberflächlicher Interaktion. 3) VERANTWORTUNG - Sich als Urheber des eigenen Lebens erkennen, nicht als Opfer der Umstände. 4) FREIE WAHL - Bewusste Entscheidungen treffen statt automatisch zu reagieren. 5) ETHIK - Reflexion aller Handlungsauswirkungen auf sich selbst und andere. Diese Werte bilden das Fundament für bewusste Lebensführung.', 'framework', 4, 'Psychology', ARRAY['values', 'integrity', 'communication', 'responsibility', 'ethics']),

('kai', 'Werte-Konflikt Identifikation', 'Systematische Erkennung von Diskrepanzen zwischen persönlichen Werten und tatsächlichem Verhalten. Anzeichen für Werte-Konflikte: innere Unruhe, Stress ohne erkennbare Ursache, Gefühl der Unzufriedenheit trotz äußerer Erfolge, wiederholte Verhaltensmuster, die nicht zu gewünschten Ergebnissen führen. Assessment-Methoden: Werte-Inventar erstellen, tägliche Handlungen analysieren, Gefühls-Check bei wichtigen Entscheidungen, Beobachtung von Energie-Levels bei verschiedenen Aktivitäten. Auflösung erfolgt durch bewusste Ausrichtung der Handlungen an den Kernwerten.', 'technique', 4, 'Psychology', ARRAY['values-conflict', 'assessment', 'alignment', 'energy']),

('kai', 'Integrität als Transformationsschlüssel', 'Integrität ist die Übereinstimmung zwischen Denken, Fühlen, Sagen und Handeln. Sie entsteht durch: Klarheit über eigene Werte, Ehrlichkeit gegenüber sich selbst und anderen, Zuverlässigkeit in Worten und Taten, Mut zur Authentizität auch bei Widerstand. Mangelnde Integrität zeigt sich durch: innere Zerrissenheit, Energieverlust, verminderte Selbstachtung, Schwierigkeiten in Beziehungen. Aufbau von Integrität: kleine Versprechen einhalten, bei Fehlern zu Korrekturen stehen, Werte-basierte Entscheidungen treffen, authentische Kommunikation praktizieren.', 'concept', 4, 'Psychology', ARRAY['integrity', 'authenticity', 'values-alignment', 'self-respect']),

-- Transformational Breakthrough (4 entries)
('kai', 'Transformational Breakthrough Framework', 'Systematischer Ansatz für Durchbrüche in vier Lebensbereichen: 1) GELD/KARRIERE - Von Mangel zu Fülle-Bewusstsein, berufliche Erfüllung finden. 2) BEZIEHUNGEN/FAMILIE - Authentische Verbindungen schaffen, Kommunikationsmuster transformieren. 3) VITALITÄT/WOHLBEFINDEN - Ganzheitliche Gesundheit, Energie-Management, Work-Life-Integration. 4) GEFÜHLSMANAGEMENT - Emotionale Intelligenz, Stress-Resilienz, innere Ruhe. Jeder Bereich wird durch Bestandsaufnahme, Vision-Entwicklung, Blockaden-Identifikation und Handlungsplan systematisch transformiert.', 'framework', 4, 'Psychology', ARRAY['breakthrough', 'life-areas', 'transformation', 'holistic']),

('kai', 'Lebensbereichs-Mapping', 'Ganzheitliche Analyse aller Lebensbereiche zur Identifikation von Transformation-Potentialen. Assessment-Dimensionen: Zufriedenheit (1-10 Skala), Energie-Level, Zeit-Investment, Stress-Faktoren, Wachstums-Potentiale. Visualisierung durch Lebensrad oder Matrix. Identifikation von: Stärken-Bereichen (hohe Zufriedenheit, Energie-Quellen), Entwicklungs-Bereichen (niedrige Zufriedenheit, Verbesserungs-Potential), Stress-Bereichen (hoher Aufwand, niedriger Ertrag), Vernachlässigungs-Bereichen (wenig Aufmerksamkeit, aber wichtig für Gesamtzufriedenheit). Priorisierung nach Impact und Machbarkeit.', 'technique', 4, 'Psychology', ARRAY['life-mapping', 'assessment', 'priorities', 'balance']),

('kai', 'Von Mangel zu Fülle-Bewusstsein', 'Transformation der Grundhaltung von Knappheit zu Abundanz. Mangel-Bewusstsein zeigt sich durch: Angst vor Verlust, Konkurrenz-Denken, Fokus auf das was fehlt, Geiz mit Zeit/Energie/Ressourcen. Fülle-Bewusstsein manifestiert sich durch: Vertrauen in eigene Fähigkeiten, Kooperations-Bereitschaft, Dankbarkeit für Vorhandenes, großzügigen Umgang mit Ressourcen. Transformation-Strategien: Dankbarkeits-Praktiken, Erfolgs-Inventar erstellen, Ressourcen-Bewusstsein entwickeln, Geben und Nehmen ausbalancieren, Wachstums-Mindset kultivieren.', 'concept', 4, 'Psychology', ARRAY['abundance', 'mindset', 'gratitude', 'growth']),

('kai', 'Visions-Entwicklung für Durchbrüche', 'Systematische Entwicklung kraftvoller Zukunfts-Visionen als Motivation für Transformation. Elemente einer kraftvollen Vision: emotional berührend, sinnstiftend, herausfordernd aber erreichbar, konkret visualisierbar, mit Werten aligned. Entwicklungs-Prozess: Ideal-Tag visualisieren, 5-Jahres-Vision entwerfen, Meilensteine definieren, Hindernisse antizipieren, Ressourcen identifizieren. Vision-Aktivierung: tägliche Visualisierung, Vision-Board erstellen, Handlungs-Schritte ableiten, Fortschritt tracken, Vision bei Entscheidungen als Kompass nutzen.', 'technique', 4, 'Psychology', ARRAY['vision', 'goals', 'motivation', 'future-self']),

-- Glaubenssätze & Blockaden (3 entries)
('kai', 'Dysfunktionale Glaubenssätze identifizieren', 'Systematische Erkennung limitierender Überzeugungen. Häufige Muster: "Ich bin nicht gut genug" (Selbstwert-Thema), "Ich muss es allen recht machen" (Boundaries-Problem), "Ich passe nirgendwo dazu" (Zugehörigkeits-Angst), "Erfolg ist gefährlich" (Erfolgs-Sabotage), "Ich verdiene keine Liebe" (Beziehungs-Blockade). Identifikations-Methoden: Trigger-Situationen analysieren, emotionale Reaktions-Muster beobachten, innere Dialoge bewusst wahrnehmen, körperliche Stress-Signale beachten, wiederkehrende Lebens-Themen erkennen.', 'technique', 4, 'Psychology', ARRAY['belief-systems', 'limiting-beliefs', 'triggers', 'patterns']),

('kai', 'Kognitive Umstrukturierung', 'Evidenz-basierte Methode zur Transformation dysfunktionaler Gedankenmuster. Schritte: 1) IDENTIFIKATION - Automatische Gedanken bewusst wahrnehmen. 2) HINTERFRAGUNG - Realitäts-Check der Gedanken. 3) EVIDENZ-SAMMLUNG - Pro und Contra der Überzeugung. 4) ALTERNATIVE PERSPEKTIVEN - Neue, hilfreiche Sichtweisen entwickeln. 5) VERHALTENS-EXPERIMENTE - Neue Überzeugungen in der Realität testen. 6) INTEGRATION - Neue Denkmuster etablieren. Fragen zur Hinterfragung: "Ist das wirklich wahr?", "Wie fühle ich mich mit diesem Gedanken?", "Welche Alternativen gibt es?", "Was würde ich einem Freund raten?"', 'technique', 4, 'Psychology', ARRAY['cognitive-restructuring', 'thought-patterns', 'evidence', 'reframing']),

('kai', 'Blockaden-Analyse und Auflösung', 'Systematische Bearbeitung von inneren Hindernissen bei der Zielerreichung. Blockaden-Typen: emotionale (Ängste, Sorgen), kognitive (limitierende Glaubenssätze), verhaltensbezogene (Prokrastination, Sabotage), systemische (Umfeld-Widerstand). Analyse-Methoden: Blockaden-Mapping, Sekundär-Gewinn identifizieren, Worst-Case-Szenarien durchspielen, Ressourcen-Inventar erstellen. Auflösungs-Strategien: schrittweise Desensibilisierung, Erfolgs-Erfahrungen schaffen, Support-System aufbauen, neue Gewohnheiten etablieren.', 'technique', 4, 'Psychology', ARRAY['blockages', 'resistance', 'fears', 'breakthrough']),

-- Bewusstseinserweiterung (2 entries)
('kai', 'Vier Stadien der Bewusstseinsentwicklung', 'Klassisches Kompetenz-Modell auf Bewusstseinsentwicklung angewendet: 1) UNBEWUSSTE INKOMPETENZ - Nicht wissen, dass man nicht weiß. Automatische Reaktionen ohne Reflexion. 2) BEWUSSTE INKOMPETENZ - Erkennen der eigenen Begrenzungen. Entstehung von Lernbereitschaft. 3) BEWUSSTE KOMPETENZ - Bewusste Anwendung neuer Fähigkeiten. Erfordert Aufmerksamkeit und Übung. 4) UNBEWUSSTE KOMPETENZ - Automatische Meisterschaft. Integration der neuen Fähigkeiten. Coaching-Ziel: Menschen von Stadium 1 zu Stadium 4 zu führen durch Bewusstmachung, Übung und Integration.', 'framework', 4, 'Psychology', ARRAY['consciousness-levels', 'competence', 'development', 'mastery']),

('kai', 'Meta-kognitive Reflexion', 'Denken über das Denken als höchste Form der Bewusstseinserweiterung. Elemente: Gedanken-Beobachtung (Witness-Consciousness), Muster-Erkennung (wiederkehrende Denkstrukturen), Perspektiven-Wechsel (verschiedene Standpunkte einnehmen), Bewertungs-Reflexion (Urteile hinterfragen). Praktische Übungen: Gedanken-Tagebuch führen, tägliche Reflexions-Zeiten einbauen, Entscheidungs-Prozesse analysieren, verschiedene Perspektiven bewusst einnehmen. Ziel: Entwicklung einer "inneren Beobachter-Instanz" die bewusste Entscheidungen ermöglicht.', 'technique', 4, 'Psychology', ARRAY['meta-cognition', 'reflection', 'awareness', 'observer-self']);