-- Deutsche Übersetzungen für Dr. Vita Femina Knowledge Base Einträge (Batch 2/2)

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Hormone und Schlaf bei Frauen', 'women_sleep_de', 'hormonal_guidance', 'Östrogen und Progesteron beeinflussen Schlafqualität erheblich. Östrogen fördert REM-Schlaf, Progesteron wirkt beruhigend. Während Menstruation: Magnesium 400mg vor Schlafengehen. Perimenopause: Melatonin 1-3mg, kühlere Schlaftemperatur. Zyklusbasierte Schlafhygiene: Follikulärphase - normale Bedtimes, Lutealphase - frühere Bedtimes für bessere Regeneration.', 'dr_vita_femina', 4, ARRAY['schlafhormone', 'östrogen_progesteron', 'menstruation_schlaf', 'melatonin'], now(), now()),

('Krafttraining in der Schwangerschaft', 'pregnancy_strength_de', 'exercise_guideline', 'Sicheres Krafttraining während Schwangerschaft: 1. Trimester - normale Intensität möglich. 2./3. Trimester - Rückenlage vermeiden, Core-Training anpassen. Empfohlene Übungen: Kniebeugen, modifizierte Planks, Beckenboden-Training. Intensität bei 60-70% der gewohnten Last. Bei Blutungen, Schwindel oder ungewöhnlichen Symptomen sofort pausieren und Arzt konsultieren.', 'dr_vita_femina', 5, ARRAY['schwangerschaft_training', 'sicheres_krafttraining', 'beckenboden', 'trimester_anpassung'], now(), now()),

('Menopause und Muskelerhaltung', 'menopause_muscle_de', 'aging_guidance', 'Östrogenverlust beschleunigt Muskelverlust um 1-2% jährlich nach Menopause. Gegenmaßnahmen: Krafttraining 3x/Woche mit progressiver Belastung, Protein 1.2-1.6g/kg Körpergewicht, Vitamin D 1000-2000 IU täglich. HRT kann Muskelerhaltung unterstützen - individuelle Abwägung mit Gynäkologen. Fokus auf compound movements und Widerstandstraining.', 'dr_vita_femina', 5, ARRAY['menopause_muskel', 'östrogenverlust', 'krafttraining_alter', 'hrt_muskel'], now(), now()),

('Eisenmangel bei Sportlerinnen', 'iron_deficiency_athletes_de', 'nutritional_guidance', 'Eisenmangel betrifft 25-35% der Ausdauersportlerinnen. Symptome: Müdigkeit, verminderte Leistung, blasse Haut. Laborwerte: Ferritin <30 ng/ml problematisch. Eisenreiche Lebensmittel: rotes Fleisch, Spinat, Hülsenfrüchte. Absorption verbessern mit Vitamin C, vermeiden mit Kaffee/Tee zu Mahlzeiten. Bei schwerem Mangel: Eisenpräparate 18-65mg täglich, idealerweise auf nüchternen Magen.', 'dr_vita_femina', 4, ARRAY['eisenmangel', 'sportlerinnen', 'ferritin', 'eisenabsorption'], now(), now()),

('Osteoporose-Prävention durch Training', 'bone_health_prevention_de', 'bone_health', 'Weight-bearing exercises stimulieren Knochenneubildung. Optimal: Krafttraining mit progressiver Belastung + impact activities (Springen, Laufen). Vitamin D 1000-2000 IU + Calcium 1000-1200mg täglich. Kritische Phase: Perimenopause - hier Knochenverlust am stärksten. Regelmäßige DEXA-Scans ab 50 Jahren. Vermeiden: Rauchen, exzessiver Alkohol, zu niedrige Körpergewicht.', 'dr_vita_femina', 5, ARRAY['osteoporose_prävention', 'weight_bearing', 'calcium_vitamin_d', 'dexa_scan'], now(), now()),

('Hormonelle Verhütung und Leistung', 'contraception_performance_de', 'hormonal_guidance', 'Hormonelle Verhütung kann Trainingsadaptation beeinflussen. Kombinationspillen: können Kraft- und Ausdauerleistung reduzieren, Wasserretention erhöhen. Progesteronbasierte Methoden: weniger Einfluss auf Leistung. Training anpassen: in ersten Monaten nach Beginn eventuell niedrigere Intensitäten. Bei Leistungseinbußen: alternative Verhütungsmethoden mit Gynäkologen besprechen.', 'dr_vita_femina', 3, ARRAY['verhütung_leistung', 'kombinationspille', 'progesteron_training', 'alternative_verhütung'], now(), now()),

('Autoimmunerkrankungen und Sport', 'autoimmune_exercise_de', 'medical_guidance', 'Moderate Bewegung kann Autoimmunreaktionen reduzieren, intensive Belastung kann sie verstärken. Anpassung nach Krankheitsaktivität: Ruhephasen - leichte Bewegung/Yoga, stabile Phasen - moderates Krafttraining möglich. Wichtig: Stress-Management, ausreichend Schlaf, entzündungshemmende Ernährung. Bei Hashimoto, Rheuma, MS: individuelles Trainingsprogramm mit Arzt abstimmen.', 'dr_vita_femina', 4, ARRAY['autoimmun_sport', 'moderate_bewegung', 'krankheitsaktivität', 'stress_management'], now(), now()),

('Weibliche Athleten: RED-S Prävention', 'red_s_prevention_de', 'sports_medicine', 'Relative Energy Deficiency in Sport (RED-S): Energiemangel führt zu hormonellen Störungen, Knochenverlust, Leistungseinbußen. Warnsignale: ausbleibende Periode, häufige Verletzungen, Müdigkeit. Prävention: ausreichende Kalorienzufuhr (nicht unter Grundumsatz), regelmäßige Laborkontrollen, psychologische Betreuung bei Essstörungen. Treatment: Energiezufuhr erhöhen, Training reduzieren, medizinische Überwachung.', 'dr_vita_femina', 5, ARRAY['red_s', 'energiemangel', 'amenorrhoe', 'essstörung_sport'], now(), now());