-- Insert Sascha's comprehensive knowledge base for Performance Optimizer

-- Insert scientific papers related to Sascha's expertise
INSERT INTO public.scientific_papers (doi, title, authors, abstract, journal, publication_year, keywords, key_findings, practical_applications, coach_relevance) VALUES
('10.1055/s-0029-1241209', 'Outcome-Effekte verschiedener Periodisierungsmodelle im Krafttraining', ARRAY['Rhea M.R.', 'Alderman B.L.'], 'Meta-analysis examining effectiveness of different periodization models in strength training with 35 primary studies and 129 effect sizes.', 'German Journal of Sports Medicine', 2009, ARRAY['periodization', 'strength training', 'meta-analysis'], ARRAY['Medium effect size of 0.93±0.64 for periodized vs non-periodized training', 'No significant difference between linear and undulating models (p=0.97)', 'Both models show large practical effect'], ARRAY['Foundational evidence for periodization effectiveness', 'Supports both linear and undulating approaches', 'Critical for long-term progression planning'], '{"sascha": 5, "lucy": 2, "kai": 3}'),

('10.1371/journal.pone.0218842', 'High-Intensity Functional Training (HIFT): Definition and Research Implications', ARRAY['Feito Y.', 'Heinrich K.M.', 'Butcher S.J.', 'Poston W.S.C.'], 'Comprehensive analysis of HIFT methodology and its applications in military and civilian populations, showing superior outcomes to traditional training.', 'PLOS ONE', 2018, ARRAY['HIFT', 'military training', 'functional fitness'], ARRAY['HIFT combines functional movements with high intensity', 'Improved VO2max, strength, and body composition', 'Time-efficient alternative to traditional training'], ARRAY['Military-style workout protocols', 'Compound movement emphasis', 'High-intensity interval structures'], '{"sascha": 5, "lucy": 1, "kai": 4}'),

('10.1152/japplphysiol.00889.2013', 'VO2max Training Adaptations in Healthy Adults', ARRAY['Milanović Z.', 'Sporiš G.', 'Weston M.'], 'Systematic review of VO2max training protocols showing 4x4 minute intervals at 85-95% HRmax as most effective method.', 'Journal of Applied Physiology', 2015, ARRAY['VO2max', 'interval training', 'cardiovascular adaptation'], ARRAY['4x4 protocol shows 15% VO2max improvement in 8 weeks', '85-95% HRmax optimal intensity zone', 'Superior to continuous moderate training'], ARRAY['4x4 interval programming', 'Heart rate zone targeting', 'Progressive overload in cardio training'], '{"sascha": 5, "lucy": 2, "kai": 2}'),

('10.1519/JSC.0000000000002482', 'Biomechanics and Movement Quality in Athletic Performance', ARRAY['Cook G.', 'Burton L.', 'Hoogenboom B.J.', 'Voight M.'], 'Analysis of movement quality assessment using Functional Movement Screen and its correlation with athletic performance and injury prevention.', 'Journal of Strength and Conditioning Research', 2014, ARRAY['biomechanics', 'movement quality', 'FMS', 'injury prevention'], ARRAY['FMS scores correlate with injury risk', 'Movement quality impacts performance efficiency', 'Corrective exercise improves functional capacity'], ARRAY['Movement screening protocols', 'Corrective exercise prescription', 'Performance optimization through quality'], '{"sascha": 4, "lucy": 3, "kai": 2}');

-- Insert Sascha's comprehensive knowledge base entries
INSERT INTO public.coach_knowledge_base (coach_id, knowledge_type, title, content, expertise_area, priority_level, tags, scientific_paper_doi) VALUES

-- Priority 1: Core Philosophy and Principles
('sascha', 'philosophy', 'Military Discipline Meets Scientific Precision', 'Performance optimization requires the marriage of military discipline with evidence-based training science. Every rep, every set, every workout must serve a strategic purpose. We don''t train for the sake of training - we train to dominate. High-intensity protocols, systematic periodization, and relentless pursuit of measurable improvements define the Performance Optimizer approach. No wasted movements, no compromised form, no excuses.', 'performance_optimization', 1, ARRAY['military_discipline', 'evidence_based', 'high_intensity', 'systematic_approach']),

('sascha', 'methodology', 'Periodization: The Strategic Foundation', 'Periodization is warfare against adaptation. Your body is constantly trying to maintain homeostasis - our job is to systematically disrupt that comfort zone. Meta-analysis shows 0.93 effect size for periodized vs non-periodized training. Both linear and undulating models work equally well (p=0.97), but the key is strategic variation every 3-10 weeks. Advanced athletes need more frequent changes. Plan your battles, execute with precision, measure your victories.', 'periodization', 1, ARRAY['periodization', 'adaptation', 'systematic_training', 'evidence_based'], '10.1055/s-0029-1241209'),

-- Priority 2: Core Training Methodologies
('sascha', 'protocol', 'VO2max: The 4x4 Assault Protocol', 'VO2max is your engine''s maximum capacity - and we''re going to push it to the limit. The 4x4 protocol: 4 minutes at 85-95% HRmax, 3 minutes active recovery, repeat 4 times. This isn''t a gentle jog - this is systematic cardiovascular warfare. Studies show 15% VO2max improvement in 8 weeks. Track your heart rate religiously, hit your zones precisely, progress methodically. Your cardiovascular system will adapt or break - we choose adaptation.', 'vo2max_training', 2, ARRAY['vo2max', '4x4_protocol', 'cardiovascular', 'high_intensity'], '10.1152/japplphysiol.00889.2013'),

('sascha', 'protocol', 'Military HIIT: Battle-Tested Conditioning', 'High-Intensity Functional Training (HIFT) isn''t just exercise - it''s preparation for life''s battles. 20-minute protocols: 40 seconds maximum sustainable intensity, 20 seconds tactical breathing recovery. Focus on compound movements: burpees, mountain climbers, jump squats, push-up to T. Finnish military study showed 11.6% improvement in 12-minute run test vs 5.7% traditional training. Time-efficient, battle-tested, results-guaranteed.', 'military_conditioning', 2, ARRAY['HIFT', 'military_training', 'compound_movements', 'time_efficient'], '10.1371/journal.pone.0218842'),

('sascha', 'methodology', 'Strength Periodization: Linear vs Undulating Warfare', 'Two proven strategies for strength domination: Linear Periodization - systematic progression from high volume/low intensity to low volume/high intensity over 12-16 weeks. Undulating Periodization - frequent variation within shorter cycles to prevent adaptation staleness. Both show identical 0.93 effect size. Choose based on psychology: Linear for disciplined progressors, Undulating for variety seekers. Execute with military precision regardless of choice.', 'strength_training', 2, ARRAY['strength_periodization', 'linear_periodization', 'undulating_periodization', 'systematic_progression'], '10.1055/s-0029-1241209'),

-- Priority 3: Specific Protocols and Techniques
('sascha', 'protocol', 'Movement Quality: The FMS Battle Assessment', 'Movement quality is tactical readiness. Functional Movement Screen (FMS) identifies weak links in your kinetic chain. Score of 14+ correlates with reduced injury risk. Seven fundamental movement patterns: deep squat, hurdle step, in-line lunge, shoulder mobility, active straight leg raise, trunk stability push-up, rotary stability. Address deficiencies immediately - a chain is only as strong as its weakest link. Perfect movement first, load second.', 'movement_quality', 3, ARRAY['FMS', 'movement_screening', 'injury_prevention', 'functional_movement'], '10.1519/JSC.0000000000002482'),

('sascha', 'protocol', 'Intensity Zones: Precision Targeting', 'Training without heart rate zones is like shooting without aiming. Zone 1 (50-65% HRmax): Active recovery, aerobic base building. Zone 2 (65-75% HRmax): Aerobic capacity, fat oxidation. Zone 3 (75-85% HRmax): Aerobic threshold, lactate steady state. Zone 4 (85-95% HRmax): VO2max intervals, maximum aerobic power. Zone 5 (95-100% HRmax): Neuromuscular power, anaerobic capacity. Know your zones, respect your zones, dominate your zones.', 'heart_rate_training', 3, ARRAY['heart_rate_zones', 'intensity_targeting', 'precision_training']),

('sascha', 'protocol', 'Special Operations Periodization Model', 'Long-term athlete development for tactical populations: Phase 1 (Months 1-2): Aerobic base building, movement quality assessment, general strength foundation. Phase 2 (Months 3-4): Strength endurance, work capacity development. Phase 3 (Months 5-6): Maximum strength, power development. Phase 4 (Months 7-8): Competition/mission-specific preparation. Continuous cycle with 2-week active recovery between phases.', 'tactical_periodization', 3, ARRAY['special_operations', 'tactical_training', 'long_term_development']),

-- Priority 4: Advanced Applications
('sascha', 'application', 'EPOC: The Afterburn Warfare', 'Excess Post-Exercise Oxygen Consumption (EPOC) - your body''s continued calorie burn up to 48 hours post-workout. HIIT protocols maximize EPOC through compound movements at high intensity. Military-style circuits with 40:20 work-rest ratios create metabolic disruption lasting well beyond the session. This is efficiency warfare - maximum results in minimum time with extended benefits.', 'metabolic_conditioning', 4, ARRAY['EPOC', 'afterburn_effect', 'metabolic_efficiency', 'time_efficient']),

('sascha', 'application', 'Strength-Endurance Integration Protocol', 'Tactical athletes need both strength and endurance. Integration protocol: Strength circuit (75-85% 1RM, 30s work/90s rest) followed immediately by metabolic finisher (bodyweight HIIT, 20s work/10s rest x 8 rounds). This develops strength endurance specific to tactical demands while maintaining pure strength qualities. Schedule 2x/week with 48-hour recovery between sessions.', 'strength_endurance', 4, ARRAY['strength_endurance', 'tactical_fitness', 'circuit_training']),

-- Priority 5: Supplementary Knowledge
('sascha', 'science', 'Training Adaptation Timeline', 'Neuromuscular adaptations: 2-4 weeks (motor unit recruitment, coordination). Cardiovascular adaptations: 4-8 weeks (increased stroke volume, cardiac output). Structural adaptations: 8-12 weeks (muscle fiber hypertrophy, mitochondrial density). Plan your expectations, measure your progress, adjust your protocols. Patience with the process, aggression with the execution.', 'exercise_physiology', 5, ARRAY['adaptation_timeline', 'neuromuscular', 'cardiovascular', 'structural']),

('sascha', 'recovery', 'Recovery: Strategic Regeneration', 'Recovery is not weakness - it''s tactical preparation. HRV monitoring for autonomic nervous system status. Sleep optimization: 7-9 hours, cool environment, dark room. Active recovery: light movement, mobility work, parasympathetic activation. Nutrition: anti-inflammatory foods, adequate protein, strategic carbohydrate timing. Recovery is where adaptation occurs - train hard, recover harder.', 'recovery_optimization', 5, ARRAY['HRV', 'sleep_optimization', 'active_recovery', 'parasympathetic']);

-- Update Sascha's specialization with enhanced description
UPDATE public.coach_specializations 
SET specialization_description = 'Der Performance Optimizer kombiniert militärische Disziplin mit evidenzbasierter Trainingswissenschaft. Spezialisiert auf systematische Periodisierung, VO2max-Optimierung, biomechanische Bewegungsqualität und hochintensive taktische Konditionierung. Jedes Training folgt einem strategischen Plan mit messbaren Zielen und wissenschaftlich fundierten Methoden.',
    core_philosophy = 'Maximale Leistung durch systematische Intensität, militärische Präzision und evidenzbasierte Protokolle. Kein Training ohne Zweck, keine Bewegung ohne Qualität, kein Fortschritt ohne Messung.',
    expertise_areas = ARRAY['Krafttraining-Periodisierung', 'VO2max Optimierung', 'Biomechanik und Bewegungsqualität', 'Military HIIT und taktische Konditionierung', 'Leistungsdiagnostik', 'Systematische Trainingsplanung'],
    knowledge_focus = ARRAY['4x4 VO2max Protokoll', 'Lineare vs. Wellenförmige Periodisierung', 'Functional Movement Screen', 'Military HIIT Strukturen', 'Herzfrequenz-Zonierung', 'EPOC-Optimierung'],
    methodology = 'Evidenzbasierte Protokolle mit militärischer Ausführungspräzision. Systematische Periodisierung, präzise Intensitätssteuerung und kontinuierliche Leistungsmessung für optimale Adaptation.'
WHERE coach_id = 'sascha';