-- Deutsche Übersetzungen für Kai's Knowledge Base Einträge

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('HRV-Dateninterpretation: Dein autonomes Dashboard', 'hrv_analytics_de', 'protocol', 'HRV ist nicht nur eine Zahl - es ist der Echtzeit-Statusbericht deines Nervensystems. RMSSD <30ms = parasympathische Unterdrückung, erfordert aktive Regeneration. LF/HF-Verhältnis >4.0 = sympathische Übererregung, reduziere Trainingsintensität um 20-30%. 7-Tage-Durchschnitt fällt >8% = Entlastungswoche eingeleitet. Tracke RMSSD-, SDNN- und Stress-Score-Trends, nicht Einzelwerte. Deine HRV-Daten leiten, wann du Grenzen pushen und wann du Regeneration priorisieren sollst.', 'kai', 1, ARRAY['hrv', 'dateninterpretation', 'rmssd', 'parasympathisch', 'trainingsanpassung'], now(), now()),

('Schlafarchitektur-Analytics: Deine Regenerationsdaten entschlüsseln', 'sleep_analytics_de', 'application', 'Deine Schlafdaten erzählen die Geschichte deiner Regeneration. REM <15% des Gesamtschlafs = Stressüberlastung oder Alkoholeinfluss. Tiefschlaf <13% = Wachstumshormon-Unterdrückung, Muskelregeneration kompromittiert. Schlafeffizienz <85% = Schlafhygiene-Probleme. Tracke Schlaflatenz: >20 Minuten zeigt sympathische Hyperaktivierung. Nutze Schlafphasen-Prozentsätze zur Trainingsbelastungsanpassung: schlechter Tiefschlaf = reduziere Volumen um 25%.', 'kai', 2, ARRAY['schlafanalytics', 'rem', 'tiefschlaf', 'schlafeffizienz', 'regenerationsdaten'], now(), now()),

('Digital Detox Protokolle: Kognitive Bandbreite zurückgewinnen', 'digital_wellness_de', 'methodology', 'Digitale Überstimulation fragmentiert Aufmerksamkeit und erhöht Cortisol. Implementiere progressiven Digital Detox: Woche 1: Handyfreie Morgen bis 9 Uhr. Woche 2: Keine Bildschirme 1 Stunde vor dem Schlaf. Woche 3: Komplette Handy-Abschaltung 20-8 Uhr. Woche 4: 24-Stunden digitale Fasten wöchentlich. Tracke Verbesserungen in Schlafqualität, HRV und Focus-Scores. Blaues Licht nach 21 Uhr unterdrückt Melatonin um 50% - nutze Daten zur Optimierung deiner digitalen Grenzen.', 'kai', 3, ARRAY['digital_detox', 'blaues_licht', 'melatonin', 'cortisol', 'aufmerksamkeitstraining'], now(), now()),

('Flow-State-Induktion: Die Neurowissenschaft von Peak Performance', 'flow_psychology_de', 'protocol', 'Flow-Zustände treten auf, wenn Herausforderung präzise dem Skill-Level entspricht (4% Schwierigkeitssteigerung optimal). Neurologisch: reduzierte präfrontale Kortex-Aktivität, erhöhtes Dopamin/Norepinephrin. Pre-Flow-Protokoll: 10-minütige fokussierte Atmung, klare Zielsetzung, Ablenkungen eliminieren. Tracke Flow-Indikatoren: Zeitverzerrung, mühelose Konzentration, intrinsische Motivation. Nutze RPE- und Motivations-Scores zur Identifikation von Flow-Fenstern - treten typisch bei 7-8 RPE mit hohen Motivations-Scores auf.', 'kai', 2, ARRAY['flow_state', 'peak_performance', 'dopamin', 'präfrontaler_kortex', 'herausforderung_skill_balance'], now(), now()),

('Kälte-Hitze-Hormesis: Temperaturtherapie für Resilienz', 'temperature_therapy_de', 'application', 'Kontrollierter Temperaturstress baut physiologische und psychologische Resilienz auf. Kälteexposition (10-15°C, 2-4 Minuten): erhöht Norepinephrin um 250%, verbessert braune Fett-Aktivierung, steigert Fokus. Hitzeexposition (80-100°C Sauna, 15-20 Minuten): erhöht Hitzeschockproteine, Wachstumshormon +2400%, verbessert Herz-Kreislauf-Funktion. Protokoll: 3x/Woche alternierend. Tracke HRV-Verbesserungen und Stresstoleranz-Metriken nach Sitzungen.', 'kai', 3, ARRAY['kälteexposition', 'hitzetherapie', 'norepinephrin', 'hitzeschockproteine', 'hormesis'], now(), now()),

('Kognitives Lastmanagement: Mentale Energie-Optimierung', 'cognitive_optimization_de', 'methodology', 'Deine kognitiven Ressourcen sind endlich und trackbar. Entscheidungsmüdigkeit erreicht Höhepunkt nach 3-4 Stunden fokussierter Arbeit. Lade Entscheidungen vor: automatisiere Mahlzeiten-Auswahl, Trainingspläne und tägliche Routinen. Tracke mentale Energie auf 1-10 Skala 3x täglich. Bei kognitiver Last >7, vermeide komplexe Entscheidungen. Plane hohe kognitive Aufgaben während Cortisol-Peak (8-10 Uhr). Nutze Motivations- und Fokus-Scores zur Optimierung mentaler Performance-Fenster.', 'kai', 2, ARRAY['kognitive_last', 'entscheidungsmüdigkeit', 'mentale_energie', 'cortisol_timing', 'automatisierung'], now(), now()),

('Stressresilienz-Aufbau: Kontrolliertes Adversitätstraining', 'stress_resilience_de', 'protocol', 'Resilienz ist trainierbar durch progressive Stressexposition. Kontrollierte Stressoren: kalte Duschen, Atemanhaltungen, herausfordernde Workouts bei >8 RPE. Schlüsselprinzip: freiwilliges Unbehagen baut unfreiwillige Stresstoleranz auf. Tracke Stressmarker: Ruhepuls, HRV-Erholung, subjektive Stress-Scores. Progressives Protokoll: Woche 1-2: 30-Sekunden Kälteexposition, Woche 3-4: 60 Sekunden, Woche 5-6: 90 Sekunden. Überwache Anpassung durch verbesserte Baseline-Metriken.', 'kai', 2, ARRAY['stressresilienz', 'kontrollierter_stress', 'anpassung', 'progressive_überlastung', 'freiwilliges_unbehagen'], now(), now()),

('Libido und Motivations-Korrelationsanalyse', 'biomarker_analysis_de', 'science', 'Libido ist ein kraftvoller Biomarker für gesamte hormonelle und psychologische Gesundheit. Niedrige Libido korreliert mit erhöhtem Cortisol, reduziertem Testosteron und Übertrainings-Syndrom. Tracke Libido-Scores neben HRV, Schlafqualität und Trainingsbelastung. Rückläufige Libido-Trends zeigen Bedarf für Entlastung, Stressreduktion oder hormonelle Unterstützung. Optimale Libido-Scores (7-9/10) korrelieren mit Peak-Motivation, Trainingskapazität und Regenerationseffizienz.', 'kai', 1, ARRAY['libido', 'hormonelle_gesundheit', 'testosteron', 'cortisol', 'übertraining', 'biomarker'], now(), now());