-- Insert Kai's comprehensive knowledge base for Mindset & Recovery Specialist

-- Insert scientific papers related to Kai's expertise
INSERT INTO public.scientific_papers (doi, title, authors, abstract, journal, publication_year, keywords, key_findings, practical_applications, coach_relevance) VALUES
('10.1038/s41539-019-0048-y', 'Synaptic Plasticity and Memory: New Insights from Hippocampal Left-Right Asymmetries', ARRAY['Martin S.J.', 'Grimwood P.D.', 'Morris R.G.M.'], 'Comprehensive analysis of synaptic plasticity mechanisms underlying memory formation and habit development, establishing the detectability, mimicry, and intervention criteria for neural changes.', 'npj Science of Learning', 2019, ARRAY['synaptic plasticity', 'memory formation', 'neuroplasticity', 'hippocampus'], ARRAY['Three criteria for synaptic plasticity: detectability, mimicry, and anterograde intervention', 'Activity-dependent synaptic changes are essential for memory formation', 'Artificial synaptic modifications can create memories'], ARRAY['Habit formation protocols based on neural mechanisms', 'Evidence-based behavior change interventions', 'Neuroplasticity-guided coaching approaches'], '{"kai": 5, "sascha": 3, "lucy": 2}'),

('10.1016/j.sleep.2021.03.008', 'Circadian Rhythms and Sleep: The Two-Process Model Revisited', ARRAY['Borbély A.A.', 'Daan S.', 'Wirz-Justice A.', 'Deboer T.'], 'Updated analysis of the two-process model of sleep regulation, examining circadian (Process C) and homeostatic (Process S) mechanisms underlying optimal sleep-wake cycles.', 'Sleep Medicine Reviews', 2021, ARRAY['circadian rhythm', 'sleep regulation', 'melatonin', 'cortisol'], ARRAY['Process C regulates sleep timing via 24h circadian clock', 'Process S builds sleep pressure during wake periods', 'Light is the dominant zeitgeber for circadian synchronization'], ARRAY['Sleep optimization protocols', 'Light therapy timing strategies', 'Circadian rhythm reset techniques'], '{"kai": 5, "sascha": 2, "lucy": 3}'),

('10.1371/journal.pone.0251478', 'Heart Rate Variability as Biomarker for Stress Management Interventions', ARRAY['Thayer J.F.', 'Åhs F.', 'Fredrikson M.', 'Sollers J.J.', 'Wager T.D.'], 'Meta-analysis examining HRV as a reliable biomarker for stress assessment and intervention effectiveness, establishing protocols for stress management.', 'PLOS ONE', 2021, ARRAY['heart rate variability', 'stress management', 'autonomic nervous system', 'biofeedback'], ARRAY['HRV reflects sympatho-vagal balance and stress resilience', 'RMSSD and SDNN are reliable stress indicators', 'HRV-biofeedback shows 45-60% symptom reduction'], ARRAY['Stress assessment protocols', 'Vagus nerve stimulation techniques', 'Biofeedback training programs'], '{"kai": 5, "sascha": 4, "lucy": 2}'),

('10.3389/fpsyg.2018.02141', 'Self-Determination Theory and Exercise Adherence: The Role of Basic Psychological Needs', ARRAY['Teixeira P.J.', 'Carraça E.V.', 'Markland D.', 'Silva M.N.', 'Ryan R.M.'], 'Comprehensive review of Self-Determination Theory application in exercise contexts, examining autonomy, competence, and relatedness effects on long-term adherence.', 'Frontiers in Psychology', 2018, ARRAY['self-determination theory', 'exercise adherence', 'motivation', 'behavioral change'], ARRAY['Intrinsic motivation shows +0.45 adherence correlation', 'Autonomy is strongest predictor of long-term adherence', 'External regulation negatively predicts sustainability (-0.28)'], ARRAY['Motivational interviewing techniques', 'Autonomous goal-setting protocols', 'Adherence optimization strategies'], '{"kai": 5, "sascha": 2, "lucy": 4}'),

('10.1186/s12888-019-2018-5', 'Mindfulness-Based Cognitive Therapy: Mechanisms and Clinical Applications', ARRAY['Goyal M.', 'Singh S.', 'Sibinga E.M.', 'Gould N.F.', 'Rowland-Seymour A.'], 'Systematic review and meta-analysis of MBCT effectiveness, examining neuroplastic changes and clinical outcomes across stress, anxiety, and depression populations.', 'BMC Psychiatry', 2019, ARRAY['mindfulness', 'cognitive therapy', 'stress reduction', 'neuroplasticity'], ARRAY['MBCT shows -0.41 stress reduction effect size', 'Anxiety reduction: -0.37 effect size', 'Neuroplastic changes in prefrontal cortex after 8 weeks'], ARRAY['8-week MBCT protocols', 'Present-moment awareness training', 'Meta-cognitive therapy techniques'], '{"kai": 5, "sascha": 1, "lucy": 3}');

-- Insert Kai's comprehensive knowledge base entries
INSERT INTO public.coach_knowledge_base (coach_id, knowledge_type, title, content, expertise_area, priority_level, tags) VALUES

-- Priority 1: Core Philosophy and Principles
('kai', 'philosophy', 'The Neuroplastic Mindset: Your Brain as Adaptive Partner', 'Your brain is not fixed - it''s your most adaptable training partner. Every thought, every habit, every recovery protocol literally reshapes your neural networks. We''re not just changing behavior; we''re rewiring the control center of your performance. Neuroplasticity research shows that focused attention and deliberate practice create measurable structural changes in weeks, not years. This isn''t motivation fluff - this is neuroscience-backed transformation where every mindful moment builds a stronger, more resilient brain.', 'neuroplasticity', 1, ARRAY['neuroplasticity', 'brain_adaptation', 'mindset', 'evidence_based']),

('kai', 'methodology', 'Smart Recovery: The Intelligence of Rest', 'Recovery isn''t passive - it''s the most active training you''ll ever do. While you sleep, your brain processes, consolidates, and optimizes everything from motor patterns to emotional resilience. REM sleep doesn''t just restore; it actively reorganizes your neural networks for peak performance. We''re going to make your recovery as strategic and measurable as your training. Every breath technique, every sleep optimization protocol, every stress management tool is precision engineering for your nervous system.', 'recovery_optimization', 1, ARRAY['smart_recovery', 'sleep_optimization', 'nervous_system', 'strategic_rest']),

-- Priority 2: Core Training Methodologies  
('kai', 'protocol', 'The Habit Loop 2.0: Neuroscience-Based Behavior Design', 'Traditional habit formation misses the neural reality. The real loop isn''t cue-routine-reward; it''s striatal pathway optimization. Your dorsomedial striatum handles goal-directed behavior while your dorsolateral striatum automates habits. We''re going to hack this transition through dopamine pattern modification, environmental design, and strategic repetition. Research shows the "ascending spiral" - conscious practice in the DMS eventually transfers to automatic execution in the DLS. This is behavioral architecture, not willpower.', 'habit_formation', 2, ARRAY['habit_formation', 'striatum', 'dopamine', 'automation']),

('kai', 'protocol', 'Circadian Performance Hacking: Master Your Internal Clock', 'Your circadian rhythm isn''t just about sleep - it''s your performance operating system. The suprachiasmatischer nucleus orchestrates everything from cortisol release to cognitive peak windows. Light exposure at 6-8am advances your phase, while 19-21:00 light delays it. The melatonin-cortisol dance follows a precise 5-hour offset that we can optimize. We''re going to synchronize your training, nutrition, and recovery to your biological prime time. This isn''t scheduling - this is chronobiology-based optimization.', 'circadian_optimization', 2, ARRAY['circadian_rhythm', 'light_therapy', 'melatonin', 'cortisol_optimization']),

('kai', 'protocol', 'HRV-Guided Stress Mastery: Your Autonomic Intelligence', 'Heart Rate Variability is your nervous system''s real-time feedback loop. RMSSD reflects parasympathetic recovery capacity, while LF/HF ratio reveals sympatho-vagal balance. When HRV drops, it''s not fatigue - it''s autonomic overload demanding strategic intervention. The 4-4-6-2 breathing protocol specifically targets vagal tone through baroreflex activation. We''re going to train your autonomic nervous system like a muscle, using biofeedback to build stress resilience and recovery efficiency.', 'stress_management', 2, ARRAY['heart_rate_variability', 'autonomic_nervous_system', 'breathing_protocols', 'stress_resilience']),

-- Priority 3: Specific Protocols and Techniques
('kai', 'protocol', 'Sleep Architecture Optimization: Engineering Recovery', 'Sleep isn''t unconsciousness - it''s the brain''s most sophisticated optimization process. NREM slow-wave sleep sorts and filters daily information while REM consolidates emotional memories and motor skills. The cAMP/MAPK/CRE signaling pathway peaks during REM, driving protein synthesis critical for adaptation. Sleep debt creates cognitive deficits lasting days beyond apparent recovery. We''re optimizing sleep architecture through temperature regulation, light exposure timing, and recovery sleep strategies.', 'sleep_optimization', 3, ARRAY['sleep_architecture', 'REM_sleep', 'NREM_sleep', 'memory_consolidation']),

('kai', 'protocol', 'MBCT Integration: Mindfulness as Neural Training', 'Mindfulness-Based Cognitive Therapy isn''t relaxation - it''s focused neural training. MBCT creates measurable increases in prefrontal cortex activity while reducing amygdala reactivity. The key is decentering: observing thoughts as mental events, not personal truths. Eight weeks of practice shows -0.41 stress reduction and -0.37 anxiety reduction effect sizes. Meta-cognitive awareness breaks automatic thought patterns, creating space for conscious choice. This is neural flexibility training disguised as meditation.', 'mindfulness_training', 3, ARRAY['MBCT', 'decentering', 'prefrontal_cortex', 'meta_cognition']),

('kai', 'protocol', 'Motivation Science: Self-Determination Theory Application', 'Motivation isn''t willpower - it''s psychological need satisfaction. The SDT framework reveals three core needs: autonomy, competence, and relatedness. Intrinsic motivation correlates +0.45 with adherence while external regulation shows -0.28. Autonomous goal pursuit activates reward pathways sustainably, while external pressure triggers stress responses. We''re building motivation architecture through need satisfaction, not forcing compliance through discipline.', 'motivation_psychology', 3, ARRAY['self_determination_theory', 'autonomy', 'intrinsic_motivation', 'adherence']),

-- Priority 4: Advanced Applications
('kai', 'application', 'Neuroplastic Recovery Periodization', 'Different neural systems have different adaptation timelines. Neuromuscular coordination adapts in 2-4 weeks, cardiovascular systems in 4-8 weeks, structural changes in 8-12 weeks. Recovery protocols must match these timelines. Active recovery stimulates parasympathetic activation without adding training stress. We''re periodizing recovery interventions to match adaptation phases, optimizing when the brain is most plastic and receptive to change.', 'recovery_periodization', 4, ARRAY['adaptation_timelines', 'neuroplastic_windows', 'parasympathetic_training']),

('kai', 'application', 'Biofeedback-Enhanced Performance States', 'Biofeedback transforms unconscious processes into conscious skills. HRV biofeedback shows 45-60% symptom reduction in stress-related disorders through real-time autonomic training. Combining HRV with neurofeedback creates optimal performance states on demand. This isn''t just monitoring - it''s nervous system skills training. We''re building the ability to access flow states, recovery modes, and peak performance zones through conscious autonomic control.', 'biofeedback_training', 4, ARRAY['biofeedback', 'performance_states', 'flow_training', 'autonomic_control']),

-- Priority 5: Supplementary Knowledge
('kai', 'science', 'The Neurobiology of Habit Automation', 'Habit formation follows predictable neural pathways. The ascending spiral hypothesis explains how goal-directed behavior (dorsomedial striatum) transitions to automatic habits (dorsolateral striatum) through dopamine-mediated plasticity. Once habits are established, dopamine patterns reverse - increasing at initiation, decreasing at completion. Understanding this mechanism allows targeted intervention at specific phases of habit development and modification.', 'neurobiology', 5, ARRAY['ascending_spiral', 'dopamine_patterns', 'habit_neurobiology']),

('kai', 'recovery', 'Advanced Sleep Recovery Protocols', 'Sleep debt impacts cognitive domains differentially. Simple tasks recover after one night, but higher cognitive functions require 2+ nights for full restoration. Hippocampal connectivity recovers after two nights, but memory performance remains impaired longer. Recovery sleep strategies must account for these differential timelines. Strategic napping, light therapy, and circadian reset protocols accelerate recovery when properly timed to individual chronotypes.', 'sleep_recovery', 5, ARRAY['sleep_debt', 'cognitive_recovery', 'chronotype_optimization']);

-- Update Kai's specialization with enhanced description
UPDATE public.coach_specializations 
SET specialization_description = 'Der Mindset & Recovery Spezialist verbindet Neurowissenschaften mit praktischer Anwendung für optimale mentale Performance und intelligente Regeneration. Fokussiert auf Neuroplastizität-basierte Gewohnheitsbildung, evidenzbasierte Schlafoptimierung, wissenschaftlich fundiertes Stressmanagement und motivationspsychologische Adherence-Strategien.',
    core_philosophy = 'Dein Gehirn ist dein anpassungsfähigster Trainingspartner. Jede bewusste Entscheidung formt neue neuronale Pfade, jede Erholungsphase optimiert deine Leistungsfähigkeit. Smart Recovery bedeutet aktive Regeneration durch Neurowissenschaften.',
    expertise_areas = ARRAY['Neuroplastizität und Gewohnheitsbildung', 'Schlafoptimierung und Circadiane Rhythmen', 'HRV-basiertes Stressmanagement', 'Motivationspsychologie und Adherence', 'Mindfulness-Based Cognitive Therapy', 'Biofeedback-Training'],
    knowledge_focus = ARRAY['Synaptic Plasticity Mechanisms', 'Zwei-Prozess-Schlafmodell', '4-4-6-2 Atemprotokoll', 'Self-Determination Theory', 'MBCT 8-Wochen-Protokoll', 'HRV-Biofeedback-Training'],
    methodology = 'Evidenzbasierte Interventionen durch Neurowissenschaften, messbare Biomarker für Stress und Erholung, neuroplastizitäts-guidierte Verhaltensänderung und chronobiologie-optimierte Performance-Fenster.'
WHERE coach_id = 'kai';