-- Add English quotes for men
INSERT INTO men_quotes (quote_text, author, language) VALUES
('The body is a temple. Keep it pure and clean for the soul to reside in.', 'B.K.S. Iyengar', 'en'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'en'),
('Your body can do it. It''s your mind that you have to convince.', 'Unknown', 'en'),
('The groundwork for all happiness is good health.', 'Leigh Hunt', 'en'),
('Health is not about the weight you lose, but about the life you gain.', 'Unknown', 'en'),
('A healthy outside starts from the inside.', 'Robert Urich', 'en'),
('Take care of your body. It''s the only place you have to live.', 'Jim Rohn', 'en'),
('The first wealth is health.', 'Ralph Waldo Emerson', 'en'),
('To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear.', 'Buddha', 'en'),
('Health is a state of complete physical, mental and social well-being.', 'World Health Organization', 'en'),
('The best investment you can make is in your own health.', 'Unknown', 'en'),
('A fit body, a calm mind, a house full of love. These things cannot be bought – they must be earned.', 'Naval Ravikant', 'en'),
('Your health is an investment, not an expense.', 'Unknown', 'en'),
('What we plant today, we harvest tomorrow.', 'Unknown', 'en'),
('Discipline is choosing between what you want now and what you want most.', 'Abraham Lincoln', 'en'),
('Progress, not perfection.', 'Unknown', 'en'),
('Small steps every day lead to big changes one year from now.', 'Unknown', 'en'),
('The only bad workout is the one that didn''t happen.', 'Unknown', 'en'),
('You are stronger than you think.', 'Unknown', 'en'),
('Don''t put off tomorrow what you can do today.', 'Benjamin Franklin', 'en'),
('Success is the sum of small efforts, repeated day in and day out.', 'Robert Collier', 'en'),
('The pain you feel today will be the strength you feel tomorrow.', 'Unknown', 'en'),
('Champions are made from something deep inside them: a desire, a dream, a vision.', 'Muhammad Ali', 'en'),
('It''s not about being perfect. It''s about being better than you were yesterday.', 'Unknown', 'en'),
('The only way to do great work is to love what you do.', 'Steve Jobs', 'en');

-- Add English quotes for women
INSERT INTO women_quotes (quote_text, author, language) VALUES
('Dream your life beautifully and make those dreams reality.', 'Marie Curie', 'en'),
('Be yourself; everyone else is already taken.', 'Oscar Wilde', 'en'),
('Be the heroine of your life, not the victim.', 'Nora Ephron', 'en'),
('Don''t let yourself be defeated, be cheeky and wild and wonderful!', 'Astrid Lindgren', 'en'),
('Life is not measured by the number of breaths we take, but by the moments that take our breath away.', 'Maya Angelou', 'en'),
('A woman is like a tea bag – you never know how strong she is until she gets in hot water.', 'Eleanor Roosevelt', 'en'),
('The most courageous act is still to think for yourself. Aloud.', 'Coco Chanel', 'en'),
('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis', 'en'),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'en'),
('Well-behaved women seldom make history.', 'Laurel Thatcher Ulrich', 'en'),
('She believed she could, so she did.', 'R.S. Grey', 'en'),
('Strong women don''t have attitudes, they have standards.', 'Unknown', 'en'),
('A strong woman looks a challenge dead in the eye and gives it a wink.', 'Gina Carey', 'en'),
('You are braver than you believe, stronger than you seem, and smarter than you think.', 'A.A. Milne', 'en'),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'en'),
('Don''t be afraid to give up the good to go for the great.', 'John D. Rockefeller', 'en'),
('The only impossible journey is the one you never begin.', 'Tony Robbins', 'en'),
('Your only limit is your mind.', 'Unknown', 'en'),
('Push yourself because no one else is going to do it for you.', 'Unknown', 'en'),
('Great things never come from comfort zones.', 'Unknown', 'en'),
('Dream it. Wish it. Do it.', 'Unknown', 'en'),
('Success doesn''t just find you. You have to go out and get it.', 'Unknown', 'en'),
('The harder you work for something, the greater you''ll feel when you achieve it.', 'Unknown', 'en'),
('Dream bigger. Do bigger.', 'Unknown', 'en'),
('Don''t stop when you''re tired. Stop when you''re done.', 'Unknown', 'en');