-- Deutsche Übersetzungen für Dr. Vita Femina's Knowledge Base Einträge

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Zyklusbasiertes Training: Phasenspezifische Programmierung', 'cycle_sync_training_de', 'protocol', 'Training abgestimmt auf Menstruationsphasen maximiert Performance und reduziert Verletzungsrisiko. Follikelphase (Tag 1-14): Höheres Östrogen verstärkt Kraftzuwächse - plane PR-Versuche und HIIT. Lutealphase (Tag 15-28): Progesteron steigt - fokussiere auf Technik, Mobilität und moderate Intensität. Ovulation: Peak-Power-Fenster - Sprints, Krafttraining. Überwache Symptome und passe RPE um ±1 an. Tracke Zyklusdaten und individualisiere das Programm für jede Phase.', 'dr_vita_femina', 1, ARRAY['menstruationszyklus', 'phasentraining', 'östrogen', 'progesteron', 'rpe_anpassung'], now(), now()),

('Eisen- und Mikronährstoff-Auffüllung für Athletinnen', 'micronutrient_repletion_de', 'application', 'Eisenmangel betrifft 30% aktiver Frauen. Ferritin <30 ng/mL beeinträchtigt VO2max und Kognition. Protokoll: 45mg elementares Eisen mit Vitamin C auf nüchternen Magen, Retest nach 8 Wochen. Inkludiere Häm-Quellen (150g mageres Rindfleisch 2x/Woche) und Nicht-Häm + Vitamin C Kombos (Linsen + Paprika). Überwache Ferritin, B12 und Vitamin D alle 6 Monate.', 'dr_vita_femina', 2, ARRAY['eisenmangel', 'ferritin', 'athletinnen', 'mikronährstoffe', 'performance'], now(), now()),

('Endometriose Anti-entzündliche Ernährungsstrategie', 'endometriosis_nutrition_de', 'application', 'Endometriose-bedingte Entzündungen können durch Ernährung gemildert werden. Omega-3 (2-3g EPA+DHA) reduziert Prostaglandin E2. Curcumin (500mg) hemmt NF-κB. Low-FODMAP + glutenfrei reduziert Schmerzwerte um 40%. Betone Kreuzblütler für DIM und I3C zur Unterstützung des Östrogen-Stoffwechsels. Führe Symptom-Tagebuch und passe Lebensmittel entsprechend an.', 'dr_vita_femina', 3, ARRAY['endometriose', 'entzündungshemmend', 'omega_3', 'curcumin', 'low_fodmap'], now(), now()),

('Trimester-Trainingsrichtlinien: Sichere Kraftprogression', 'pregnancy_training_de', 'protocol', 'Schwangerschaftstraining muss sich per Trimester anpassen. T1: Halte Pre-Schwangerschaftsroutine mit RPE ≤7. Vermeide Überhitzung. T2: Eliminiere Rückenlage-Übungen >3 Min, führe Stabilitätsarbeit ein, Kraft bei 60-70% 1RM. T3: Fokus auf Mobilität, Beckenboden und leichten Widerstand. Wöchentliche Volumenreduktion ~15%. Überwache RPE, HF und Atemlosigkeit.', 'dr_vita_femina', 1, ARRAY['schwangerschaftstraining', 'trimester_richtlinien', 'beckenboden', 'rpe', 'stabilität'], now(), now()),

('Postpartum Kern-Rehabilitationsprotokoll', 'postpartum_rehab_de', 'protocol', 'Diastasis recti erfordert stufenweise Kern-Reha. Woche 0-2: Zwerchfellatmung und Beckenneigungs. Woche 3-6: Rückenlage Fersenschieber und Dead-Bug-Progressionen. Woche 7-12: Plank-Varianten unter 10s Halten. Progressionskriterien: Spalt <2cm, kein Doming. Kombiniere mit 20-30min täglichem Gehen und gradueller Belastungsrückkehr.', 'dr_vita_femina', 2, ARRAY['postpartum', 'diastasis_recti', 'kern_reha', 'gehen', 'progressionskriterien'], now(), now()),

('Menopause Kraft- und Knochendichte-Plan', 'menopause_strength_de', 'application', 'Östrogenrückgang beschleunigt Knochenverlust. Schweres Widerstandstraining (80-85% 1RM, 3-5 Sätze x 5 Wdh) 2x/Woche kombiniert mit hochintensiven Plyometrics (Box Jumps, Seilspringen) 2x/Woche verbessert Lendenwirbel-BMD (+0.4 SMD). Protein 1.6g/kg + Calcium 1200mg + Vitamin D 2000 IU unterstützen Anpassung. Tracke DEXA alle 12 Monate.', 'dr_vita_femina', 2, ARRAY['menopause', 'knochendichte', 'schweres_heben', 'plyometrics', 'protein', 'dexa'], now(), now()),

('Female Athlete Triad / RED-S Monitoring', 'female_athlete_health_de', 'screening_tool', 'Relative Energiedefizit im Sport (RED-S) Risikoindikatoren: Menstruationsstörungen, niedrige Energieverfügbarkeit (<30kcal/kg FFM), BMD Z-Score <-1. Protokoll: monatliche Zyklusüberprüfung, wöchentliche Energiebilanz-Review, jährliche DEXA. Symptome lösen Diäterhöhung um 300 kcal und Trainingsbelastungsreduktion um 15% aus.', 'dr_vita_femina', 1, ARRAY['red_s', 'energieverfügbarkeit', 'zyklusmonitoring', 'bmd', 'trainingsanpassung'], now(), now()),

('Hormonelle Verhütung Auswirkung auf Performance', 'contraception_performance_de', 'science', 'Kombinierte orale Kontrazeptiva (KOK) können VO2max um 5-10% reduzieren und oxidative Stressmarker erhöhen. Reine Gestagen-Methoden zeigen geringen Performance-Einfluss. Überwache Performance-Trends 3 Monate nach KOK-Beginn. Bei anhaltendem Rückgang erwäge nicht-hormonelle Methoden. Supplementiere mit Antioxidantien (Vitamin C 500mg, E 200IU) um oxidative Belastung zu mildern.', 'dr_vita_femina', 3, ARRAY['verhütung', 'performance', 'vo2max', 'oxidativer_stress', 'antioxidantien'], now(), now()),

('Frauenspezifische Schlafoptimierungsstrategien', 'female_sleep_de', 'protocol', 'Frauen erleben mehr Schlafstörungen um Menstruation und Menopause. Magnesium-Bisglycinat 400mg, Sauerkirschextrakt 500mg verbessern Schlafqualität. Schlafumgebung: 18°C optimal. Lutealphase: erhöhe komplexe Kohlenhydrate zum Abendessen (30-50g) für Serotonin-Produktion. Menopause: kühle Bettwäsche und Abendyoga reduzieren Hitzewallungen um 50%. Tracke Schlafmetriken und passe an.', 'dr_vita_femina', 2, ARRAY['schlaf', 'frauen', 'schlafstörungen', 'lutealphase', 'menopause_hitzewallungen'], now(), now()),

('Weibliche Darm-Hirn-Achse: Stimmung & Mikrobiom', 'gut_brain_female_de', 'science', 'Die weibliche Darm-Hirn-Achse wird von Östrogenspiegeln beeinflusst. Lactobacillus-reiche fermentierte Lebensmittel erhöhen GABA-Produktion und reduzieren PMS-Angst. Probiotik-Protokoll: Lactobacillus reuteri 108 CFU täglich reduziert depressive Symptome um 32%. Präbiotisches Inulin (10g) stärkt Bifidobakterien und verbessert Stimmung. Tracke Stimmungswerte und GI-Symptome.', 'dr_vita_femina', 3, ARRAY['darm_hirn_achse', 'östrogen', 'lactobacillus', 'pms', 'probiotika', 'präbiotika'], now(), now());