-- Deutsche Übersetzungen für weitere Sascha Knowledge Base Einträge (Batch 5/6)

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Blockperiodisierung im Military-Setting', 'periodization_de', 'scientific_research', 'Blockperiodisierung führt in Tactical Populations zu effizienter Zielentwicklung und geringerem Verletzungsrisiko. Blöcke: Kraft, Ausdauer, Technik, Recovery, 4–6 Wochen pro Block. Wechsele Trainingsblöcke planmäßig zur Plateau-Freigabe.', 'sascha', 3, ARRAY['blockperiodisierung', 'militär', 'tactical', 'verletzungsprävention'], now(), now()),

('Combat Fitness Test – ACFT', 'tactical_training_de', 'operational_standard', 'Erfolg korreliert mit Vielseitigkeit: Kraft, Explosivität, Core, Cardio. 6 Event-Test: Deadlift, Standing Power Throw, Hand-Release Push-up, Sprint-Drag-Carry, Leg Tuck, 2 Mile Run. Trainingspläne entlang der ACFT-Events strukturieren.', 'sascha', 3, ARRAY['acft', 'militär', 'combat_fitness_test'], now(), now()),

('High-Intensity Functional Training (HIFT)', 'hiit_de', 'controlled_study', '11.6% Steigerung im 12-min Lauftest vs. 5.7% bei traditionellem Militärtraining. 2–3x/Woche hochintensive Zirkel, Fokus: Ganzkörperkraft, Cardio. Erschaffe battle-tested circuits für Muskelaufbau und Ausdauer.', 'sascha', 3, ARRAY['hift', 'functional_training', 'militär', 'circuits'], now(), now()),

('HIIT vs. Ausdauertraining (MICE)', 'hiit_de', 'meta_analysis', 'HIIT steigert VO2max doppelt so schnell wie MICE (14.7% vs. 7.9%, 16 Wochen). 2x HIIT, 1x MICE pro Woche für Synergie. Kombiniere intensive und moderate Protokolle.', 'sascha', 3, ARRAY['hiit', 'mice', 'vo2max', 'meta_analyse', 'vergleich'], now(), now()),

('HIIT vs. klassisches Ausdauertraining', 'hiit_de', 'scientific_research', 'HIIT steigert VO2max 2x so schnell wie MICE (14.7% vs. 7.9% in 16 Wochen). Zur schnellen VO2max-Steigerung zwei HIIT- und eine MICE-Session wöchentlich einplanen. Kombiniere intensive und moderate Intervalle zur Synergienutzung.', 'sascha', 3, ARRAY['hiit', 'mice', 'vo2max', 'meta_analyse'], now(), now()),

('IGF-1 und anabole Hormon-Kaskade beim Mann', 'male_hormone_optimization_de', 'science', 'IGF-1 korreliert mit aerober Fitness und Muskelausdauer, aber nicht direkt mit Hypertrophie. Mechanischer Stress durch schweres Training stimuliert lokale IGF-1-Produktion (MGF). Kombiniertes Kraft- und Ausdauertraining optimiert systemisches IGF-1. Alter 35-65: IGF-1 sinkt 1-2%/Jahr, durch Training teilweise reversibel.', 'sascha', 3, ARRAY['igf_1', 'growth_factors', 'anabole_hormone', 'mechanischer_stress', 'aging'], now(), now()),

('Intensity Zones: Precision Targeting', 'heart_rate_training_de', 'protocol', 'Training ohne Herzfrequenzzonen ist wie Schießen ohne Zielen. Zone 1 (50-65% HRmax): Aktive Erholung, aerobe Basis. Zone 2 (65-75% HRmax): Aerobe Kapazität, Fettoxidation. Zone 3 (75-85% HRmax): Aerobe Schwelle, Laktat-Steady-State. Zone 4 (85-95% HRmax): VO2max-Intervalle, maximale aerobe Power. Zone 5 (95-100% HRmax): Neuromuskuläre Power, anaerobe Kapazität.', 'sascha', 3, ARRAY['herzfrequenzzonen', 'intensitäts_targeting', 'präzisionstraining'], now(), now()),

('MetCon Circuits', 'metabolic_conditioning_de', 'controlled_study', 'MetCon-Zirkel verbessern Ausdauer, Kraft und Work Capacity zugleich. Workouts 30–45min, 6–12 Multi-Joint Übungen. MetCon als Grundbaustein military Fitness.', 'sascha', 3, ARRAY['metcon', 'work_capacity', '30_45min', '6_12_übungen'], now(), now()),

('Movement Quality: The FMS Battle Assessment', 'movement_quality_de', 'protocol', 'Bewegungsqualität ist taktische Bereitschaft. Functional Movement Screen (FMS) identifiziert schwache Glieder in deiner kinetischen Kette. Score von 14+ korreliert mit reduziertem Verletzungsrisiko. Sieben fundamentale Bewegungsmuster: Deep Squat, Hurdle Step, In-Line Lunge, Shoulder Mobility, Active Straight Leg Raise, Trunk Stability Push-up, Rotary Stability. Adressiere Defizite sofort - eine Kette ist nur so stark wie ihr schwächstes Glied.', 'sascha', 3, ARRAY['fms', 'movement_screening', 'verletzungsprävention', 'funktionelle_bewegung'], now(), now()),

('Navy SEAL Standards – VO2, Kraft, Schwimmen', 'special_forces_de', 'selection_research', 'VO2max > 55 ml/kg/min und deutlich-über-Minimum-Werte erhöhen Erfolgsrate signifikant. Kombiniere HIIT, Langstreckenlauf und Kraftprotokolle in Multiwochenplänen. Tracke Rekrut-Standards und optimiere gezielt für Ausdauer und Kraft.', 'sascha', 3, ARRAY['navy_seal', 'vo2max', 'selection_standards'], now(), now());