-- Deutsche Übersetzungen für Lucy's Knowledge Base (Batch 1/2)

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Entzündungshemmende Ernährung', 'anti_inflammatory_nutrition_de', 'nutritional_guidance', 'Chronische Entzündungen durch gezielte Lebensmittel reduzieren: Omega-3-reiche Fische 2-3x/Woche, dunkles Blattgemüse täglich, Beeren und Nüsse als Antioxidantien-Quellen. Vermeiden: verarbeitete Lebensmittel, Zucker, Transfette. Kurkuma mit schwarzem Pfeffer, Ingwer, grüner Tee als natürliche Entzündungshemmer. CRP-Werte als Biomarker für Entzündungsstatus überwachen.', 'lucy', 4, ARRAY['entzündungshemmend', 'omega_3', 'antioxidantien', 'crp_werte'], now(), now()),

('Kalorienaufnahme-Wissenschaft', 'caloric_science_de', 'metabolic_science', 'Energiebilanz vs. Kalorienqualität: 100 Kalorien Nüsse ≠ 100 Kalorien Zucker in metabolischer Wirkung. Thermischer Effekt: Protein verbrennt 20-30% seiner Kalorien bei Verdauung, Kohlenhydrate 5-10%, Fette 0-5%. Adaptive Thermogenese: Stoffwechsel passt sich bei Kalorienrestriktion an. Timing matters: gleiche Kalorienmenge zu verschiedenen Tageszeiten hat unterschiedliche metabolische Effekte.', 'lucy', 3, ARRAY['energiebilanz', 'thermischer_effekt', 'adaptive_thermogenese', 'kalorienbilanz'], now(), now()),

('Intervallfasten Optimierung', 'intermittent_fasting_de', 'metabolic_optimization', 'IF-Protokolle für verschiedene Ziele: 16:8 für Anfänger und Gewichtsreduktion, 18:6 für verbesserte Insulinsensitivität, 20:4 für fortgeschrittene Autophagie-Aktivierung. Frauen: kürzere Fastenfenster während Menstruation. Fastenbrechen mit Protein und gesunden Fetten, nicht mit Kohlenhydraten. HbA1c und Nüchternglukose als Erfolgsmarker überwachen.', 'lucy', 4, ARRAY['intervallfasten', '16_8_protokoll', 'autophagie', 'insulinsensitivität'], now(), now()),

('Lifestyle-Medizin Integration', 'lifestyle_medicine_de', 'holistic_health', 'Die 6 Säulen der Lifestyle-Medizin: Ernährung (vollwertig, pflanzenbasiert), Bewegung (150 min/Woche), Schlaf (7-9h), Stressmanagement, soziale Verbindungen, Vermeidung von Risikoverhalten. 80% chronischer Krankheiten sind durch Lifestyle-Faktoren beeinflussbar. Personalisierte Ansätze basierend auf Genetik, Mikrobiom und Biomarkern für optimale Präventionsstrategien.', 'lucy', 5, ARRAY['lifestyle_medizin', 'präventionsmedizin', 'chronische_krankheiten', 'ganzheitliche_gesundheit'], now(), now()),

('Metabolische Flexibilität', 'metabolic_flexibility_de', 'metabolic_optimization', 'Fähigkeit zwischen Glukose- und Fettverbrennung zu wechseln. Training: Nüchterntraining für Fettoxidation, Carb-Cycling für Glykogen-Depletion/Repletion. Ernährung: Ketogene Phasen alternierend mit Higher-Carb Tagen. Biomarker: Ketonkörper, Respiratorischer Quotient, Glukose-Variabilität. Ziel: optimale Energieproduktion unabhängig von konstanter Nahrungszufuhr.', 'lucy', 4, ARRAY['metabolische_flexibilität', 'fettoxidation', 'ketonkörper', 'carb_cycling'], now(), now()),

('Mikronährstoff-Optimierung', 'micronutrient_optimization_de', 'nutritional_science', 'Individueller Mikronährstoff-Bedarf basierend auf Genetik, Lebensstil, Umwelt. Kritische Nährstoffe: Vitamin D (25-OH >30ng/ml), B12 (>400 pg/ml), Magnesium, Zink, Omega-3. Synergien nutzen: Vitamin C + Eisen, Vitamin D + K2 + Magnesium. Laborwerte > RDA für optimale Funktion. Bioavailabilität durch richtige Formen und Timing maximieren.', 'lucy', 5, ARRAY['mikronährstoffe', 'vitamin_d', 'bioavailabilität', 'nährstoff_synergien'], now(), now()),

('Nährstoff-Timing Strategien', 'nutrient_timing_de', 'performance_nutrition', 'Chrono-Ernährung für optimale Absorption: Protein gleichmäßig über Tag verteilt (20-30g/Mahlzeit), Kohlenhydrate primär periworkout und morgens, Fette abends für Hormonproduktion. Post-Workout-Window: 30-60 min für Glykogen-Resynthese. Koffein: 6h vor Schlafenszeit stoppen. Melatonin-Produktion durch blaues Licht und späte Mahlzeiten nicht beeinträchtigen.', 'lucy', 4, ARRAY['nährstoff_timing', 'post_workout', 'chrono_ernährung', 'glykogen_resynthese'], now(), now()),

('Plateau-Durchbruch Strategien', 'plateau_breaking_de', 'advanced_nutrition', 'Gewichts-/Leistungsplateaus durchbrechen: Refeed-Days alle 7-14 Tage bei Diät, Kalorienzeittaktung ändern, Makronährstoff-Cycling, neue Trainingsreize. Hormonelle Optimierung: Leptin, Ghrelin, Cortisol, Schilddrüsenhormone checken. Methylierung und Entgiftung unterstützen. Darmmikrobiom reset durch Präbiotika/Probiotika. Manchmal Pause = Progress.', 'lucy', 4, ARRAY['plateau_durchbruch', 'refeed_days', 'hormonelle_optimierung', 'darmmikrobiom'], now(), now()),

('Polyphenol-Optimierung', 'polyphenol_optimization_de', 'phytonutrient_science', 'Polyphenole als Longevity-Booster: 800-1000mg täglich aus verschiedenen Quellen. Resveratrol (Trauben), EGCG (grüner Tee), Quercetin (Zwiebeln), Curcumin (Kurkuma). Bioavailabilität steigern: mit Fett konsumieren, Piperin zugeben, fermentierte Formen wählen. NF-κB-Hemmung, SIRT1-Aktivierung, mitochondriale Biogenese fördern. Rotation verschiedener Polyphenol-Quellen für Synergien.', 'lucy', 4, ARRAY['polyphenole', 'resveratrol', 'longevity', 'sirt1_aktivierung'], now(), now()),

('Stress-Schlaf-Stoffwechsel Verbindung', 'stress_sleep_metabolism_de', 'metabolic_health', 'Cortisol-Dysregulation stört Glukose-Homöostase und Fettstoffwechsel. Chronischer Stress → Insulinresistenz → viszerales Fett. Schlafmangel reduziert Leptin, erhöht Ghrelin → Heißhunger. Adaptogene: Ashwagandha, Rhodiola für HPA-Achsen-Balance. Magnesium, L-Theanin, Glycin für besseren Schlaf. Cortisol-Rhythmus durch Morgenlicht und Abendroutine optimieren.', 'lucy', 5, ARRAY['stress_stoffwechsel', 'cortisol_regulation', 'hpa_achse', 'adaptogene'], now(), now());