-- Insert Dr. Vita Femina knowledge base entries for female-specific health and training

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Cycle Sync Training: Phase-Specific Programming', 'cycle_sync_training', 'protocol', 'Training aligned with menstrual phases maximizes performance and reduces injury risk. Follicular Phase (Days 1-14): Higher estrogen enhances strength gains—schedule PR attempts and HIIT. Luteal Phase (Days 15-28): Progesterone rises—focus on technique, mobility, and moderate intensity. Ovulation: Peak power window—sprints, power lifts. Monitor symptoms and adjust RPE by ±1. Track cycle data and tailor program for each phase.', 'dr_vita_femina', 1, ARRAY['menstrual_cycle', 'phase_training', 'estrogen', 'progesterone', 'RPE_adjustment'], now(), now()),

('Iron & Micronutrient Repletion for Female Athletes', 'micronutrient_repletion', 'application', 'Iron deficiency affects 30% of active women. Ferritin <30 ng/mL impairs VO2max and cognition. Protocol: 45mg elemental iron with vitamin C on empty stomach, retest in 8 weeks. Include heme sources (150g lean beef 2x weekly) and non-heme + vitamin C combos (lentils + bell pepper). Monitor ferritin, B12, and vitamin D every 6 months.', 'dr_vita_femina', 2, ARRAY['iron_deficiency', 'ferritin', 'female_athletes', 'micronutrients', 'performance'], now(), now()),

('Endometriosis Anti-Inflammatory Nutrition Blueprint', 'endometriosis_nutrition', 'application', 'Endometriosis-related inflammation can be mitigated by nutrition. Omega-3 (2-3g EPA+DHA) reduces prostaglandin E2. Curcumin (500mg) inhibits NF-κB. Low-FODMAP + gluten-free reduces pain scores by 40%. Emphasize cruciferous vegetables for DIM and I3C to support estrogen metabolism. Track symptom diary and adjust foods accordingly.', 'dr_vita_femina', 3, ARRAY['endometriosis', 'anti_inflammatory', 'omega_3', 'curcumin', 'low_FODMAP'], now(), now()),

('Trimester Training Guidelines: Safe Strength Progression', 'pregnancy_training', 'protocol', 'Pregnancy training must adapt by trimester. T1: Maintain pre-pregnancy routine with RPE ≤7. Avoid overheating. T2: Eliminate supine exercises >3 min, introduce stability work, strength at 60-70% 1RM. T3: Focus on mobility, pelvic floor, and light resistance. Weekly volume reduction ~15%. Monitor RPE, HR, and breathlessness.', 'dr_vita_femina', 1, ARRAY['pregnancy_training', 'trimester_guidelines', 'pelvic_floor', 'RPE', 'stability'], now(), now()),

('Postpartum Core Rehabilitation Protocol', 'postpartum_rehab', 'protocol', 'Diastasis recti requires staged core rehab. Week 0-2: diaphragmatic breathing and pelvic tilts. Week 3-6: supine heel slides and dead-bug progressions. Week 7-12: plank variants under 10s holds. Criteria to progress: gap <2cm, no doming. Combine with walking 20-30min daily and gradual load return.', 'dr_vita_femina', 2, ARRAY['postpartum', 'diastasis_recti', 'core_rehab', 'walking', 'progression_criteria'], now(), now()),

('Menopause Power & Bone Density Plan', 'menopause_strength', 'application', 'Estrogen decline accelerates bone loss. Heavy resistance training (80-85% 1RM, 3-5 sets x 5 reps) 2x weekly combined with high-impact plyometrics (box jumps, skip rope) 2x weekly improves lumbar spine BMD (+0.4 SMD). Protein 1.6g/kg + calcium 1200mg + vitamin D 2000 IU support adaptation. Track DEXA every 12 months.', 'dr_vita_femina', 2, ARRAY['menopause', 'bone_density', 'heavy_lifting', 'plyometrics', 'protein', 'DEXA'], now(), now()),

('Female Athlete Triad / RED-S Monitoring', 'female_athlete_health', 'screening_tool', 'Relative Energy Deficiency in Sport (RED-S) risk indicators: menstrual dysfunction, low energy availability (<30kcal/kg FFM), BMD Z-score <-1. Protocol: monthly cycle check, weekly energy balance review, annual DEXA. Symptoms trigger diet increase by 300 kcal and training load reduction by 15%.', 'dr_vita_femina', 1, ARRAY['RED-S', 'energy_availability', 'cycle_monitoring', 'BMD', 'training_adjustment'], now(), now()),

('Hormonal Contraception Impact on Performance', 'contraception_performance', 'science', 'Combined oral contraceptives (COCs) can reduce VO2max by 5-10% and increase oxidative stress markers. Progestin-only methods show minor performance impact. Monitor performance trends 3 months post-COC initiation. If decline persists, consider non-hormonal methods. Supplement with antioxidants (vitamin C 500mg, E 200IU) to mitigate oxidative load.', 'dr_vita_femina', 3, ARRAY['contraception', 'performance', 'VO2max', 'oxidative_stress', 'antioxidants'], now(), now()),

('Female-Specific Sleep Optimization Strategies', 'female_sleep', 'protocol', 'Women experience more sleep disturbances around menstruation and menopause. Magnesium bisglycinate 400mg, tart cherry extract 500mg enhance sleep quality. Sleep environment: 18°C optimal. Luteal phase: increase complex carbs at dinner (30-50g) to aid serotonin production. Menopause: cool bedding and evening yoga reduce hot flashes by 50%. Track sleep metrics and adjust.', 'dr_vita_femina', 2, ARRAY['sleep', 'women', 'sleep_disturbance', 'luteal_phase', 'menopause_hot_flashes'], now(), now()),

('Female Gut-Brain Axis: Mood & Microbiome', 'gut_brain_female', 'science', 'The female gut-brain axis is influenced by estrogen levels. Lactobacillus-rich fermented foods increase GABA production, reducing PMS anxiety. Probiotic protocol: Lactobacillus reuteri 108 CFU daily reduces depressive symptoms by 32%. Prebiotic inulin (10g) boosts Bifidobacteria and improves mood. Track mood scores and GI symptoms.', 'dr_vita_femina', 3, ARRAY['gut_brain_axis', 'estrogen', 'Lactobacillus', 'PMS', 'probiotics', 'prebiotics'], now(), now());