-- Deutsche Übersetzungen für weitere Sascha Knowledge Base Einträge (Batch 4/6)

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Strength Periodization: Linear vs Undulating Warfare', 'strength_training_de', 'methodology', 'Zwei bewährte Strategien für Kraftdominanz: Lineare Periodisierung - systematische Progression von hohem Volumen/niedriger Intensität zu niedrigem Volumen/hoher Intensität über 12-16 Wochen. Wellenförmige Periodisierung - häufige Variation in kürzeren Zyklen zur Vermeidung von Adaptations-Stagnation. Beide zeigen identische 0.93 Effektstärke. Wähle basierend auf Psychologie: Linear für disziplinierte Progressoren, Wellenförmig für Variationsuchende.', 'sascha', 2, ARRAY['kraftperiodisierung', 'lineare_periodisierung', 'wellenförmige_periodisierung', 'systematische_progression'], now(), now()),

('Testosteron-optimierte Ernährung für Männer', 'male_nutrition_hormones_de', 'application', 'Spezifische Nährstoffe steigern Testosteronproduktion: Zink (15-30mg/Tag) aus Austern, Rindfleisch; Vitamin D (2000-4000 IU); gesunde Fette 25-30% der Kalorien; Magnesium (400mg) aus Spinat, Nüssen. Vermeiden: Übermäßiger Zucker, Transfette, Alkohol >2 Drinks/Tag. Proteinaufnahme 1.6-2.2g/kg für Muskelerhalt.', 'sascha', 2, ARRAY['testosteron_ernährung', 'zink', 'vitamin_d', 'gesunde_fette', 'protein', 'männer_diät'], now(), now()),

('VO2max – 4x4 Protokoll (Detailliert)', 'performance_monitoring_de', 'gold_standard', '4x4-Test etabliert zur VO2max-Beurteilung. Alle 6 Wochen testen. Fortschritt/Progress regelmäßig messen für optimierte Ausdauerplanung.', 'sascha', 2, ARRAY['vo2max', '4x4', '6_wochen', 'goldstandard'], now(), now()),

('VO2max Testing – 4x4 Protocol', 'performance_monitoring_de', 'testing_protocol', '4x4 Laufen (4min @ 90-95% HRmax, 3min Pause) ist der Standard für VO2max-Messung. Vor/nach jedem Mesozyklus VO2max testen. Nutze 4x4 Protokoll zur Leistungsüberprüfung und Progressionssteuerung.', 'sascha', 2, ARRAY['vo2max', '4x4_protocol', 'testing', 'performance'], now(), now()),

('VO2max: The 4x4 Assault Protocol', 'vo2max_training_de', 'protocol', 'VO2max ist die maximale Kapazität deines Motors - und wir werden sie bis ans Limit pushen. Das 4x4 Protokoll: 4 Minuten bei 85-95% HRmax, 3 Minuten aktive Erholung, 4x wiederholen. Das ist kein sanftes Joggen - das ist systematische kardiovaskuläre Kriegsführung. Studien zeigen 15% VO2max-Verbesserung in 8 Wochen. Tracke Herzfrequenz religiös, triff Zonen präzise, progrediere methodisch.', 'sascha', 2, ARRAY['vo2max', '4x4_protocol', 'kardiovaskulär', 'hochintensiv'], now(), now()),

('20-min Military HIIT Workout', 'hiit_de', 'training_protocol', 'Das 40s:20s-Protokoll steigert VO2max und Kraftausdauer nachweislich in 6 Wochen. Workouts à 20min, Kombination aus Burpees, Push-ups, High Knees, 3x/Woche. Setze bei limitiertem Zeitbudget auf Military HIIT für schnelle Ausdauer- und Kraftzuwächse.', 'sascha', 3, ARRAY['hiit', 'militär', 'vo2max', 'kraftausdauer', 'burpees'], now(), now()),

('20-min Military HIIT Workout (Advanced)', 'hiit_de', 'controlled_study', 'Das 40s:20s HIIT-Protokoll erhöht VO2max und Kraftausdauer binnen 6 Wochen signifikant. Burpees, Push-ups, High Knees, 20-minütige Workouts, 3x/Woche. Empfehle Military HIIT für Zeit- und Wirkungseffizienz.', 'sascha', 3, ARRAY['hiit', 'militär', '40s_20s', 'vo2max', 'rct'], now(), now()),

('ACFT – US Army Combat Fitness Test (Detailliert)', 'tactical_training_de', 'operational_standard', 'Erfolg korreliert mit Kraft, Explosivität, Cardio. 6 Event-Test. Events gezielt über Zyklus trainieren. Trainings-Blöcke an ACFT ausrichten für optimale Vorbereitung.', 'sascha', 3, ARRAY['acft', '6_events', 'us_army', 'combat_fitness'], now(), now()),

('Battle-Tested HIIT Protokoll', 'hiit_de', 'training_protocol', 'Work:Rest Ratio 40s:20s optimiert für VO2max, Kraftausdauer und Fettverlust. Burpees, Mountain Climbers, Jump Squats, Push-up to T, High Knees. Mindestens 3x/Woche, Zyklussteigerung nach 2 Wochen.', 'sascha', 3, ARRAY['40s_20s', 'hiit_protocol', 'battle_tested', 'kraftausdauer'], now(), now()),

('Blockperiodisierung im Militär (Detailliert)', 'periodization_de', 'meta_analysis', 'Blöcke: Kraft, Ausdauer, Technik, Erholung, jew. 4–6 Wochen, reduzieren Verletzungen & Ermüdung. Makro-, Meso-, Mikrozyklen gezielt einsetzen. Blockwechsel nach Zielgruppe und Testing.', 'sascha', 3, ARRAY['blockperiodisierung', 'verletzungsreduktion', 'ermüdung', '4_6_wochen'], now(), now());