-- Insert all men quotes into the database
INSERT INTO public.men_quotes (quote_text, author) VALUES
('Es ist leichter, Liebhaber als Ehemann zu sein, weil es schwerer ist, alle Tage Geist zu haben, als von Zeit zu Zeit eine hübsche Bemerkung zu machen.', 'Honore de Balzac'),
('Oft sind es gut genutzte Mußestunden, in welchen der Mensch das Tor zu einer neuen Welt findet.', 'George M. Adams'),
('Der Körper ist wie ein Auto. Wenn man gut darauf aufpasst, hat man am Ende ein Vintagemodell.', 'Karl Lagerfeld'),
('Gepflegte Männer kommen besser an!', 'Tonsus'),
('Ein Junggeselle ist ein Mann, der nur ein einziges Problem hat - und das ist lösbar.', 'Woody Allen'),
('Der wahre Junggeselle kommt jeden Morgen aus einer anderen Richtung ins Büro.', 'Frank Sinatra'),
('Ändert sich der Zustand der Seele, so ändert dies zugleich auch das Aussehen des Körpers und umgekehrt: ändert sich das Aussehen des Körpers, so ändert dies zugleich auch den Zustand der Seele.', 'Aristoteles'),
('Eleganz heißt nicht ins Auge zu fallen, sondern im Gedächtnis bleiben.', 'Giorgio Armani'),
('Weißt Du, was es bedeutet, nach Hause zu kommen, zu einer Frau, die Dich liebt, die zärtlich zu Dir ist und auch leidenschaftlich? Es bedeutet: du bist in einer fremden Wohnung gelandet!', 'George Burns'),
('Nicht den Tod sollte man fürchten, sondern dass man nie beginnen wird zu leben.', 'Marc Aurel'),
('Sei freundlich zu deinem Leib, damit die Seele Lust hat, darin zu wohnen.', 'Theresia von Avila'),
('Mit der Liebe ist es wie mit dem Bart, pflegt man ihn nicht, sieht man bald dumm aus.', 'Tonsus'),
('Früher rasierte man sich, wenn man Beethoven hören wollte, jetzt hört man Beethoven, wenn man sich rasieren will.', 'Peter Bamm'),
('Mit Zwanzig schenkt einem die Natur sein Gesicht. Mit Dreißig ist das Gesicht vom Leben geformt. Wie Ihr Gesicht jedoch mit fünfzig aussieht, liegt ganz an Ihnen.', 'Coco Chanel'),
('Der Bart als Geschlechtszeichen mitten im Gesicht ist obszön. Deshalb gefällt er den Weibern.', 'Arthur Schopenhauer'),
('Ein Mann ohne Bart ist wie ein Brot ohne Kruste.', 'Lettisches Sprichwort'),
('Mit dem Bart im Gesicht ist es wie mit dem Golfrasen: nur kontinuierliche Pflege und Schur bringen ihn zur Perfektion.', 'Tonsus'),
('Ich bin stolz auf meine Falten, sie sind das Leben in meinem Gesicht.', 'Brigitte Bardot'),
('Die meisten Männer verstehen es überhaupt nicht zu leben, sie nutzen sich nur ab.', 'Charles Bukowski'),
('Es ist ein großer Vorteil, die Fehler, aus denen man lernen kann, recht früh zu machen.', 'Winston Churchill'),
('Schönheit ist mit Geld nicht aufzuwiegen.', 'Paulo Coelho'),
('Ohne Schnurrbart ist ein Mann nicht richtig angezogen.', 'Salvador Dali'),
('Tja, sollen sich die Frauen ruhig nach dem Toilettengang die Hände waschen. Wir Männer haben indes gelernt, uns nicht auf die Hände zu pinkeln.', 'Harald Schmidt'),
('A good lather is half the shave', 'Englisches Sprichwort'),
('A man''s face is his autobiography. A woman''s face is her work of fiction.', 'Oscar Wilde'),
('Menschen, die nach immer größerer Erfüllung jagen, ohne sich jemals Zeit zu gönnen, sie zu genießen, sind wie Hungrige, die immerfort kochen, sich aber nie zu Tische setzen.', 'Marie von Ebner-Eschenbach'),
('Was wir am meisten im Leben bedürfen, ist jemand, der uns dazu bringt, das zu tun, wozu wir fähig sind.', 'Ralph Waldo Emerson'),
('Man entdeckt keine neuen Kontinente, ohne den Mut zu haben, alte Küsten aus den Augen zu verlieren.', 'André Gide'),
('Klassischer materieller Luxus mag nicht mehr ausreichend befriedigen. Die neuen Statussymbole sind Wellness und Gesundheit!', 'GDI-Studie 2008'),
('Als die Scheren erfunden wurden, die sicher nicht aus der ältesten Zeit stammen, was hat man da nicht alles gegen die Ersten gesagt, die sich Nägel und Haare schnitten.', 'Voltaire'),
('Wir müssen uns beständig verändern, erneuern, verjüngern, andernfalls verhärten wir.', 'Johann Wolfgang von Goethe'),
('Man kann nicht immer ein Held sein, aber man kann immer ein Mann sein.', 'Johann Wolfgang von Goethe'),
('Ein Gentleman ist ein Mann, der immer weiß, wie weit er bei einer Frau zu weit gehen darf.', 'Alec Guinness'),
('Ein Gentleman ist ein Mann, der eine unfaire Handlung auch dann bedauert, wenn sie von Erfolg gekrönt war.', 'Sir Harold Wilson'),
('The right man can make you feel comfortable wherever you are, and that''s sexy.', 'Selita Ebanks'),
('Sobald jemand in einer Sache Meister geworden ist, sollte er in einer neuen Sache Schüler werden.', 'Gerhart Hauptmann'),
('Wenn Du an dir nicht Freude hast, die Welt wird dir nicht Freude machen.', 'Paul Heyse'),
('Sei mäßig in allem, atme reine Luft, treibe täglich Hautpflege und Körperübung, halte den Kopf kalt, die Füße warm, und heile ein kleines Weh eher durch Fasten als durch Arznei.', 'Hippokrates von Kos'),
('Ein gut gepflegter Körper und ein gut gepflegtes Gesicht stellen ein wichtiges Statussymbol dar: Man schreibt diesen Personen persönliche Disziplin und Perfektion zu, und dies wiederum ist auch eine Vorbedingung für beruflichen Erfolg.', 'Dr. Helene Karmasin'),
('Jeder Mensch hat die Chance, mindestens einen Teil der Welt zu verbessern, nämlich sich selbst.', 'Paul Anton de Lagarde'),
('Es gibt keinen Luxus ohne Parfum.', 'Karl Lagerfeld'),
('Willst du wertvolle Dinge sehen, so brauchst du nur dorthin zu blicken, wohin die große Menge nicht sieht.', 'Laotse'),
('Stil ist wichtiger als Modetrends.', 'Yves Saint Laurent'),
('Gutes Aussehen und positive Gefühle gehören zusammen.', 'Alexander Lowen'),
('Was das Auge freut, erfrischt den Geist, und was den Geist erfrischt, erfrischt den Körper.', 'Prentice Mulford'),
('Das Faszinierende am Leben ist: Wenn man darauf besteht, nur das Beste zu bekommen, dann bekommt man es häufig auch.', 'William Somerset Maugham'),
('Wir brauchen nicht so fortzuleben, wie wir gestern gelebt haben. Macht euch nur von dieser Anschauung los, und tausend Möglichkeiten laden uns zu neuem Leben ein.', 'Christian Morgenstern'),
('Man sollte sich nicht scheuen, seine Ansichten zu ändern. Schließlich trägt man ein Hemd auch nicht jahrzehntelang.', 'John Osborne'),
('Stoppeln am Kinn sind gemein, so zeige dich immer gut rasiert.', 'Ovid'),
('Ich finde Bärte wunderschön; man sieht so wenig von den Gesichtern.', 'Anna Magnani'),
('Um Erfolg zu haben, muss man aussehen, als habe man Erfolg.', 'Valentin Polcuch'),
('Wer aufhört, besser zu werden, hat aufgehört, gut zu sein.', 'Philip Rosenthal'),
('Erfolg im Leben ist etwas Sein, etwas Schein und sehr viel Schwein.', 'Philip Rosenthal'),
('Der Geschmack ist die Kunst, sich auf Kleinigkeiten zu verstehen.', 'Jean-Jacques Rousseau'),
('Wenn man auf seinen Körper achtet, geht''s auch dem Kopf besser.', 'Jil Sander'),
('Schönheit ist ein offener Empfehlungsbrief, der die Herzen im Voraus für uns gewinnt.', 'Arthur Schopenhauer'),
('Weise Lebensführung gelingt keinem Menschen durch Zufall. Man muss, solange man lebt, lernen, wie man leben soll.', 'Seneca'),
('Sorge dafür, das zu haben, was du liebst, oder du wirst gezwungen werden, das zu lieben, was du hast.', 'George Bernard Shaw'),
('Die Kunst des Ausruhens ist Teil der Kunst des Arbeitens.', 'John Steinbeck'),
('Wir verbringen einen großen Teil des Lebens damit, die Achtung anderer zu erwerben. Aber Selbstachtung zu gewinnen, darauf verwenden wir wenig Zeit.', 'Josef von Sternberg'),
('A gentleman will walk but never run.', 'Sting'),
('Ein Gentleman ist ein Mann, der seinem Mädchen die Antibabypillen bezahlt.', 'Dan Carter'),
('Ein Gentleman vergisst dein Alter, aber nie deinen Geburtstag.', 'Clark Gable'),
('Was ein Mann schöner ist als ein Aff'', ist ein Luxus.', 'Tante Jolesch'),
('Die Frauen haben es ja von Zeit zu Zeit auch nicht leicht. Wir Männer aber müssen uns rasieren.', 'Kurt Tucholsky'),
('Menschen mit einer neuen Idee gelten so lange als Spinner, bis sich die Sache durchgesetzt hat.', 'Mark Twain'),
('Jeder Mann braucht fünf Ehefrauen: einen Filmstar, ein Dienstmädchen, eine Köchin, eine Zuhörerin und eine Krankenschwester.', 'Mark Twain'),
('Keine Frau ist so schlecht, dass sie nicht die bessere Hälfte eines Mannes werden kann.', 'Heinz Erhardt'),
('Ein Mann ohne Eitelkeit ist kein Mann.', 'John Wayne'),
('Ich habe einen ganz einfachen Geschmack, ich bin immer mit dem Besten zufrieden.', 'Oscar Wilde'),
('Der Kultivierte bedauert nie einen Genuss. Der Unkultivierte weiß überhaupt nicht, was ein Genuss ist.', 'Oscar Wilde'),
('Wer einmal sich selbst gefunden hat, der kann nichts auf dieser Welt mehr verlieren.', 'Stefan Zweig'),
('Try not to become a man of success but rather try to become a man of value.', 'Albert Einstein'),
('A man cannot be comfortable without his own approval.', 'Mark Twain'),
('Better keep yourself clean and bright; you are the window through which you must see the world.', 'George Bernard Shaw'),
('Every man over forty is responsible for his face.', 'Abraham Lincoln'),
('Ein Mann ist alt, wenn er seine Komplimente nicht mehr in die Tat umsetzen kann.', 'Charles Boyer'),
('A man has to do what a man has to do.', 'Sprichwort'),
('Der Mann muss der Frau den Auspuff schweißen können.', 'Gunter Gabriel'),
('Für einen Mann zählt das Erreichte, einer Frau reicht das Erzählte.', 'Karl Kraus'),
('Es gibt Frauen, mit denen man nur in einen Nachtclub gehen kann. Alle anderen Lokale sind längst geschlossen, wenn sie mit dem Anziehen fertig sind.', NULL),
('Mit den Frauen ist es, ich hoffe, ihr wisst es, wie mit den Äpfeln rings an den Ästen. Die schönsten schmecken nicht immer am besten.', 'Erich Kästner'),
('Glück ist ein Parfüm, das du nicht auf andere sprühen kannst, ohne selbst ein paar Tropfen abzubekommen.', 'Ralph Waldo Emerson'),
('Wenn es dir gelingt, die innere Ruhe zu erobern, so hast du mehr getan als derjenige, der Städte und ganze Reiche erobert hat.', 'Michel de Montaigne'),
('Nicht der Wind, sondern die Segel bestimmen den Kurs.', NULL),
('Qualität ist niemals Zufall; sie ist immer das Ergebnis hoher Ziele, aufrichtiger Bemühung, intelligenter Vorgehensweise und geschickter Ausführung.', 'Will A. Foster'),
('Die größten Ereignisse sind nicht unsere lautesten, sondern unsere stillsten Stunden.', 'Friedrich Wilhelm Nietzsche'),
('Die Muße scheint Lust, wahres Glück und seliges Leben in sich selbst zu tragen.', 'Aristoteles'),
('Menschen, die die Muße und Ruhe nicht mehr kennen, führen auch im größten Reichtum ein armes Leben.', NULL),
('Das Dasein ist köstlich, man muss nur den Mut haben, sein eigenes Leben zu führen.', 'Giacomo Casanova'),
('Muße ist das Kunststück, sich selbst ein angenehmer Gesellschafter zu sein.', 'Karl Heinrich Waggerl'),
('Ein Mann darf viele Fehler machen. Das spielt keine Rolle. Wenn die Fehler aber zu groß sind und auf seinem Leben lasten, bleibt ihm nur noch, sich nicht ernst zu nehmen.', 'Pedro Juan Gutiérrez'),
('Der Traum der Männer wäre es, den Frauen in die Arme zu sinken, ohne ihnen gleichzeitig in die Hände fallen zu müssen.', 'Jerry Lewis'),
('Die Frau gleicht einer Krawatte: Ob sie passt, weiß Mann erst, wenn er sie am Hals hat.', 'Helmut Kohl'),
('Wenn eine Freundin zu teuer wird, muss man sie heiraten.', 'Peter Sellers'),
('Der eine hat ein trautes Heim, der andere traut sich nicht mehr heim.', 'Graf Fito'),
('Die Männer regieren die Welt und die Frauen ihre Männer. Was wollen sie noch mehr?', 'Bogumil Goltz'),
('Wenn ein Mann einer Frau die Autotür aufhält, ist entweder das Auto neu oder die Frau.', 'Henry Ford'),
('Frauen mögen stille Männer. Sie glauben, dass sie zuhören.', NULL),
('Wenn Männer auseinandergehn, so sagen sie auf Wiedersehn. Wenn Weiber auseinandergehn, so bleiben sie noch lange stehn.', 'Schlesisches Sprichwort'),
('Kluge Männer machen sich immer ein Verdienst aus ihren Handlungen, auch wenn allein die Notwendigkeit sie dazu zwingt.', 'Niccolò Machiavelli'),
('Frauen sind erstaunt, was Männer alles vergessen. Männer sind erstaunt, woran Frauen sich erinnern.', 'Peter Bamm'),
('Was wir Männer euch Frauen voraus haben? Wir fragen niemals: Warum hast du nicht angerufen?', 'George Clooney'),
('Ein Mann ist, wer Rückgrat hat und nicht nur gestärkte Hemden trägt. Manchmal glaube ich, dass echte Männer eine aussterbende Spezies sind.', 'Bruce Willis'),
('Es ist viel leichter, für eine geliebte Frau zu sterben, als mit ihr zu leben.', 'Lord Byron'),
('Wenn ein Mann will, dass ihn seine Frau schweigend zuhört, muss er im Schlaf sprechen.', NULL),
('Am liebsten erinnern sich die Frauen an die Männer, mit denen sie lachen konnten.', 'Anton Tschechow'),
('Wenn Männer von ihrem geraden Weg abweichen, sind meistens weibliche Kurven die Ursache.', NULL),
('Männer wollen immer nur das Eine – Frauen immer nur das Andere.', 'Peter Silie'),
('Die strengsten Richter eines Mannes sind seine Kinder.', 'Thornton Wilder'),
('Junggesellen sind Männer, die wissen, wie klein die Chance ist, dass man in einer Auster eine Perle findet.', NULL),
('Viele Männer vergessen in der Liebe das Dessert. Das ist schade, denn die meisten Frauen sind naschsüchtig.', 'Mariella Pozzo'),
('Charme ist der unsichtbare Teil der Schönheit, ohne den niemand wirklich schön sein kann.', 'Sophia Loren'),
('Charme ist ein Mittel, ein JA zu erhalten, ohne präzise eine Frage danach gestellt zu haben.', 'Albert Camus'),
('Seife und Bildung wirken nicht so prompt wie ein Massaker, auf lange Sicht aber viel verheerender.', 'Mark Twain'),
('Gewinner werden nicht geboren, sondern gemacht – und zwar hauptsächlich von sich selbst.', NULL),
('Versuche zu kriegen, was Du liebst, sonst bist Du gezwungen, das zu lieben, was Du kriegst.', NULL),
('Alles Behaartsein ist tierisch. Die Rasur ist das Abzeichen höherer Zivilisation.', 'Arthur Schopenhauer'),
('Ein kluger Mann macht nicht alle Fehler selbst. Er gibt auch anderen eine Chance.', 'Winston Churchill'),
('Jeder Mann von Stil und Niveau ist ein Hypochonder.', 'Molière'),
('Die einzigen Männer, die eine Frau zu durchschauen vermögen, sind die Röntgenologen.', 'Sacha Guitry'),
('Niemand ist den Frauen gegenüber aggressiver oder herablassender als ein Mann, der seiner Männlichkeit nicht ganz sicher ist.', 'Simone de Beauvoir'),
('Alle Männer sind eitel – vor allem jene, die es nicht zugeben.', 'Sean Connery'),
('Altern ist eine schlechte Gewohnheit, die ein beschäftigter Mann gar nicht erst aufkommen lässt.', 'André Maurois'),
('Bei zwei Sachen wird ein Mann nie zugeben, dass er sie nicht gut kann: Sex und Autofahren.', 'Stirling Moss'),
('Der ganze Emanzipationsrummel hat nichts daran geändert, dass Frauen sich schön machen, um Männern zu gefallen.', 'Marcello Mastroianni');