-- Insert Lucy's comprehensive knowledge base for 80/20+ Nutrition, Lifestyle Medicine & Metabolism

-- Insert scientific papers related to Lucy's expertise
INSERT INTO public.scientific_papers (doi, title, authors, abstract, journal, publication_year, keywords, key_findings, practical_applications, coach_relevance) VALUES
('10.1016/j.clnu.2019.05.012', 'Chrononutrition: Circadian Rhythms and Food Intake Timing Effects on Metabolism', ARRAY['Almoosawi S.', 'Vingeliene S.', 'Karagounis L.G.', 'Pot G.K.'], 'Comprehensive review examining how meal timing affects circadian rhythms, glucose tolerance, and metabolic health outcomes across different populations.', 'Clinical Nutrition', 2019, ARRAY['chrononutrition', 'circadian rhythm', 'meal timing', 'glucose tolerance'], ARRAY['Early eating improves glucose tolerance by 25%', '5-hour meal delay shifts glucose rhythm by 5.7 hours', 'Regular meal timing stabilizes peripheral clocks'], ARRAY['Optimal meal timing strategies', 'Circadian-based nutrition planning', 'Metabolic optimization protocols'], '{"lucy": 5, "kai": 3, "sascha": 2}'),

('10.3389/fnut.2021.676992', 'Mediterranean Diet and Inflammatory Markers: Systematic Review and Meta-Analysis', ARRAY['Schwingshackl L.', 'Lampousi A.M.', 'Portillo M.P.', 'Romaguera D.'], 'Meta-analysis of Mediterranean diet effects on inflammatory biomarkers including CRP, IL-6, and TNF-α across multiple populations and intervention studies.', 'Frontiers in Nutrition', 2021, ARRAY['mediterranean diet', 'inflammation', 'CRP', 'IL-6'], ARRAY['High adherence reduces CRP by 20%, IL-6 by 17%', 'Anti-inflammatory effects consistent across populations', 'Polyphenols and omega-3s drive primary mechanisms'], ARRAY['Anti-inflammatory meal planning', 'Mediterranean diet implementation', 'Biomarker-guided nutrition therapy'], '{"lucy": 5, "sascha": 2, "kai": 3}'),

('10.1016/j.metabol.2020.154170', 'Intermittent Fasting and Metabolic Flexibility: Mechanisms and Clinical Applications', ARRAY['Mattson M.P.', 'Longo V.D.', 'Harvie M.'], 'Comprehensive analysis of intermittent fasting effects on metabolic switch, insulin sensitivity, and adaptive thermogenesis with clinical intervention protocols.', 'Metabolism', 2020, ARRAY['intermittent fasting', 'metabolic switch', 'insulin sensitivity', 'thermogenesis'], ARRAY['Metabolic switch occurs after 12-18h fasting', 'IF improves insulin sensitivity by 25-40%', 'Activates AMPK, sirtuins, and autophagy pathways'], ARRAY['IF protocol design and implementation', 'Metabolic flexibility training', 'Therapeutic fasting applications'], '{"lucy": 5, "kai": 4, "sascha": 3}'),

('10.1080/07315724.2018.1552544', 'Omega-3 Fatty Acids and Metabolic Health: Anti-inflammatory Mechanisms and Thermogenic Effects', ARRAY['Calder P.C.', 'Bosco N.', 'Bourdet-Sicard R.', 'Capuron L.'], 'Analysis of omega-3 PUFA effects on inflammation resolution, brown adipose tissue activation, and metabolic rate enhancement through UCP1 expression.', 'Journal of the American College of Nutrition', 2019, ARRAY['omega-3', 'thermogenesis', 'brown fat', 'inflammation'], ARRAY['2g EPA+DHA daily activates brown fat', 'Inhibits NLRP3 inflammasome, reduces IL-1β', 'Increases energy expenditure by 5-10%'], ARRAY['Omega-3 supplementation protocols', 'Anti-inflammatory nutrition strategies', 'Thermogenic diet optimization'], '{"lucy": 5, "sascha": 4, "kai": 2}'),

('10.1210/clinem/dgaa204', 'Nutrition and Hormonal Balance: Impact on Insulin, Leptin, and Sex Hormones', ARRAY['Barrea L.', 'Savastano S.', 'Di Somma C.', 'Colao A.'], 'Systematic review of nutritional interventions on hormonal balance, examining effects of macronutrient composition, meal timing, and specific nutrients on endocrine function.', 'Journal of Clinical Endocrinology & Metabolism', 2020, ARRAY['nutrition', 'hormones', 'insulin', 'leptin', 'estrogen'], ARRAY['Mediterranean diet improves β-cell sensitivity within 4 weeks', 'High fiber (≥30g) increases fecal estrogen excretion 3-fold', 'Low-GI diets reduce leptin and improve satiety'], ARRAY['Hormone-balancing nutrition protocols', 'Macronutrient timing for endocrine health', 'Therapeutic nutrition for hormonal disorders'], '{"lucy": 5, "kai": 3, "sascha": 2}');

-- Insert Lucy's comprehensive knowledge base entries
INSERT INTO public.coach_knowledge_base (coach_id, knowledge_type, title, content, expertise_area, priority_level, tags) VALUES

-- Priority 1: Core Philosophy and Principles
('lucy', 'philosophy', 'The 80/20+ Lifestyle Medicine Approach', 'Sustainable transformation happens when 80% of your results come from smart nutrition choices, while 20% comes from strategic movement and recovery. This isn''t about perfection - it''s about precision where it matters most. Your metabolism responds to consistency in meal timing, nutrient quality, and caloric balance far more than extreme restrictions. We''re building a lifestyle that works with your circadian biology, hormonal rhythms, and real-world constraints. Evidence-based nutrition meets practical implementation for lasting change.', 'lifestyle_medicine', 1, ARRAY['80_20_principle', 'lifestyle_medicine', 'sustainable_nutrition', 'evidence_based']),

('lucy', 'methodology', 'Chrono-Nutrition: Eating in Sync with Your Biology', 'Your body has an internal clock that controls everything from insulin sensitivity to fat oxidation. Early eating windows (before 2 PM for main carbohydrates) improve glucose tolerance by 25% compared to late eating. The metabolic switch from glucose to ketones happens after 12-18 hours of fasting, activating powerful cellular repair mechanisms. We''re not just counting calories - we''re optimizing when and how your body processes them. Timing is the secret weapon that amplifies every nutritional choice you make.', 'chrono_nutrition', 1, ARRAY['chrono_nutrition', 'meal_timing', 'metabolic_switch', 'circadian_biology']),

-- Priority 2: Core Training Methodologies
('lucy', 'protocol', 'Intermittent Fasting: The Metabolic Reset Tool', 'Intermittent fasting isn''t starvation - it''s strategic metabolic flexibility training. The 16:8 protocol (eating 12-8 PM or 8 AM-4 PM) activates AMPK pathways, increases insulin sensitivity by 25-40%, and triggers cellular autophagy. Early time-restricted eating shows superior results for glucose control and fat oxidation. This isn''t about willpower; it''s about working with your body''s natural rhythms to enhance fat burning, reduce inflammation, and improve mental clarity. Your eating window becomes your metabolic optimization window.', 'intermittent_fasting', 2, ARRAY['intermittent_fasting', '16_8_protocol', 'metabolic_flexibility', 'autophagy']),

('lucy', 'protocol', 'Anti-Inflammatory Nutrition: Fighting Fire with Food', 'Chronic inflammation is the silent saboteur of your metabolism and health goals. Mediterranean dietary patterns reduce CRP by 20% and IL-6 by 17% through polyphenol-rich foods and omega-3 fatty acids. The magic numbers: 2g EPA+DHA daily, 800mg polyphenols, and 30g+ fiber. We''re not just eating - we''re actively reducing inflammatory fire in your body. Every colorful plant food is medicine, every healthy fat is healing, every anti-inflammatory choice moves you closer to optimal metabolic function.', 'anti_inflammatory_nutrition', 2, ARRAY['anti_inflammatory', 'mediterranean_diet', 'polyphenols', 'omega_3']),

('lucy', 'protocol', 'Hormonal Balance Through Strategic Nutrition', 'Your hormones are the master controllers of your metabolism, and nutrition is their programming language. Protein distribution (30/30/40% across meals) stabilizes insulin and GLP-1. High-fiber intake (≥30g daily) increases fecal estrogen excretion 3-fold, supporting hormonal balance. Low-GI foods reduce leptin resistance and improve satiety signals. We''re not fighting your hormones - we''re giving them the nutrients they need to work optimally for fat loss, energy, and wellbeing.', 'hormonal_nutrition', 2, ARRAY['hormonal_balance', 'insulin_optimization', 'leptin_sensitivity', 'protein_distribution']),

-- Priority 3: Specific Protocols and Techniques
('lucy', 'protocol', 'Nutrient Timing: The Performance Edge', 'When you eat is as important as what you eat. Pre-workout: 0.3g protein/kg + 1g carbs/kg 1-2 hours before training maximizes performance. Post-workout: 0.3g protein/kg + 0.8g carbs/kg within 2 hours optimizes recovery and muscle protein synthesis. The "anabolic window" stays open with protein every 3-4 hours (20-40g doses). Morning carbs, evening proteins: this simple rule aligns with your natural insulin sensitivity patterns for optimal body composition.', 'nutrient_timing', 3, ARRAY['nutrient_timing', 'pre_workout_nutrition', 'post_workout_nutrition', 'protein_timing']),

('lucy', 'protocol', 'Metabolic Flexibility: Training Your Fat-Burning Engine', 'Metabolic flexibility is your body''s ability to efficiently switch between burning carbs and fats based on availability. Periodic carb cycling (2-3 low-carb days followed by 1 higher-carb day) trains this flexibility. Omega-3 fatty acids (2g EPA+DHA) activate brown fat and increase energy expenditure by 5-10%. Fasting windows create metabolic stress that strengthens your fat-oxidation pathways. We''re building a metabolic engine that runs efficiently on whatever fuel is available.', 'metabolic_flexibility', 3, ARRAY['metabolic_flexibility', 'carb_cycling', 'fat_oxidation', 'brown_fat_activation']),

('lucy', 'protocol', 'The Three-Color Rule: Polyphenol Power', 'Every meal should contain at least three different colored plant foods to maximize polyphenol diversity and anti-inflammatory benefits. Red (berries, tomatoes), orange (carrots, sweet potatoes), green (leafy vegetables, broccoli), purple (eggplant, red cabbage), white (onions, garlic). Each color provides unique compounds that work synergistically to reduce inflammation, support detoxification, and optimize cellular function. This isn''t just about vitamins - it''s about accessing nature''s pharmacy through food variety.', 'polyphenol_optimization', 3, ARRAY['three_color_rule', 'polyphenol_diversity', 'plant_variety', 'phytonutrients']),

-- Priority 4: Advanced Applications
('lucy', 'application', 'Plateau-Breaking Protocol: Metabolic Adaptation Strategies', 'When weight loss stalls, it''s not willpower failure - it''s metabolic adaptation. Adaptive thermogenese can reduce metabolic rate by 10-25%. Combat strategies: structured refeeds (1-2 higher-carb days weekly), protein cycling (varying intake 1.2-2.0g/kg), omega-3 loading (3g daily during plateaus), and strategic diet breaks (1-2 weeks at maintenance every 6-8 weeks). We''re staying one step ahead of your body''s survival mechanisms through strategic metabolic variation.', 'plateau_breaking', 4, ARRAY['metabolic_adaptation', 'refeed_days', 'diet_breaks', 'adaptive_thermogenesis']),

('lucy', 'application', 'Hormone Optimization Through Micronutrient Precision', 'Hormonal balance requires specific micronutrient cofactors. Thyroid function: 55-200μg selenium daily (2 Brazil nuts), 150μg iodine, adequate iron (>15mg). Insulin sensitivity: 200-400μg chromium, 15-30mg zinc, 400mg magnesium. Estrogen metabolism: B-complex vitamins, especially B6 (50-100mg), plus cruciferous vegetables for DIM and I3C. Cortisol regulation: 200mg L-theanine before meditation, adequate vitamin C (500-1000mg). We''re providing the precise nutrients your endocrine system needs for optimal function.', 'micronutrient_optimization', 4, ARRAY['micronutrients', 'thyroid_support', 'insulin_cofactors', 'estrogen_metabolism']),

-- Priority 5: Supplementary Knowledge
('lucy', 'science', 'The Science of Caloric Deficit: Beyond CICO', 'While caloric deficit remains fundamental for fat loss, the "calories in, calories out" model oversimplifies metabolic reality. Protein has a thermic effect of 20-30% vs 0-5% for fats and carbs. Fiber-rich foods require more energy for digestion and absorption. Meal timing affects metabolic rate - early eating increases diet-induced thermogenesis. Ultra-processed foods reduce energy expenditure compared to whole foods with identical caloric content. We''re optimizing both sides of the energy equation through strategic food choices and timing.', 'caloric_science', 5, ARRAY['caloric_deficit', 'thermic_effect', 'diet_induced_thermogenesis', 'food_processing']),

('lucy', 'lifestyle', 'Stress, Sleep, and Metabolic Health Integration', 'Chronic stress elevates cortisol, promoting abdominal fat storage and insulin resistance. Poor sleep disrupts leptin and ghrelin, increasing appetite by 20-25%. The solution integrates nutrition with lifestyle: magnesium (400mg) and tart cherry juice for sleep quality, adaptogenic herbs (ashwagandha 300-600mg) for stress resilience, and strategic meal timing to support circadian rhythms. We''re addressing the hidden metabolic disruptors that sabotage even perfect nutrition plans through comprehensive lifestyle medicine.', 'stress_sleep_metabolism', 5, ARRAY['stress_management', 'sleep_optimization', 'cortisol_regulation', 'lifestyle_integration']);

-- Update Lucy's specialization with enhanced description
UPDATE public.coach_specializations 
SET specialization_description = 'Die 80/20+ Lifestyle-Medizin Expertin kombiniert evidenzbasierte Ernährungswissenschaft mit praktischer Anwendbarkeit für nachhaltigen Lebensstil-Wandel. Spezialisiert auf Chrono-Nutrition, anti-inflammatorische Ernährung, hormonelle Balance und metabolische Flexibilität. Jede Empfehlung basiert auf dem Prinzip: 80% Ernährung, 20% Bewegung und Regeneration für optimale Ergebnisse.',
    core_philosophy = '80% deiner Ergebnisse kommen von intelligenten Ernährungsentscheidungen. Wir arbeiten mit deiner Biologie, nicht gegen sie. Meal-Timing, Nährstoffqualität und hormonelle Balance sind die Säulen nachhaltiger Transformation.',
    expertise_areas = ARRAY['Chrono-Nutrition und Meal-Timing', 'Anti-inflammatorische Ernährung', 'Hormonelle Balance durch Nutrition', 'Intermittierendes Fasten und Metabolische Flexibilität', 'Kaloriendefizit-Optimierung', 'Lifestyle-Medizin Integration'],
    knowledge_focus = ARRAY['16:8 Intermittent Fasting', 'Mediterranes Ernährungsmuster', '3-Farben-Regel für Polyphenole', 'Protein-Timing 30/30/40', 'Omega-6/Omega-3 Ratio 4:1', 'Metabolic Switch Mechanismus'],
    methodology = 'Evidenzbasierte Chrono-Nutrition mit praktischer Umsetzbarkeit. Anti-inflammatorische Strategien, hormonoptimierte Makroverteilung und metabolische Flexibilitäts-Training für nachhaltigen Lifestyle-Wandel ohne Verzicht.'
WHERE coach_id = 'lucy';