-- Deutsche Übersetzungen für weitere Sascha Knowledge Base Einträge (Batch 1/6)

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('HIIT für Testosteron und Wachstumshormon Boost', 'male_hormone_optimization_de', 'protocol', 'High-Intensity Interval Training stimuliert Testosteron und Wachstumshormon synergistisch. Das 4×4-Protokoll zeigt 17% Testosteronerhöhung und 18-fachen GH-Anstieg bei Männern 55+. Protokoll: 4min @ 85-95% HRmax, 3min aktive Erholung, 2x/Woche. Kombination HIIT + Krafttraining ist isoliertem Training überlegen.', 'sascha', 1, ARRAY['hiit', 'testosteron', 'wachstumshormon', 'intervalltraining', 'hormonelle_reaktion'], now(), now()),

('Makro-, Meso-, Mikrozyklen (Detailliert)', 'periodization_de', 'theoretical_review', 'Hierarchie: Makro >3 Monate, Meso 4–8 Wochen, Mikro 1 Woche. Periodisierte Steuerung aller Variablen. Langfristige Ziele mit periodisierten Blöcken kombinieren für optimale Anpassung und Verletzungsprävention.', 'sascha', 1, ARRAY['makro', 'meso', 'mikro', 'hierarchie', '3_monate'], now(), now()),

('Militärische Effizienz', 'training_de', 'core_principle', 'Saschas Ansatz basiert auf militärischer Disziplin: Maximale Ergebnisse in minimaler Zeit durch strukturierte, hochintensive Trainingseinheiten. Keine Zeitverschwendung, nur bewährte, wissenschaftlich fundierte Methoden für Elitesoldaten und Zivilisten.', 'sascha', 1, ARRAY['militärtraining', 'effizienz', 'hiit'], now(), now()),

('Militärische Disziplin trifft wissenschaftliche Präzision', 'performance_optimization_de', 'philosophy', 'Leistungsoptimierung erfordert die Verbindung von militärischer Disziplin mit evidenzbasierter Trainingswissenschaft. Jede Wiederholung, jeder Satz, jedes Workout muss einem strategischen Zweck dienen. Wir trainieren nicht um des Trainierens willen - wir trainieren um zu dominieren. Hochintensive Protokolle, systematische Periodisierung und erbarmungslose Verfolgung messbarer Verbesserungen definieren den Performance Optimizer Ansatz.', 'sascha', 1, ARRAY['militärdisziplin', 'evidenzbasiert', 'hochintensiv', 'systematischer_ansatz'], now(), now()),

('Periodisierung: Das strategische Fundament', 'periodization_de', 'methodology', 'Periodisierung ist Kriegsführung gegen Adaptation. Dein Körper versucht ständig Homöostase zu bewahren - unser Job ist es, diese Komfortzone systematisch zu stören. Meta-Analysen zeigen 0.93 Effektstärke für periodisierte vs. nicht-periodisierte Training. Sowohl lineare als auch wellenförmige Modelle funktionieren gleich gut (p=0.97), aber der Schlüssel ist strategische Variation alle 3-10 Wochen.', 'sascha', 1, ARRAY['periodisierung', 'adaptation', 'systematisches_training', 'evidenzbasiert'], now(), now()),

('UCM-Hypothese zur Bewegungsqualität', 'biomechanics_de', 'theoretical_review', 'Variabilität = motorische Qualität, nicht Defizit. Individualisierte Trainingssteuerung. UCM-Screening zur Feinevaluation einsetzen für präzise Bewegungsanalyse und Leistungsoptimierung.', 'sascha', 1, ARRAY['ucm', 'variabilität', 'motorik', 'individualisierung'], now(), now()),

('Uncontrolled Manifold (UCM) Hypothese', 'biomechanics_de', 'theoretical_review', 'UCM erlaubt differenzierte Erfassung individueller Bewegungsqualität und frühzeitige Diagnose von Defiziten. UCM-basiertes Screening bei komplexen Bewegungen und Rehabilitation. Für Athleten, die Bewegungsqualität gezielt verbessern wollen.', 'sascha', 1, ARRAY['ucm', 'bewegungsqualität', 'screening', 'rehabilitation'], now(), now()),

('Active Recovery & Schlaf', 'recovery_de', 'controlled_study', 'Aktive Regeneration (z.B. Mobility, leichtes Cardio) steigert Resilienz und mindert Verletzungen. Deload nach 3–4 Wochen Intensivtraining, Schlafmonitoring >7h/Tag. Plane regelmäßige Erholungs- und Mobility-Tage (Active Rest) für optimale Anpassung.', 'sascha', 2, ARRAY['active_recovery', 'schlaf', 'regeneration', 'deload'], now(), now()),

('Active Rest und Schlaf', 'recovery_de', 'controlled_study', 'Deloads & Schlaf erhöhen Leistungsfähigkeit, senken Verletzungsrisiko. Alle 3–4 Wochen Deload, >7h Schlaf pro Nacht. Regelmäßige Regeneration einbauen für nachhaltigen Leistungsaufbau.', 'sascha', 2, ARRAY['active_rest', 'deload', '7h_schlaf', '3_4_wochen'], now(), now()),

('Afterburn Effekt (EPOC) bei HIIT', 'hiit_de', 'scientific_research', 'Bis zu 15% Gesamtumsatzsteigerung durch EPOC nach intensiven HIIT-Einheiten. Workouts mit komplexen Mehrgelenksübungen, Intensität ≥90% 1RM. Empfehle HIIT für maximale Nachbrenn-Effekte und Fettverbrennung über 48 Stunden.', 'sascha', 2, ARRAY['hiit', 'epoc', 'fettverbrennung', 'nachbrennen'], now(), now());