-- Insert cycle training knowledge for Dr. Vita Femina
INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at) VALUES
('Menstruationszyklus-basierte Periodisierung: IMPACT-Studie Erkenntnisse', 'cycle_based_training', 'research_finding', 'Die randomisierte IMPACT-Studie (n=120) untersuchte follikuläre vs. luteale Trainingsperiodisierung bei trainierten Frauen. Primärhypothese: Follikuläres Training ist überlegen bei aeroben Leistungsverbesserungen und Muskelkraft aufgrund höherer Östrogenspiegel.', 'dr_vita_femina', 5, ARRAY['menstrual_cycle_periodization','aerobic_performance','strength_training'], '2025-07-28T14:30:00+02:00'),

('Östrogen/Progesteron-Verhältnis als Leistungsindikator', 'hormonal_performance_correlation', 'science', 'Endurance-Performance variiert nur bei hohem E/P-Ratio (Östrogen/Progesteron pmol/nmol) in der mittleren Lutealpahse vs. früher Follikelphase. Späte Follikelphase mit prä-ovulatorischem Östrogensurge zeigt optimale Cycling-Time-Trial-Performance.', 'dr_vita_femina', 5, ARRAY['estrogen_progesterone_ratio','endurance_performance','cycling_performance'], '2025-07-28T14:31:00+02:00'),

('Wahrgenommene vs. objektive Leistungsveränderungen', 'perceived_vs_actual_performance', 'research_finding', '50-71% der Athletinnen berichten Leistungseinbußen in bestimmten Zyklusphasen, besonders frühe Follikel- und späte Lutealphase. Objektive Messungen zeigen jedoch oft triviale Effekte (Effect Size <0.2). Meta-Analyse: nur geringfügig reduzierte Performance in früher Follikelphase.', 'dr_vita_femina', 4, ARRAY['perceived_performance','objective_performance','meta_analysis'], '2025-07-28T14:32:00+02:00'),

('Cycle Syncing Kontroverse: McMaster Universität Befunde', 'cycle_syncing_research', 'research_finding', 'McMaster-Studie (n=12) zeigt: Zyklusphasen-spezifisches Training hat KEINEN Einfluss auf Muskelproteinsynthese. Follicular vs. luteal phase resistance training zeigte identische Muskelprotein-Produktionsraten. "Cycle Syncing für Muskelaufbau ist wissenschaftlich nicht belegt."', 'dr_vita_femina', 5, ARRAY['cycle_syncing','muscle_protein_synthesis','resistance_training'], '2025-07-28T14:33:00+02:00'),

('Follikelphase: Optimales Krafttraining-Fenster', 'follicular_phase_training', 'application', 'Follikelphase (Tage 1-14): Ansteigende Östrogenspiegel fördern Muskelkraft-Gewinne. Studien zeigen 33% höhere Fmax-Steigerungen bei follikulärem vs. lutealem Krafttraining. Optimal für Progressive Overload, PR-Versuche und Hypertrophie-Training.', 'dr_vita_femina', 4, ARRAY['follicular_phase','strength_training','progressive_overload'], '2025-07-28T14:34:00+02:00'),

('Ovulationsphase: Peak Performance und Testosteron-Boost', 'ovulation_phase_training', 'application', 'Ovulation (Tage 14-16): Testosteron-Peak führt zu maximaler Kraft und Energy. Optimal für HIIT, Kraftmaxima, Power-Training. Jedoch erhöhtes ACL-Verletzungsrisiko durch Östrogen-induzierte Ligament-Laxität. "Unstoppable"-Mentalität nutzen, aber auf Gelenke achten.', 'dr_vita_femina', 4, ARRAY['ovulation_phase','testosterone_peak','ACL_injury_risk'], '2025-07-28T14:35:00+02:00'),

('Lutealphase: Progesteron-Effekte und Trainingsanpassung', 'luteal_phase_training', 'application', 'Lutealphase (Tage 15-28): Erhöhtes Progesteron führt zu thermogenen Effekten (+0.5°C Körpertemperatur), erhöhter Atemfrequenz und perceived exertion. Empfehlung: Volumen-Reduktion (-20%), Fokus auf Technik, mehr Regeneration, Mobility-Work.', 'dr_vita_femina', 4, ARRAY['luteal_phase','progesterone_effects','volume_reduction'], '2025-07-28T14:36:00+02:00'),

('Menstruationsphase: Low-Impact Training Benefits', 'menstrual_phase_training', 'application', 'Menstruation (Tage 1-5): Niedrige Östrogen/Progesteron-Spiegel, aber paradoxerweise erhöhte Schmerztoleranz und schnellere Muskelregeneration. Empfehlung: Gentle Movement (Yoga, Walking), leichtes Krafttraining ab Tag 3-4. Exercise reduziert Dysmenorrhoe um 25%.', 'dr_vita_femina', 4, ARRAY['menstrual_phase','pain_tolerance','dysmenorrhea_reduction'], '2025-07-28T14:37:00+02:00'),

('Psychologische und Motivationseffekte des Zyklus', 'psychological_cycle_effects', 'science', 'Hormonfluktuationen beeinflussen Mood, Motivation und Stress-Response. Hohe Östrogenspiegel verbessern Resilienz und Confidence. Prä-menstruelle Phase zeigt 37% negative Auswirkung auf Mental Performance (Mood, Attention). Häufigste Symptome: Mood Swings, Fatigue, Reduced Focus.', 'dr_vita_femina', 4, ARRAY['psychological_effects','motivation','mood_swings'], '2025-07-28T14:38:00+02:00'),

('Exercise als PMS-Management: Meta-Analyse Evidenz', 'exercise_pms_management', 'research_finding', 'Systematische Reviews zeigen: Regelmäßiges Exercise (Aerobic, Yoga, Krafttraining) reduziert PMS-Symptome signifikant. Mechanismen: Erhöhte β-Endorphin-Spiegel, normalisierte Cortisol-Response, anti-inflammatorische Effekte. 30min, 3-5x/Woche optimal.', 'dr_vita_femina', 4, ARRAY['PMS_management','beta_endorphins','anti_inflammatory'], '2025-07-28T14:39:00+02:00'),

('Hormonelle Verhütung und Trainingsadaptation', 'hormonal_contraception_training', 'research_finding', 'Studie mit 4,594 Frauen: Hormonelle Verhütung beeinflusst Recovery-Response. Kombinations-Präparate zeigen stärkste Recovery-Reduktion, gefolgt von Progestin-only. Olympia-Athletinnen mit Verhütung haben höhere inflammatorische Exercise-Response vs. natürlich zyklisierende.', 'dr_vita_femina', 4, ARRAY['hormonal_contraception','recovery_response','inflammatory_response'], '2025-07-28T14:40:00+02:00'),

('HIIT vs. Traditional Training: Hormonelle Auswirkungen bei Frauen', 'hiit_hormonal_effects', 'research_finding', '10-Wochen-Studie (n=72): HIIT und Traditional Resistance Training modulieren Hormonspiegel bei jungen Frauen. Östrogen-Anstieg: HIIT +150%, TRT +72%. Testosteron-Reduktion: HIIT -58%, TRT -49%. Beide Modalitäten beeinflussen reproduktive und metabolische Gesundheit positiv.', 'dr_vita_femina', 4, ARRAY['HIIT','hormonal_modulation','estrogen_testosterone'], '2025-07-28T14:41:00+02:00'),

('Individualisierte Zyklus-Tracking Strategien', 'cycle_tracking_strategies', 'application', 'Apple Women''s Health Study: Nur 12% haben konsistente 28-Tage-Zyklen. Individuelle Variabilität erfordert personalisierte Ansätze. Empfehlung: 3-Monate Tracking (Basal-Temperatur, HRV, Symptome) vor zyklus-basiertem Training. One-size-fits-all-Protokolle ungeeignet.', 'dr_vita_femina', 5, ARRAY['individualized_tracking','cycle_variability','personalized_training'], '2025-07-28T14:42:00+02:00'),

('Fear Conditioning und Östrogen: Neuroplastizität im Zyklus', 'estrogen_neuroplasticity', 'science', 'Kontrollierte Studien zeigen: Östrogen-Administration beeinflusst Fear Extinction Learning. Supraphysiologische Östrogen-Dosen können Stress-Response und Motor Learning beeinträchtigen. Relevanz für High-Pressure Training-Situationen und Wettkampf-Performance.', 'dr_vita_femina', 3, ARRAY['estrogen_neuroplasticity','fear_extinction','stress_response'], '2025-07-28T14:43:00+02:00'),

('Praktische Zyklus-Periodisierung für Athletinnen', 'practical_cycle_periodization', 'application', 'Evidenz-basierte Periodisierung: Follikelphase (Heavy Lifting, PR-Attempts, High Volume), Ovulation (Power/HIIT, aber ACL-Schutz), Lutealphase (Technical Work, Mobility, -20% Volume), Menstruation (Active Recovery, Light Movement). Individuell anpassbar basierend auf Symptom-Response.', 'dr_vita_femina', 5, ARRAY['practical_periodization','evidence_based','individualized_approach'], '2025-07-28T14:44:00+02:00');