-- Insert L-Citrullin and L-Arginin supplement knowledge into coach knowledge base

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, source_url, created_at) VALUES
('L-Citrullin: Superior NO-Booster mit nachhaltiger Wirkung', 'l_citrullin_pump_enhancement', 'science', 'L-Citrullin zeigt überlegene Bioverfügbarkeit vs. L-Arginin, da es den hepatischen First-Pass-Metabolismus umgeht. 6-8g Citrullin-Malat oder 3-5g reines L-Citrullin erhöhen Plasma-Arginin nachhaltiger als direkte Arginin-Supplementierung. Wirkungseintritt nach 30-60min, Maximum nach 1-2h.', 'sascha', 4, ARRAY['l_citrullin_pump_enhancement'], NULL, '2025-07-28T12:29:29+02:00'),

('L-Citrullin Performance-Protokolle für Kraftsport', 'citrullin_strength_endurance', 'application', 'Studien zeigen: 8g Citrullin-Malat steigern Wiederholungszahlen bei Klimmzügen, Liegestützen und Beinpress signifikant. 2,4g L-Citrullin über 7 Tage verbessern 4km-Zeitfahrt und VO2-Kinetik. Reduktion von RPE (Rate of Perceived Exertion) und Muskelkater.', 'sascha', 4, ARRAY['citrullin_strength_endurance'], NULL, '2025-07-28T12:29:29+02:00'),

('L-Arginin: Schneller NO-Boost mit Limitierungen', 'l_arginin_nitric_oxide', 'science', 'L-Arginin hat nur 20% orale Bioverfügbarkeit aufgrund hepatischem Abbau durch Arginase. 2-5g täglich für allgemeine Zwecke, 6-10g für intensive Trainierende. Schnellere Wirkung als Citrullin (30-45min vs. 45-60min), aber kürzere Dauer. Bei >6g häufig GI-Beschwerden.', 'sascha', 3, ARRAY['l_arginin_nitric_oxide'], NULL, '2025-07-28T12:29:29+02:00'),

('Citrullin vs. Arginin: Evidenzbasierter Vergleich', 'citrullin_arginin_comparison', 'science', 'Meta-Analysen bestätigen: Citrullin erhöht Plasma-Arginin effektiver als Arginin selbst. Citrullin umgeht Arginase-Abbau, längere Halbwertszeit, weniger Nebenwirkungen. Arginin wirkt schneller, aber Effekt kürzer. Kombination beider kann synergistische Effekte erzielen.', 'lucy', 4, ARRAY['citrullin_arginin_comparison'], NULL, '2025-07-28T12:29:29+02:00'),

('L-Arginin für Herz-Kreislauf-Gesundheit', 'arginin_cardiovascular_health', 'application', 'L-Arginin senkt Blutdruck bei Hypertonie um 5-7 mmHg systolisch und 3-5 mmHg diastolisch. Verbessert endotheliale Funktion, reduziert ADMA-Spiegel. 3g täglich für kardiovaskuläre Prävention. Besonders effektiv bei Präeklampsie-Risiko (30-50% Reduktion).', 'lucy', 3, ARRAY['arginin_cardiovascular_health'], NULL, '2025-07-28T12:29:29+02:00'),

('Citrullin für Ausdauerleistung und Regeneration', 'citrullin_endurance_recovery', 'application', 'L-Citrullin 6g täglich über 7 Tage steigern Plasmaarginin und Nitrit signifikant, verbessern VO2-Kinetik und Trainingsleistung. Reduktion von Muskelkater und schnellere Regeneration durch verbesserte Durchblutung und Nährstofftransport. Ideal für Ausdauersportler.', 'kai', 4, ARRAY['citrullin_endurance_recovery'], NULL, '2025-07-28T12:29:29+02:00'),

('Optimales Timing für Citrullin und Arginin', 'amino_acid_timing_strategies', 'application', 'L-Citrullin: 30-60min vor Training für optimalen Pump-Effekt. L-Arginin: 30min vor Training für schnelle NO-Freisetzung. Kombination: Arginin für sofortige Wirkung, Citrullin für anhaltenden Effekt. Bei täglicher Einnahme: Arginin morgens, Citrullin pre-workout.', 'sascha', 4, ARRAY['amino_acid_timing_strategies'], NULL, '2025-07-28T12:29:29+02:00'),

('Citrullin-Malat vs. reines L-Citrullin', 'citrullin_forms_comparison', 'science', 'Citrullin-Malat (2:1 Ratio) bietet zusätzliche Energieproduktion durch Malat im Citratzyklus. 6-8g Citrullin-Malat = ca. 4-5g reines Citrullin. Malat kann Lactat-Clearance verbessern und Ermüdung reduzieren. Beide Formen zeigen vergleichbare NO-Steigerung.', 'lucy', 3, ARRAY['citrullin_forms_comparison'], NULL, '2025-07-28T12:29:29+02:00'),

('Arginin-Sicherheit und Dosierungsgrenzen', 'arginin_safety_dosage', 'guideline', 'Toleranzstudien zeigen Sicherheit bis 15g L-Arginin täglich, aber optimale Absorption bei max. 10g. Über 13g häufig GI-Komplikationen. Vorsicht bei niedrigem Blutdruck, Nierenproblemen. Interaktionen mit ACE-Hemmern und Viagra möglich. Max. 3g Einzeldosis empfohlen.', 'lucy', 3, ARRAY['arginin_safety_dosage'], NULL, '2025-07-28T12:29:29+02:00'),

('Synergistische Arginin-Citrullin-Stacks', 'arginin_citrullin_synergy', 'application', 'Kombinierte Einnahme zeigt additive Effekte: 3g L-Arginin + 3g L-Citrullin übertreffen Einzelsubstanzen. Arginin für schnelle NO-Freisetzung, Citrullin als "Arginin-Verstärker" für anhaltende Wirkung. Reduziert Arginase-bedingten Abbau, verlängert Plasma-Verfügbarkeit.', 'sascha', 4, ARRAY['arginin_citrullin_synergy'], NULL, '2025-07-28T12:29:29+02:00');