-- Deutsche Übersetzungen für Lucy's Knowledge Base Einträge

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Die Mikrobiom-Stoffwechsel-Verbindung', 'microbiome_nutrition_de', 'science', 'Dein Darmmikrobiom produziert über 1000 Metaboliten, die direkt Stoffwechsel, Entzündungen und Gehirnfunktion beeinflussen. Spezifische Bakterienstämme wie Akkermansia muciniphila korrelieren mit verbesserter Glukosetoleranz und reduzierter Adipositas. Präbiotische Fasern (Inulin, resistente Stärke) nähren nützliche Bakterien, während Probiotika (Lactobacillus rhamnosus, Bifidobacterium lactis) direkt metabolische Marker verbessern. Wir füttern nicht nur dich - wir füttern deine metabolischen Verbündeten.', 'lucy', 2, ARRAY['mikrobiom', 'präbiotika', 'probiotika', 'stoffwechsel', 'darmgesundheit'], now(), now()),

('Cortisol-bewusste Ernährungsstrategie', 'stress_nutrition_de', 'protocol', 'Chronischer Stress erhöht Cortisol und fördert viszerale Fettspeicherung und Insulinresistenz. Strategische Ernährung kann die HPA-Achse modulieren: Phosphatidylserin (100mg) reduziert Cortisol um 20%, Ashwagandha (300-600mg) senkt Stress-Biomarker, Magnesium-Glycinat (400mg) unterstützt parasympathische Erholung. Vermeide hochglykämische Lebensmittel während Stress-Peaks - sie verstärken Cortisol-Reaktion. Takte Kohlenhydrate am Abend zur Unterstützung von Cortisols natürlichem Rückgang.', 'lucy', 3, ARRAY['cortisol', 'stressessen', 'hpa_achse', 'adaptogene_kräuter', 'glykämische_kontrolle'], now(), now()),

('Typ-2-Diabetes Umkehr-Ernährungsprotokoll', 'medical_nutrition_de', 'application', 'Typ-2-Diabetes ist oft durch strategische Ernährung umkehrbar. Low-Carb-ketogener Ansatz (<50g Kohlenhydrate) oder intermittierendes Fasten (16:8 minimum) zeigen beide HbA1c-Reduktionen von 1-2%. Priorisiere: ballaststoffreiches Gemüse (unbegrenzt), Qualitätsproteine (1.2-1.6g/kg), gesunde Fette (Avocado, Nüsse, Olivenöl). Überwache Blutzucker 2 Stunden nach Mahlzeit - Ziel <140mg/dL. Chrom (200-400mcg) und Berberin (500mg 3x täglich) verbessern natürlich Insulinsensitivität.', 'lucy', 4, ARRAY['diabetes', 'hba1c', 'low_carb', 'intermittierendes_fasten', 'insulinsensitivität'], now(), now()),

('Hashimoto-Thyreoiditis Ernährungsunterstützung', 'autoimmune_nutrition_de', 'application', 'Hashimoto erfordert entzündungshemmende, nährstoffdichte Ernährung zur Schilddrüsenfunktions-Unterstützung und Autoimmunaktivitäts-Reduktion. Eliminiere Gluten (Kreuzreaktion mit Schilddrüsengewebe), reduziere Goitrogene (rohe Kreuzblütler), optimiere Jod (150-300mcg) und Selen (200mcg - 2 Paranüsse). Fokus auf: Wildfisch, Innereien, Algen und bunte Gemüse. Vitamin D (2000-4000 IU) und Zink (15-30mg) unterstützen Immunregulation.', 'lucy', 4, ARRAY['hashimoto', 'schilddrüse', 'autoimmun', 'glutenfrei', 'selen', 'jod'], now(), now()),

('Saisonale Ernährung & nachhaltige Proteinstrategien', 'sustainable_nutrition_de', 'methodology', 'Saisonales Essen optimiert Nährstoffdichte bei reduzierter Umweltbelastung. Frühling: entgiftende Grüns und Sprossen. Sommer: hydrierende Früchte und Gemüse. Herbst: erdende Wurzelgemüse und Nüsse. Winter: wärmende Proteine und konservierte Lebensmittel. Nachhaltige Protein-Hierarchie: Hülsenfrüchte und Hanf (niedrigste Belastung), regenerativ aufgezogene Tierproteine, dann konventionelle. Strebe 50% pflanzenbasierte Proteine an bei Erfüllung der Leucin-Anforderungen (2.5g pro Mahlzeit).', 'lucy', 3, ARRAY['saisonales_essen', 'nachhaltiges_protein', 'pflanzenbasiert', 'umweltbelastung', 'leucin'], now(), now()),

('Fortgeschrittene Chrono-Ernährung: Zirkadiane Mahlzeiten-Architektur', 'chrono_nutrition_de', 'protocol', 'Fortgeschrittenes Mahlzeiten-Timing nutzt zirkadiane Biologie für Stoffwechsel-Optimierung. Morgen (6-10 Uhr): Hohes Protein (30-40g) + komplexe Kohlenhydrate zur Synchronisation peripherer Uhren. Mittag (12-14 Uhr): Größte Mahlzeit mit ausgewogenen Makros während Peak-Insulinsensitivität. Abend (18-20 Uhr): Proteinreich, weniger Kohlenhydrate zur nächtlichen Fasten-Unterstützung. Vermeide Essen 3+ Stunden vor dem Schlaf - späte Mahlzeiten verzögern zirkadiane Phase um 5.7 Stunden und beeinträchtigen Glukosetoleranz.', 'lucy', 2, ARRAY['chronoernährung', 'zirkadiane_biologie', 'mahlzeiten_timing', 'insulinsensitivität', 'glukosetoleranz'], now(), now()),

('Langlebigkeits-Ernährung: Blue Zone Prinzipien angewandt', 'longevity_nutrition_de', 'methodology', 'Blue Zone Populationen leben am längsten durch spezifische Ernährungsmuster: 95% pflanzenbasierte Ernährung, moderate Kalorienrestriktion (1800-2000 kcal), tägliche Hülsenfrüchte, Nüsse (Handvoll täglich), moderater Rotwein (1-2 Gläser), minimale verarbeitete Lebensmittel. Schlüssel-Langlebigkeits-Verbindungen: Resveratrol (200mg), Spermidin (reich in gereiftem Käse, Pilzen) und Polyphenole (800mg+ täglich). Praktiziere "Hara Hachi Bu" - iss bis 80% satt zur Aktivierung von Langlebigkeits-Pfaden.', 'lucy', 3, ARRAY['langlebigkeit', 'blue_zones', 'kalorienrestriktion', 'resveratrol', 'spermidin', 'hara_hachi_bu'], now(), now()),

('PCOS Ernährung: Insulin-First Ansatz', 'hormonal_nutrition_de', 'application', 'PCOS-Management beginnt mit Insulin-Optimierung. Low-GI-Diät reduziert Testosteron um 22% und verbessert Ovulation. Strategisches Carb-Timing: konsumiere um Workouts herum wenn Insulinsensitivität peak ist. Inositol (4g täglich) wirkt natürlich wie Metformin. Pfefferminztee (2 Tassen täglich) reduziert freies Testosteron. Omega-3s (2g EPA+DHA) reduzieren Entzündungen. Intermittierendes Fasten 14:10 minimum verbessert Insulinsensitivität ohne Stress-Hormon-Erhöhung.', 'lucy', 4, ARRAY['pcos', 'insulinresistenz', 'low_gi', 'inositol', 'pfefferminze', 'omega_3'], now(), now());