-- Deutsche Übersetzungen für Sascha's Knowledge Base Einträge

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Fortgeschrittenes Testosteron-Optimierungsprotokoll', 'testosterone_optimization_de', 'protocol', 'Testosteron-Optimierung erfordert einen systematischen Ansatz. Grundlagen: 7-9 Stunden Schlaf, Krafttraining (Compound-Übungen 3-4x/Woche), Körperfett <15%. Zink 15-30mg, Vitamin D3 4000 IU, Magnesium 400mg täglich. Intermittierendes Fasten 16:8 erhöht Testosteron um 180%. Vermeide: Alkohol >2 Drinks/Woche, verarbeitete Lebensmittel, chronischen Stress. Lass alle 3 Monate Gesamt- und freies Testosteron testen. Ziel: Gesamt-T >600 ng/dL, freies T >15 pg/mL.', 'sascha', 1, ARRAY['testosteron', 'hormonoptimierung', 'zink', 'vitamin_d', 'intermittierendes_fasten'], now(), now()),

('Wachstumshormon-Optimierung durch Training', 'growth_hormone_optimization_de', 'application', 'Wachstumshormon (HGH) ist entscheidend für Muskelaufbau und Fettverbrennung. HGH-steigernde Faktoren: Hochintensive Intervalle (HIIT) 2-3x/Woche, Krafttraining mit kurzen Pausen (<60s), Tiefschlaf-Optimierung. Arginin 5-9g oder Glutamin 10-15g vor dem Training können HGH um 100-200% steigern. Fasten 16+ Stunden erhöht HGH 5-fach. Vermeide Zucker 2 Stunden vor dem Schlaf - blockiert nächtliche HGH-Ausschüttung um 80%.', 'sascha', 2, ARRAY['wachstumshormon', 'hiit', 'krafttraining', 'arginin', 'fasten'], now(), now()),

('Cortisol-Management für verbesserte Regeneration', 'cortisol_management_de', 'protocol', 'Chronisch erhöhtes Cortisol sabotiert Muskelaufbau und Fettabbau. Cortisol-senkende Strategien: Meditation 10-20 Min/Tag (-23% Cortisol), Ashwagandha 300-600mg (-27% Cortisol), Phosphatidylserin 100mg vor dem Schlaf. Training: Halte Einheiten <75 Min, vermeide täglich intensives Training. Schlaf vor 23 Uhr - jede Stunde später erhöht morgendliches Cortisol um 15%. Messe Cortisol-Awakening-Response zur Überwachung.', 'sascha', 3, ARRAY['cortisol', 'stressmanagement', 'ashwagandha', 'meditation', 'schlafoptimierung'], now(), now()),

('DHT und Haarausfall-Präventionsstrategien', 'dht_hair_loss_prevention_de', 'application', 'DHT (Dihydrotestosteron) verursacht androgenetischen Haarausfall. Natürliche 5α-Reduktase-Hemmer: Sägepalme 320mg täglich (-38% DHT), Kürbiskernöl 400mg, grüner Tee 3-4 Tassen. Äußerlich: Rosmarinöl ist so effektiv wie Minoxidil. Ketoconazol-Shampoo 2x/Woche reduziert Kopfhaut-DHT. Vermeide: Übermäßiges Kreatin (kann DHT erhöhen), enge Kopfbedeckungen, aggressives Styling. Biotin 5-10mg unterstützt Haarstruktur.', 'sascha', 2, ARRAY['dht', 'haarausfall', 'sägepalme', 'rosmarinöl', 'ketoconazol'], now(), now()),

('Schilddrüsen-Optimierung für männliche Performance', 'thyroid_optimization_de', 'science', 'Die Schilddrüse reguliert Stoffwechsel, Energie und Körpertemperatur. Optimaler TSH: 1.0-2.5 mIU/L, freies T3: oberes Drittel des Referenzbereichs. Schilddrüsen-unterstützende Nährstoffe: Jod 150-300mcg (Algen), Selen 200mcg (2 Paranüsse), Tyrosin 500-1000mg nüchtern. Vermeide: Rohe Kreuzblütler in großen Mengen, Soja, Fluorid. Kälteexposition aktiviert braunes Fett und T3-Umwandlung. Teste alle 6 Monate: TSH, fT3, fT4, rT3.', 'sascha', 3, ARRAY['schilddrüse', 'tsh', 'jod', 'selen', 'tyrosin'], now(), now()),

('Schlafoptimierung für hormonelle Gesundheit', 'sleep_optimization_de', 'protocol', 'Qualitätsschlaf ist die Grundlage hormoneller Optimierung. Schlafhygiene: Raum 16-19°C, komplett dunkel, keine Bildschirme 1h vor dem Schlaf. Magnesium Glycinat 400mg + Melatonin 0.5-3mg 30min vor dem Schlaf. Vermeide: Koffein nach 14 Uhr, Alkohol 3h vor dem Schlaf, große Mahlzeiten 2h vor dem Schlaf. Ziel: 7-9h Schlaf, Tiefschlaf >15%, REM >20%. Tracke mit HRV und Schlafphasen-Monitoring.', 'sascha', 1, ARRAY['schlafoptimierung', 'magnesium', 'melatonin', 'schlafhygiene', 'hrv'], now(), now()),

('Fortgeschrittene Insulin-Sensitivitätsprotokolle', 'insulin_sensitivity_de', 'application', 'Insulin-Sensitivität ist der Schlüssel zu Körperkomposition und metabolischer Gesundheit. Strategien: Intermittierendes Fasten 16:8 minimum, Krafttraining (verbessert GLUT4-Transport), 10.000+ Schritte täglich. Supplemente: Berberin 500mg 3x täglich (so effektiv wie Metformin), Chrom 200-400mcg, Alpha-Liponsäure 300-600mg. Timed Carbs: Kohlenhydrate um das Training herum für optimale Aufnahme. Meide: Verarbeitete Lebensmittel, Trans-Fette, High-Fructose-Corn-Sirup.', 'sascha', 4, ARRAY['insulin_sensitivität', 'berberin', 'intermittierendes_fasten', 'krafttraining', 'chrom'], now(), now());