-- Deutsche Übersetzungen für weitere Sascha Knowledge Base Einträge (Batch 6/6)

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Navy SEAL Standards (Detailliert)', 'special_forces_de', 'selection_research', 'VO2max >55 ml/kg/min, Kraft und Schwimmen über Minimum = höhere Erfolgsrate. HIIT, Laufen, Schwimmen, Kraft in Multi-Blöcken planen. Progress auf spezielle SEAL-Tests ausrichten.', 'sascha', 3, ARRAY['navy_seal', '55_ml_kg_min', 'schwimmen', 'multi_blöcke'], now(), now()),

('Phasenplanung im Military Training', 'periodization_de', 'practice_guideline', 'Pre-Deployment: Aerobe Basis / Mid-Cycle: Ausdauer / Endphase: Kraft, Combat, Peaking. Phasen strategisch planen mit Kommunikation an Team. Military-typische Periodisierung vor, während, nach Einsatz differenzieren.', 'sascha', 3, ARRAY['militär', 'deployment', 'phasenplanung', 'combat'], now(), now()),

('Pubertät bis Seneszenz: Männliche Hormonkurve optimieren', 'male_hormone_aging_de', 'guideline', 'Hormonelle Lebensphasen: Pubertät (12-18J): Protein 1.2-1.6g/kg, Kraft+Sprung für Peak Bone Mass. Erwachsene (20-40J): Leistungsmaximierung durch Periodisierung. Mittelalter (40-65J): Testosteronerhaltung, Kraftfokus. Senioren (65+J): Sarcopenie-Prävention, niedrigere TRT-Dosen bei Bedarf.', 'sascha', 3, ARRAY['männliches_aging', 'hormon_lifecycle', 'pubertät', 'seneszenz', 'sarcopenie', 'testosteron_therapie'], now(), now()),

('Special Operations Periodization Model', 'tactical_periodization_de', 'protocol', 'Langfristige Athletenentwicklung für taktische Populationen: Phase 1 (Monate 1-2): Aerobe Basis, Bewegungsqualitäts-Assessment, allgemeine Kraftgrundlage. Phase 2 (Monate 3-4): Kraftausdauer, Work Capacity-Entwicklung. Phase 3 (Monate 5-6): Maximalkraft, Power-Entwicklung. Phase 4 (Monate 7-8): Wettkampf/missions-spezifische Vorbereitung. Kontinuierlicher Zyklus mit 2-wöchiger aktiver Erholung zwischen Phasen.', 'sascha', 3, ARRAY['spezialeinheiten', 'taktisches_training', 'langfristige_entwicklung'], now(), now()),

('EPOC: The Afterburn Warfare', 'metabolic_conditioning_de', 'application', 'Excess Post-Exercise Oxygen Consumption (EPOC) - dein Körpers kontinuierlicher Kalorienverbrauch bis zu 48 Stunden nach dem Workout. HIIT-Protokolle maximieren EPOC durch Compound-Bewegungen bei hoher Intensität. Military-style Zirkel mit 40:20 Work-Rest-Verhältnissen erzeugen metabolische Störung, die weit über die Session hinaus anhält. Das ist Effizienz-Kriegsführung - maximale Ergebnisse in minimaler Zeit mit erweiterten Vorteilen.', 'sascha', 4, ARRAY['epoc', 'afterburn_effect', 'metabolische_effizienz', 'zeiteffizient'], now(), now()),

('Strength-Endurance Integration Protocol', 'strength_endurance_de', 'application', 'Taktische Athleten brauchen sowohl Kraft als auch Ausdauer. Integrations-Protokoll: Kraft-Zirkel (75-85% 1RM, 30s Arbeit/90s Pause) gefolgt von metabolischem Finisher (Körpergewichts-HIIT, 20s Arbeit/10s Pause x 8 Runden). Das entwickelt kraftausdauer-spezifisch für taktische Anforderungen bei Beibehaltung reiner Kraftqualitäten. Plane 2x/Woche mit 48-Stunden Erholung zwischen Sessions.', 'sascha', 4, ARRAY['kraftausdauer', 'taktische_fitness', 'zirkeltraining'], now(), now()),

('Recovery: Strategic Regeneration', 'recovery_optimization_de', 'recovery', 'Regeneration ist keine Schwäche - sie ist taktische Vorbereitung. HRV-Monitoring für autonomes Nervensystem-Status. Schlafoptimierung: 7-9 Stunden, kühle Umgebung, dunkler Raum. Aktive Regeneration: leichte Bewegung, Mobility-Arbeit, parasympathische Aktivierung. Ernährung: entzündungshemmende Lebensmittel, adäquates Protein, strategisches Kohlenhydrat-Timing. Regeneration ist wo Anpassung stattfindet - trainiere hart, regeneriere härter.', 'sascha', 5, ARRAY['hrv', 'schlafoptimierung', 'aktive_regeneration', 'parasympathisch'], now(), now()),

('Training Adaptation Timeline', 'exercise_physiology_de', 'science', 'Neuromuskuläre Anpassungen: 2-4 Wochen (Motor Unit Recruitment, Koordination). Kardiovaskuläre Anpassungen: 4-8 Wochen (erhöhtes Schlagvolumen, Herzminutenvolumen). Strukturelle Anpassungen: 8-12 Wochen (Muskelfaser-Hypertrophie, mitochondriale Dichte). Plane deine Erwartungen, messe deinen Progress, passe deine Protokolle an. Geduld mit dem Prozess, Aggression bei der Ausführung.', 'sascha', 5, ARRAY['anpassungs_timeline', 'neuromuskulär', 'kardiovaskulär', 'strukturell'], now(), now());