-- Add language column to existing quote tables
ALTER TABLE public.men_quotes ADD COLUMN language VARCHAR(2) DEFAULT 'de';
ALTER TABLE public.women_quotes ADD COLUMN language VARCHAR(2) DEFAULT 'de';

-- Update existing quotes to be marked as German
UPDATE public.men_quotes SET language = 'de';
UPDATE public.women_quotes SET language = 'de';

-- Insert English versions of men's quotes
INSERT INTO public.men_quotes (quote_text, author, language) VALUES
('It is easier to be a lover than a husband, because it is harder to have wit every day than to make a pretty remark from time to time.', 'Honoré de Balzac', 'en'),
('Often it is well-used leisure hours in which man finds the gate to a new world.', 'George M. Adams', 'en'),
('The body is like a car. If you take good care of it, you end up with a vintage model.', 'Karl Lagerfeld', 'en'),
('Well-groomed men are more appealing!', 'Tonsus', 'en'),
('A bachelor is a man who has only one problem - and it is solvable.', 'Woody Allen', 'en'),
('The true bachelor comes to the office from a different direction every morning.', 'Frank Sinatra', 'en'),
('When the state of the soul changes, this also changes the appearance of the body and vice versa: when the appearance of the body changes, this also changes the state of the soul.', 'Aristotle', 'en'),
('Elegance is not about being noticed, it is about being remembered.', 'Giorgio Armani', 'en'),
('Do you know what it means to come home to a woman who loves you, who is tender to you and also passionate? It means: you have landed in a strange apartment!', 'George Burns', 'en'),
('One should not fear death, but rather that one will never begin to live.', 'Marcus Aurelius', 'en'),
('Be kind to your body, so that the soul enjoys living in it.', 'Teresa of Avila', 'en'),
('Love is like a beard, if you don''t take care of it, you soon look stupid.', 'Tonsus', 'en'),
('In the old days, one shaved when one wanted to hear Beethoven, now one listens to Beethoven when one wants to shave.', 'Peter Bamm', 'en'),
('At twenty, nature gives you your face. At thirty, your face is shaped by life. How your face looks at fifty, however, is entirely up to you.', 'Coco Chanel', 'en'),
('The beard as a gender sign in the middle of the face is obscene. That''s why women like it.', 'Arthur Schopenhauer', 'en'),
('A man without a beard is like bread without crust.', 'Latvian Proverb', 'en'),
('With the beard on the face it is like with the golf course: only continuous care and cutting bring it to perfection.', 'Tonsus', 'en'),
('I am proud of my wrinkles, they are life in my face.', 'Brigitte Bardot', 'en'),
('Most men do not understand how to live at all, they just wear themselves out.', 'Charles Bukowski', 'en'),
('It is a great advantage to make the mistakes from which one can learn quite early.', 'Winston Churchill', 'en'),
('Beauty cannot be bought with money.', 'Paulo Coelho', 'en'),
('Without a mustache, a man is not properly dressed.', 'Salvador Dalí', 'en'),
('Well, let the women wash their hands after using the toilet. We men have learned not to pee on our hands.', 'Harald Schmidt', 'en'),
('A good lather is half the shave.', 'English Proverb', 'en'),
('A man''s face is his autobiography. A woman''s face is her work of fiction.', 'Oscar Wilde', 'en'),
('People who chase after ever greater fulfillment without ever taking time to enjoy it are like hungry people who are constantly cooking but never sit down to eat.', 'Marie von Ebner-Eschenbach', 'en'),
('What we need most in life is someone who makes us do what we are capable of.', 'Ralph Waldo Emerson', 'en'),
('One does not discover new continents without the courage to lose sight of old shores.', 'André Gide', 'en'),
('Classic material luxury may no longer be sufficiently satisfying. The new status symbols are wellness and health!', 'GDI Study 2008', 'en'),
('When scissors were invented, which certainly did not come from the oldest times, what was not said against the first ones who cut their nails and hair.', 'Voltaire', 'en'),
('We must constantly change, renew, rejuvenate, otherwise we harden.', 'Johann Wolfgang von Goethe', 'en'),
('One cannot always be a hero, but one can always be a man.', 'Johann Wolfgang von Goethe', 'en'),
('A gentleman is a man who always knows how far he can go too far with a woman.', 'Alec Guinness', 'en'),
('A gentleman is a man who regrets an unfair act even when it was crowned with success.', 'Sir Harold Wilson', 'en'),
('The right man can make you feel comfortable wherever you are, and that''s sexy.', 'Selita Ebanks', 'en'),
('As soon as someone has become a master in one thing, he should become a student in a new thing.', 'Gerhart Hauptmann', 'en'),
('If you do not have joy in yourself, the world will not give you joy.', 'Paul Heyse', 'en'),
('Be moderate in everything, breathe pure air, practice daily skin care and physical exercise, keep your head cool, your feet warm, and heal a small ailment rather by fasting than by medicine.', 'Hippocrates of Kos', 'en'),
('A well-groomed body and a well-groomed face represent an important status symbol: People attribute personal discipline and perfection to these people, and this in turn is also a prerequisite for professional success.', 'Dr. Helene Karmasin', 'en'),
('Every person has the chance to improve at least one part of the world, namely himself.', 'Paul Anton de Lagarde', 'en'),
('There is no luxury without perfume.', 'Karl Lagerfeld', 'en'),
('If you want to see valuable things, you only need to look where the great crowd does not look.', 'Laozi', 'en'),
('Style is more important than fashion trends.', 'Yves Saint Laurent', 'en'),
('Good looks and positive feelings belong together.', 'Alexander Lowen', 'en'),
('What pleases the eye refreshes the spirit, and what refreshes the spirit refreshes the body.', 'Prentice Mulford', 'en'),
('The fascinating thing about life is: If you insist on getting only the best, you often get it.', 'William Somerset Maugham', 'en'),
('We don''t need to continue living as we lived yesterday. Just free yourselves from this view, and a thousand possibilities invite us to new life.', 'Christian Morgenstern', 'en'),
('One should not be afraid to change one''s views. After all, you don''t wear a shirt for decades either.', 'John Osborne', 'en'),
('Stubble on the chin is mean, so always show yourself well-shaved.', 'Ovid', 'en'),
('I find beards beautiful; you see so little of the faces.', 'Anna Magnani', 'en'),
('To be successful, you must look as if you are successful.', 'Valentin Polcuch', 'en'),
('He who stops getting better has stopped being good.', 'Philip Rosenthal', 'en'),
('Success in life is something being, something appearance and a lot of luck.', 'Philip Rosenthal', 'en'),
('Taste is the art of understanding small things.', 'Jean-Jacques Rousseau', 'en'),
('When you take care of your body, your head feels better too.', 'Jil Sander', 'en'),
('Beauty is an open letter of recommendation that wins hearts for us in advance.', 'Arthur Schopenhauer', 'en'),
('Wise conduct of life succeeds for no one by chance. As long as one lives, one must learn how to live.', 'Seneca', 'en'),
('Make sure to have what you love, or you will be forced to love what you have.', 'George Bernard Shaw', 'en'),
('The art of resting is part of the art of working.', 'John Steinbeck', 'en'),
('We spend a large part of life earning the respect of others. But gaining self-respect, we spend little time on that.', 'Josef von Sternberg', 'en'),
('A gentleman will walk but never run.', 'Sting', 'en'),
('A gentleman is a man who pays for his girl''s birth control pills.', 'Dan Carter', 'en'),
('A gentleman forgets your age, but never your birthday.', 'Clark Gable', 'en'),
('What makes a man more beautiful than an ape is a luxury.', 'Aunt Jolesch', 'en'),
('Women have it hard from time to time too. But we men have to shave.', 'Kurt Tucholsky', 'en'),
('People with a new idea are considered crazy until the thing has caught on.', 'Mark Twain', 'en'),
('Every man needs five wives: a movie star, a maid, a cook, a listener and a nurse.', 'Mark Twain', 'en'),
('No woman is so bad that she cannot become the better half of a man.', 'Heinz Erhardt', 'en'),
('A man without vanity is no man.', 'John Wayne', 'en'),
('I have very simple tastes, I am always satisfied with the best.', 'Oscar Wilde', 'en'),
('The cultivated man never regrets a pleasure. The uncultivated man doesn''t know what a pleasure is.', 'Oscar Wilde', 'en'),
('He who has once found himself can lose nothing in this world.', 'Stefan Zweig', 'en'),
('Try not to become a man of success but rather try to become a man of value.', 'Albert Einstein', 'en'),
('A man cannot be comfortable without his own approval.', 'Mark Twain', 'en'),
('Better keep yourself clean and bright; you are the window through which you must see the world.', 'George Bernard Shaw', 'en'),
('Every man over forty is responsible for his face.', 'Abraham Lincoln', 'en'),
('A man is old when he can no longer put his compliments into action.', 'Charles Boyer', 'en'),
('A man has to do what a man has to do.', 'Proverb', 'en'),
('A man must be able to weld the exhaust pipe for his wife.', 'Gunter Gabriel', 'en'),
('For a man, what counts is what he has achieved, for a woman what he has told suffices.', 'Karl Kraus', 'en'),
('There are women you can only go to a nightclub with. All other places are already closed when they finish getting dressed.', 'Unknown', 'en'),
('With women it is, I hope you know, like with apples all around on the branches. The most beautiful don''t always taste the best.', 'Erich Kästner', 'en'),
('Happiness is a perfume that you cannot spray on others without getting a few drops yourself.', 'Ralph Waldo Emerson', 'en'),
('If you succeed in conquering inner peace, you have done more than he who has conquered cities and entire empires.', 'Michel de Montaigne', 'en'),
('It is not the wind, but the sails that determine the course.', 'Proverb', 'en'),
('Quality is never an accident; it is always the result of high intention, sincere effort, intelligent direction and skillful execution.', 'Will A. Foster', 'en'),
('The greatest events are not our loudest, but our quietest hours.', 'Friedrich Nietzsche', 'en'),
('Leisure seems to carry pleasure, true happiness and blissful life within itself.', 'Aristotle', 'en'),
('People who no longer know leisure and rest lead a poor life even in the greatest wealth.', 'Unknown', 'en'),
('Existence is delicious, one must only have the courage to lead one''s own life.', 'Giacomo Casanova', 'en'),
('Leisure is the art of being a pleasant companion to oneself.', 'Karl Heinrich Waggerl', 'en'),
('A man may make many mistakes. That doesn''t matter. But if the mistakes are too big and weigh on his life, he can only stop taking himself seriously.', 'Pedro Juan Gutiérrez', 'en'),
('Men''s dream would be to fall into women''s arms without falling into their hands at the same time.', 'Jerry Lewis', 'en'),
('A woman is like a tie: You only know if she fits when you have her around your neck.', 'Helmut Kohl', 'en'),
('When a girlfriend becomes too expensive, you have to marry her.', 'Peter Sellers', 'en'),
('One has a cozy home, the other doesn''t dare go home anymore.', 'Graf Fito', 'en'),
('Men rule the world and women rule their men. What more do they want?', 'Bogumil Goltz', 'en'),
('When a man opens the car door for a woman, either the car is new or the woman is.', 'Henry Ford', 'en'),
('Women like quiet men. They think they listen.', 'Unknown', 'en'),
('When men part, they say goodbye. When women part, they stand there for a long time.', 'Silesian Proverb', 'en'),
('Clever men always make a merit of their actions, even when necessity alone forces them to do so.', 'Niccolò Machiavelli', 'en'),
('Women are amazed at what men forget. Men are amazed at what women remember.', 'Peter Bamm', 'en'),
('What do we men have over you women? We never ask: Why didn''t you call?', 'George Clooney', 'en'),
('A man is someone who has backbone and not just starched shirts. Sometimes I think real men are an endangered species.', 'Bruce Willis', 'en'),
('It is much easier to die for a beloved woman than to live with her.', 'Lord Byron', 'en'),
('If a man wants his wife to listen to him silently, he must speak in his sleep.', 'Unknown', 'en'),
('Women most like to remember the men they could laugh with.', 'Anton Chekhov', 'en'),
('When men deviate from their straight path, female curves are usually the cause.', 'Unknown', 'en'),
('Men always want only one thing - women always want only the other.', 'Peter Silie', 'en'),
('A man''s strictest judges are his children.', 'Thornton Wilder', 'en'),
('Bachelors are men who know how small the chance is of finding a pearl in an oyster.', 'Unknown', 'en'),
('Many men forget the dessert in love. That''s a pity, because most women have a sweet tooth.', 'Mariella Pozzo', 'en'),
('Charm is the invisible part of beauty, without which no one can really be beautiful.', 'Sophia Loren', 'en'),
('Charm is a means of getting a YES without having asked a precise question about it.', 'Albert Camus', 'en'),
('Soap and education do not work as promptly as a massacre, but in the long run they are much more devastating.', 'Mark Twain', 'en'),
('Winners are not born, but made - and mainly by themselves.', 'Unknown', 'en'),
('Try to get what you love, otherwise you are forced to love what you get.', 'Unknown', 'en'),
('All hairiness is animal. Shaving is the badge of higher civilization.', 'Arthur Schopenhauer', 'en'),
('A clever man does not make all mistakes himself. He also gives others a chance.', 'Winston Churchill', 'en'),
('Every man of style and level is a hypochondriac.', 'Molière', 'en'),
('The only men who can see through a woman are the X-ray technicians.', 'Sacha Guitry', 'en'),
('No one is more aggressive or condescending towards women than a man who is not quite sure of his masculinity.', 'Simone de Beauvoir', 'en'),
('All men are vain - especially those who don''t admit it.', 'Sean Connery', 'en'),
('Aging is a bad habit that a busy man never lets develop.', 'André Maurois', 'en'),
('There are two things a man will never admit he can''t do well: sex and driving.', 'Stirling Moss', 'en'),
('All the emancipation fuss has not changed the fact that women make themselves beautiful to please men.', 'Marcello Mastroianni', 'en');