-- Insert Lucy knowledge base entries for advanced nutrition and medical nutrition therapy

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('The Microbiome-Metabolism Connection', 'microbiome_nutrition', 'science', 'Your gut microbiome produces over 1000 metabolites that directly influence metabolism, inflammation, and brain function. Specific bacterial strains like Akkermansia muciniphila correlate with improved glucose tolerance and reduced adiposity. Prebiotic fibers (inulin, resistant starch) feed beneficial bacteria, while probiotics (Lactobacillus rhamnosus, Bifidobacterium lactis) directly improve metabolic markers. We''re not just feeding you - we''re feeding your metabolic allies.', 'lucy', 2, ARRAY['microbiome', 'prebiotics', 'probiotics', 'metabolism', 'gut_health'], now(), now()),

('Cortisol-Conscious Nutrition Strategy', 'stress_nutrition', 'protocol', 'Chronic stress elevates cortisol, promoting visceral fat storage and insulin resistance. Strategic nutrition can modulate the HPA axis: phosphatidylserine (100mg) reduces cortisol by 20%, ashwagandha (300-600mg) lowers stress biomarkers, magnesium glycinate (400mg) supports parasympathetic recovery. Avoid high-glycemic foods during stress peaks - they amplify cortisol response. Time carbohydrates in evening to support cortisol''s natural decline.', 'lucy', 3, ARRAY['cortisol', 'stress_eating', 'HPA_axis', 'adaptogenic_herbs', 'glycemic_control'], now(), now()),

('Type 2 Diabetes Reversal Nutrition Protocol', 'medical_nutrition', 'application', 'Type 2 diabetes is often reversible through strategic nutrition. Low-carb ketogenic approach (<50g carbs) or intermittent fasting (16:8 minimum) both show HbA1c reductions of 1-2%. Prioritize: high-fiber vegetables (unlimited), quality proteins (1.2-1.6g/kg), healthy fats (avocado, nuts, olive oil). Monitor blood glucose 2 hours post-meal - target <140mg/dL. Chromium (200-400mcg) and berberine (500mg 3x daily) enhance insulin sensitivity naturally.', 'lucy', 4, ARRAY['diabetes', 'HbA1c', 'low_carb', 'intermittent_fasting', 'insulin_sensitivity'], now(), now()),

('Hashimoto''s Thyroiditis Nutrition Support', 'autoimmune_nutrition', 'application', 'Hashimoto''s requires anti-inflammatory, nutrient-dense nutrition to support thyroid function and reduce autoimmune activity. Eliminate gluten (cross-reacts with thyroid tissue), reduce goitrogens (raw cruciferous vegetables), optimize iodine (150-300mcg) and selenium (200mcg - 2 Brazil nuts). Focus on: wild-caught fish, organ meats, seaweed, and colorful vegetables. Vitamin D (2000-4000 IU) and zinc (15-30mg) support immune regulation.', 'lucy', 4, ARRAY['hashimotos', 'thyroid', 'autoimmune', 'gluten_free', 'selenium', 'iodine'], now(), now()),

('Seasonal Nutrition & Sustainable Protein Strategies', 'sustainable_nutrition', 'methodology', 'Eating seasonally optimizes nutrient density while reducing environmental impact. Spring: detoxifying greens and sprouts. Summer: hydrating fruits and vegetables. Fall: grounding root vegetables and nuts. Winter: warming proteins and preserved foods. Sustainable protein hierarchy: legumes and hemp (lowest impact), regeneratively-raised animal proteins, then conventional. Aim for 50% plant-based proteins while meeting leucine requirements (2.5g per meal).', 'lucy', 3, ARRAY['seasonal_eating', 'sustainable_protein', 'plant_based', 'environmental_impact', 'leucine'], now(), now()),

('Advanced Chrononutrition: Circadian Meal Architecture', 'chrono_nutrition', 'protocol', 'Advanced meal timing leverages circadian biology for metabolic optimization. Morning (6-10 AM): High protein (30-40g) + complex carbs to sync peripheral clocks. Midday (12-2 PM): Largest meal with balanced macros during peak insulin sensitivity. Evening (6-8 PM): Protein-rich, lower carbs to support overnight fasting. Avoid eating 3+ hours before bed - late meals delay circadian phase by 5.7 hours and impair glucose tolerance.', 'lucy', 2, ARRAY['chrononutrition', 'circadian_biology', 'meal_timing', 'insulin_sensitivity', 'glucose_tolerance'], now(), now()),

('Longevity Nutrition: Blue Zone Principles Applied', 'longevity_nutrition', 'methodology', 'Blue Zone populations live longest through specific nutrition patterns: 95% plant-based diet, moderate caloric restriction (1800-2000 kcal), daily legumes, nuts (handful daily), moderate red wine (1-2 glasses), minimal processed foods. Key longevity compounds: resveratrol (200mg), spermidine (rich in aged cheese, mushrooms), and polyphenols (800mg+ daily). Practice "Hara Hachi Bu" - eat until 80% full to activate longevity pathways.', 'lucy', 3, ARRAY['longevity', 'blue_zones', 'caloric_restriction', 'resveratrol', 'spermidine', 'hara_hachi_bu'], now(), now()),

('PCOS Nutrition: Insulin-First Approach', 'hormonal_nutrition', 'application', 'PCOS management starts with insulin optimization. Low-GI diet reduces testosterone by 22% and improves ovulation. Strategic carb timing: consume around workouts when insulin sensitivity peaks. Inositol (4g daily) acts like metformin naturally. Spearmint tea (2 cups daily) reduces free testosterone. Omega-3s (2g EPA+DHA) reduce inflammation. Intermittent fasting 14:10 minimum improves insulin sensitivity without stress-hormone elevation.', 'lucy', 4, ARRAY['PCOS', 'insulin_resistance', 'low_GI', 'inositol', 'spearmint', 'omega_3'], now(), now());