-- Insert Kai knowledge base entries for biohacking and performance optimization

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('HRV Data Interpretation: Your Autonomic Dashboard', 'hrv_analytics', 'protocol', 'HRV isn''t just a number - it''s your nervous system''s real-time status report. RMSSD <30ms = parasympathetic suppression, requires active recovery. LF/HF ratio >4.0 = sympathetic overdrive, reduce training intensity by 20-30%. 7-day rolling average drops >8% = deload week initiated. Track RMSSD, SDNN, and stress score trends, not single values. Your HRV data guides when to push limits and when to prioritize recovery.', 'kai', 1, ARRAY['HRV', 'data_interpretation', 'RMSSD', 'parasympathetic', 'training_adaptation'], now(), now()),

('Sleep Architecture Analytics: Decoding Your Recovery Data', 'sleep_analytics', 'application', 'Your sleep data tells the story of your recovery. REM <15% of total sleep = stress overload or alcohol interference. Deep sleep <13% = growth hormone suppression, muscle recovery compromised. Sleep efficiency <85% = sleep hygiene issues. Track sleep onset latency: >20 minutes indicates sympathetic hyperactivation. Use sleep stage percentages to adjust training load: poor deep sleep = reduce volume by 25%.', 'kai', 2, ARRAY['sleep_analytics', 'REM', 'deep_sleep', 'sleep_efficiency', 'recovery_data'], now(), now()),

('Digital Detox Protocols: Reclaiming Cognitive Bandwidth', 'digital_wellness', 'methodology', 'Digital overstimulation fragments attention and elevates cortisol. Implement progressive digital detox: Week 1: Phone-free mornings until 9 AM. Week 2: No screens 1 hour before bed. Week 3: Complete phone shutdown 8 PM-8 AM. Week 4: 24-hour digital fasts weekly. Track improvements in sleep quality, HRV, and focus scores. Blue light after 9 PM suppresses melatonin by 50% - use data to optimize your digital boundaries.', 'kai', 3, ARRAY['digital_detox', 'blue_light', 'melatonin', 'cortisol', 'attention_training'], now(), now()),

('Flow State Induction: The Neuroscience of Peak Performance', 'flow_psychology', 'protocol', 'Flow states occur when challenge matches skill level precisely (4% difficulty increase optimal). Neurologically: reduced prefrontal cortex activity, increased dopamine/norepinephrine. Pre-flow protocol: 10-minute focused breathing, clear goal setting, eliminate distractions. Track flow indicators: time distortion, effortless concentration, intrinsic motivation. Use RPE and motivation scores to identify flow windows - typically occur at 7-8 RPE with high motivation scores.', 'kai', 2, ARRAY['flow_state', 'peak_performance', 'dopamine', 'prefrontal_cortex', 'challenge_skill_balance'], now(), now()),

('Cold-Heat Hormesis: Temperature Therapy for Resilience', 'temperature_therapy', 'application', 'Controlled temperature stress builds physiological and psychological resilience. Cold exposure (10-15°C, 2-4 minutes): increases norepinephrine 250%, improves brown fat activation, enhances focus. Heat exposure (80-100°C sauna, 15-20 minutes): increases heat shock proteins, growth hormone +2400%, improves cardiovascular function. Protocol: 3x/week alternating. Track HRV improvements and stress tolerance metrics post-sessions.', 'kai', 3, ARRAY['cold_exposure', 'heat_therapy', 'norepinephrine', 'heat_shock_proteins', 'hormesis'], now(), now()),

('Cognitive Load Management: Mental Energy Optimization', 'cognitive_optimization', 'methodology', 'Your cognitive resources are finite and trackable. Decision fatigue peaks after 3-4 hours of focused work. Pre-load decisions: automate meal choices, workout plans, and daily routines. Track mental energy on 1-10 scale 3x daily. When cognitive load >7, avoid complex decisions. Schedule high-cognitive tasks during cortisol peak (8-10 AM). Use motivation and focus scores to optimize mental performance windows.', 'kai', 2, ARRAY['cognitive_load', 'decision_fatigue', 'mental_energy', 'cortisol_timing', 'automation'], now(), now()),

('Stress Resilience Building: Controlled Adversity Training', 'stress_resilience', 'protocol', 'Resilience is trainable through progressive stress exposure. Controlled stressors: cold showers, breath holds, challenging workouts at >8 RPE. Key principle: voluntary discomfort builds involuntary stress tolerance. Track stress markers: resting heart rate, HRV recovery, subjective stress scores. Progressive protocol: Week 1-2: 30-second cold exposure, Week 3-4: 60 seconds, Week 5-6: 90 seconds. Monitor adaptation through improved baseline metrics.', 'kai', 2, ARRAY['stress_resilience', 'controlled_stress', 'adaptation', 'progressive_overload', 'voluntary_discomfort'], now(), now()),

('Libido and Motivation Correlation Analysis', 'biomarker_analysis', 'science', 'Libido is a powerful biomarker for overall hormonal and psychological health. Low libido correlates with elevated cortisol, reduced testosterone, and overtraining syndrome. Track libido scores alongside HRV, sleep quality, and training load. Declining libido trends indicate need for deload, stress reduction, or hormonal support. Optimal libido scores (7-9/10) correlate with peak motivation, training capacity, and recovery efficiency.', 'kai', 1, ARRAY['libido', 'hormonal_health', 'testosterone', 'cortisol', 'overtraining', 'biomarkers'], now(), now());