-- Add new male hormone optimization knowledge entries for Sascha
INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Testosteron-Optimierung durch schweres Krafttraining', 'male_hormone_optimization', 'protocol', 'Schweres Krafttraining (80-85% 1RM) mit Compound-Übungen wie Squats, Deadlifts und Bench Press steigert Testosteron am effektivsten. Meta-Analysen zeigen 15-20% Testosteronerhöhung bei sedentären älteren Männern. Optimales Training: 3x/Woche, 3-5 Sätze × 4-6 Wiederholungen, 2-3min Pause. Morning Training (7-10 AM) nutzt natürlichen Testosteron-Peak.', 'sascha', 1, '{testosterone,strength_training,compound_exercises,hormone_optimization}', '2025-07-28T12:00:00+02:00', now()),

('HIIT für Testosteron und Growth Hormone Boost', 'male_hormone_optimization', 'protocol', 'High-Intensity Interval Training stimuliert Testosteron und Wachstumshormon synergistisch. 4×4-Protokoll zeigt 17% Testosteronerhöhung und 18-fachen GH-Anstieg bei Männern 55+. Protokoll: 4min @ 85-95% HRmax, 3min aktive Erholung, 2x/Woche. Kombination HIIT + Krafttraining überlegen vs. isoliertes Training.', 'sascha', 1, '{HIIT,testosterone,growth_hormone,interval_training,hormonal_response}', '2025-07-28T12:00:00+02:00', now()),

('Andropause-Management: Natürliche Testosteronerhaltung', 'male_hormone_aging', 'guideline', 'Männer verlieren ab 35 Jahren 1% Testosteron/Jahr, ab 65 primärer Hypogonadismus häufiger. Lifestyle-Interventionen können sekundären Hypogonadismus umkehren: Gewichtsreduktion bei BMI >30, regelmäßiges Training, Stressmanagement. Krafttraining + Ausdauer kombiniert zeigt beste Ergebnisse bei altersbedingtem Testosteronmangel.', 'sascha', 2, '{andropause,aging,testosterone_decline,lifestyle_intervention,secondary_hypogonadism}', '2025-07-28T12:00:00+02:00', now()),

('Testosteron-optimierte Ernährung für Männer', 'male_nutrition_hormones', 'application', 'Spezifische Nährstoffe steigern Testosteronproduktion: Zink (15-30mg/Tag) aus Austern, Beef; Vitamin D (2000-4000 IU); gesunde Fette 25-30% der Kalorien; Magnesium (400mg) aus Spinat, Nüssen. Vermeiden: Übermäßiger Zucker, Transfette, Alkohol >2 Drinks/Tag. Proteinaufnahme 1.6-2.2g/kg für Muskelerhalt.', 'sascha', 2, '{testosterone_nutrition,zinc,vitamin_D,healthy_fats,protein,male_diet}', '2025-07-28T12:00:00+02:00', now()),

('IGF-1 und anabole Hormon-Kaskade beim Mann', 'male_hormone_optimization', 'science', 'IGF-1 korreliert mit aerober Fitness und Muskelausdauer, aber nicht direkt mit Hypertrophie. Mechanischer Stress durch schweres Training stimuliert lokale IGF-1-Produktion (MGF). Kombiniertes Kraft- und Ausdauertraining optimiert systemisches IGF-1. Alter 35-65: IGF-1 sinkt 1-2%/Jahr, durch Training teilweise reversibel.', 'sascha', 3, '{IGF-1,growth_factors,anabolic_hormones,mechanical_stress,aging}', '2025-07-28T12:00:00+02:00', now()),

('Cortisol-Management für männliche Hormonbalance', 'male_hormone_optimization', 'protocol', 'Chronisch erhöhtes Cortisol supprimiert Testosteronproduktion durch GnRH-Hemmung. Stress-Reduktionsstrategien: Meditation 20min/Tag, adequate Schlaf 7-9h, Vermeidung Übertraining. Training-Timing: Intensive Sessions vor 18:00, um Cortisol-Rhythmus zu respektieren. Adaptogene: Ashwagandha 300-600mg zeigt 18% Testosteronerhöhung.', 'sascha', 2, '{cortisol,stress_management,testosterone,GnRH,adaptogenic_herbs,circadian_rhythm}', '2025-07-28T12:00:00+02:00', now()),

('Pubertät bis Seneszenz: Männliche Hormonkurve optimieren', 'male_hormone_aging', 'guideline', 'Hormonelle Lebensphasen: Pubertät (12-18J): Protein 1.2-1.6g/kg, Kraft+Sprung für Peak Bone Mass. Erwachsene (20-40J): Leistungsmaximierung durch Periodisierung. Mittelalter (40-65J): Testosteronerhaltung, Kraftfokus. Senioren (65+J): Sarcopenie-Prävention, niedrigere TRT-Dosen bei Bedarf.', 'sascha', 3, '{male_aging,hormone_lifecycle,puberty,senescence,sarcopenia,testosterone_therapy}', '2025-07-28T12:00:00+02:00', now());