-- Deutsche Übersetzungen für Kai's Knowledge Base (Batch 1/2)

INSERT INTO public.coach_knowledge_base (title, expertise_area, knowledge_type, content, coach_id, priority_level, tags, created_at, updated_at) VALUES
('Biofeedback-Training', 'biofeedback_training_de', 'performance_psychology', 'Objektive Körpersignale für subjektive Optimierung nutzen: HRV-Biofeedback für autonomes Nervensystem-Training, EEG-Neurofeedback für Fokus und Flow-States, EMG für Muskelspannung-Kontrolle. Real-time Feedback ermöglicht bewusste Steuerung unbewusster Prozesse. 4-7-8 Atmung mit HRV-Monitoring für Stressreduktion. Regelmäßiges Training schafft neue neuronale Pathways.', 'kai', 4, ARRAY['biofeedback', 'hrv_training', 'neurofeedback', 'autonomes_nervensystem'], now(), now()),

('Zirkadiane Rhythmus-Optimierung', 'circadian_optimization_de', 'sleep_science', 'Circadiane Biologie für Performance nutzen: Morgenlicht (10.000 Lux, 20-30min) für Cortisol-Peak, blaues Licht abends vermeiden, Kerntemperatur-Rhythmus beachten. Chronotyp bestimmen: Larchen vs. Eulen haben unterschiedliche Peak-Performance-Zeiten. Melatonin-Timing: 1-3mg, 30-60min vor gewünschter Schlafzeit. Jet-Lag-Protokolle mit strategischem Licht und Fastenzeiten.', 'kai', 5, ARRAY['zirkadiane_rhythmen', 'morgenlicht', 'chronotyp', 'melatonin_timing'], now(), now()),

('Gewohnheitsbildung Psychologie', 'habit_formation_de', 'behavioral_psychology', 'Habit-Loop: Trigger → Routine → Belohnung → neuronale Verknüpfung. 21-Tage-Mythos: tatsächlich 18-254 Tage je nach Komplexität. Keystone Habits: Eine gute Gewohnheit triggert weitere positive Veränderungen. Implementation Intentions: "Wenn X, dann Y" für automatische Verhaltensausführung. Habit Stacking: neue Gewohnheit an bestehende anhängen. Umgebungsdesign > Willenskraft.', 'kai', 4, ARRAY['gewohnheitsbildung', 'habit_loop', 'keystone_habits', 'implementation_intentions'], now(), now()),

('Achtsamkeitstraining', 'mindfulness_training_de', 'meditation_science', 'Evidenzbasierte Meditation für Performance: 10min täglich strukturierte Achtsamkeit verändert Gehirnstruktur in 8 Wochen. Prefrontaler Cortex verstärkt (Entscheidungen), Amygdala reduziert (Stress-Reaktion). Body-Scan für Körperbewusstsein, Atem-Fokus für Konzentration, Loving-Kindness für emotionale Regulation. MBSR-Protokolle wissenschaftlich validiert. Apps vs. stille Meditation je nach Lerntyp.', 'kai', 4, ARRAY['achtsamkeit', 'meditation', 'mbsr', 'gehirnstruktur'], now(), now()),

('Motivationspsychologie', 'motivation_psychology_de', 'performance_psychology', 'Intrinsische vs. extrinsische Motivation: autonomy, mastery, purpose als Langzeit-Motivatoren. Flow-Theorie: Challenge-Skill-Balance für optimale Experience. Goal-Setting: SMART-Ziele + emotionale Verbindung. Implementation Intentions reduzieren Motivation-Action-Gap. Dopamin-Systeme verstehen: Belohnungserwartung > Belohnung selbst. Progress-Tracking verstärkt motivationale Schleifen.', 'kai', 4, ARRAY['intrinsische_motivation', 'flow_theorie', 'smart_ziele', 'dopamin_systeme'], now(), now()),

('Neurobiologie der Performance', 'neurobiology_de', 'neuroscience', 'Gehirn-Performance-Connection: Neuroplastizität durch gezieltes Training, Myelinisierung durch Wiederholung, Synaptogenese durch neue Herausforderungen. Neurotransmitter-Optimierung: Dopamin (Motivation), Serotonin (Wohlbefinden), GABA (Entspannung), Acetylcholin (Fokus). Exercise = BDNF-Booster für neuronales Wachstum. Cold Exposure aktiviert Noradrenalin für mentale Klarheit.', 'kai', 5, ARRAY['neuroplastizität', 'neurotransmitter', 'bdnf', 'noradrenalin'], now(), now()),

('Neuroplastizität Training', 'neuroplasticity_de', 'cognitive_enhancement', 'Gehirn-Formbarkeit lebenslang nutzen: Dual N-Back für Arbeitsgedächtnis, neue Sprachen für kognitive Reserve, Musikinstrumente für sensomotorische Integration. Critical Windows: intensive Phasen mit Recovery für optimale Anpassung. Cross-Training für Gehirn: verschiedene kognitive Domains trainieren. Schlaf konsolidiert neue neuronale Verbindungen. Stress hemmt, moderate Herausforderung fördert Plastizität.', 'kai', 4, ARRAY['neuroplastizität_training', 'arbeitsgedächtnis', 'kognitive_reserve', 'cross_training'], now(), now()),

('Psychologie der Höchstleistung', 'psychology_de', 'performance_psychology', 'Mental Skills für Peak Performance: Visualization (mentale Rehearsal), Self-Talk (internal dialogue optimization), Concentration (attention training), Confidence (self-efficacy building). Pre-Performance Routines schaffen konsistente mentale Zustände. Pressure Training: absichtliche Stress-Exposition für Wettkampf-Robustheit. Mindset: Growth > Fixed für langfristige Entwicklung.', 'kai', 5, ARRAY['peak_performance', 'visualization', 'self_talk', 'growth_mindset'], now(), now()),

('Regenerations-Optimierung', 'recovery_optimization_de', 'recovery_science', 'Active Recovery vs. Complete Rest: individuell basierend auf Training Load und HRV. Parasympathikus-Aktivierung: 4-7-8 Atmung, kalte Duschen, Massage, Meditation. Sleep Hygiene: konstante Zeiten, kühle Temperatur (16-19°C), dunkler Raum, keine Bildschirme 1h vor Schlaf. Nutrition for Recovery: Protein vor Schlaf, Magnesium, Tart Cherry für natürliches Melatonin.', 'kai', 5, ARRAY['aktive_regeneration', 'parasympathikus', 'sleep_hygiene', 'recovery_nutrition'], now(), now()),

('Regenerations-Periodisierung', 'recovery_periodization_de', 'training_science', 'Systematische Erholungsplanung: Hard Days → Easy Days im Verhältnis 1:1 bis 2:1. Deload Weeks alle 3-4 Wochen mit 40-60% Volumenreduktion. Tapering vor wichtigen Events: 2-3 Wochen progressive Volumenreduktion bei Intensitätsbeibehaltung. HRV-guided Training: bei niedrigen Werten Recovery Days einbauen. Periodische Trainingsunterbrechungen für Supercompensation.', 'kai', 4, ARRAY['recovery_periodisierung', 'deload_weeks', 'tapering', 'supercompensation'], now(), now()),

('Schlaf-Optimierung', 'sleep_optimization_de', 'sleep_science', 'Schlaf als Performance-Tool: 7-9h für Athleten, REM-Schlaf für motorisches Lernen, Tiefschlaf für physische Regeneration. Sleep Extension: +1h Schlaf = +10% Performance. Naps: 10-20min Power Naps oder 90min für kompletten Zyklus. Temperature Drop: 1-2°C Kerntemperatur-Senkung triggert Sleepiness. Bedroom: dunkel, kühl, leise, Handys draußen. Consistency > Optimierung.', 'kai', 5, ARRAY['schlafoptimierung', 'rem_schlaf', 'power_naps', 'sleep_extension'], now(), now()),

('Schlaf-Regeneration', 'sleep_recovery_de', 'recovery_science', 'Schlaf-Phasen für verschiedene Recovery-Aspekte: Slow-Wave-Sleep (SWS) für Gewebereparatur und Wachstumshormon-Release, REM für emotionale Verarbeitung und Gedächtnis-Konsolidierung. Sleep Debt: kumulative Effekte von Schlafmangel. Recovery Sleep: nach Schlafentzug braucht Körper 2-3 Nächte für vollständige Regeneration. Sleep Aids: Melatonin, Magnesium, L-Theanin als natürliche Optionen.', 'kai', 4, ARRAY['sleep_recovery', 'slow_wave_sleep', 'sleep_debt', 'sleep_aids'], now(), now()),

('Stressmanagement', 'stress_management_de', 'stress_psychology', 'Stress-Response-System verstehen: Akuter Stress = Performance-Booster, chronischer Stress = Performance-Killer. Stressoren kategorisieren: kontrollierbar vs. unkontrollierbar. Coping Strategies: Problem-focused (Situation ändern) vs. Emotion-focused (Reaktion ändern). Stress Inoculation: graduelle Exposition für Resilienz-Aufbau. Relaxation Response: progressive Muskelentspannung, Atmungstechniken.', 'kai', 5, ARRAY['stressmanagement', 'coping_strategies', 'stress_inoculation', 'relaxation_response'], now(), now());