-- Add English quotes for women
INSERT INTO women_quotes (quote_text, author, language) VALUES
('The only way to do great work is to love what you do.', 'Steve Jobs', 'en'),
('Be yourself; everyone else is already taken.', 'Oscar Wilde', 'en'),
('You miss 100% of the shots you don''t take.', 'Wayne Gretzky', 'en'),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'en'),
('It is during our darkest moments that we must focus to see the light.', 'Aristotle', 'en'),
('The only impossible journey is the one you never begin.', 'Tony Robbins', 'en'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'en'),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'en'),
('Don''t let yesterday take up too much of today.', 'Will Rogers', 'en'),
('You learn more from failure than from success.', 'Unknown', 'en'),
('If you are working on something that you really care about, you don''t have to be pushed.', 'Steve Jobs', 'en'),
('Experience is the teacher of all things.', 'Julius Caesar', 'en'),
('Even if you are on the right track, you''ll get run over if you just sit there.', 'Will Rogers', 'en'),
('It is better to fail in originality than to succeed in imitation.', 'Herman Melville', 'en'),
('The road to success and the road to failure are almost exactly the same.', 'Colin R. Davis', 'en'),
('Someone is sitting in the shade today because someone planted a tree a long time ago.', 'Warren Buffett', 'en'),
('Don''t be afraid to give yourself everything you''ve ever wanted in life.', 'Unknown', 'en'),
('If you don''t design your own life plan, chances are you''ll fall into someone else''s plan.', 'Jim Rohn', 'en'),
('Try not to become a person of success, but rather try to become a person of value.', 'Albert Einstein', 'en'),
('A successful woman is one who can build a firm foundation with the bricks others have thrown at her.', 'David Brinkley', 'en'),
('I''ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.', 'Maya Angelou', 'en'),
('The most common way people give up their power is by thinking they don''t have any.', 'Alice Walker', 'en'),
('The question isn''t who is going to let me; it''s who is going to stop me.', 'Ayn Rand', 'en'),
('If you want something said, ask a man; if you want something done, ask a woman.', 'Margaret Thatcher', 'en'),
('Above all, be the heroine of your life, not the victim.', 'Nora Ephron', 'en'),
('The most effective way to do it, is to do it.', 'Amelia Earhart', 'en'),
('A woman is like a tea bag – you never know how strong she is until she gets in hot water.', 'Eleanor Roosevelt', 'en'),
('There is no limit to what we, as women, can accomplish.', 'Michelle Obama', 'en'),
('I alone cannot change the world, but I can cast a stone across the waters to create many ripples.', 'Mother Teresa', 'en'),
('Well-behaved women seldom make history.', 'Laurel Thatcher Ulrich', 'en'),
('A strong woman understands that the gifts such as logic, decisiveness, and strength are just as feminine as intuition and emotional connection.', 'Nancy Rathburn', 'en'),
('You are more powerful than you know; you are beautiful just as you are.', 'Melissa Etheridge', 'en'),
('The way I see it, if you want the rainbow, you got to put up with the rain.', 'Dolly Parton', 'en'),
('Power is not given to you. You have to take it.', 'Beyoncé', 'en'),
('If you don''t see a clear path for what you want, sometimes you have to make it yourself.', 'Mindy Kaling', 'en'),
('I have learned over the years that when one''s mind is made up, this diminishes fear.', 'Rosa Parks', 'en'),
('Champions keep playing until they get it right.', 'Billie Jean King', 'en'),
('Optimism is the faith that leads to achievement.', 'Helen Keller', 'en'),
('You can''t be that kid standing at the top of the waterslide, overthinking it.', 'Tina Fey', 'en'),
('I want every girl to know that her voice can change the world.', 'Malala Yousafzai', 'en'),
('Nothing is impossible, the word itself says I''m possible!', 'Audrey Hepburn', 'en'),
('The most courageous act is still to think for yourself. Aloud.', 'Coco Chanel', 'en'),
('You have what it takes to be a victorious, independent, fearless woman.', 'Tyra Banks', 'en'),
('Take criticism seriously, but not personally.', 'Hillary Clinton', 'en'),
('Don''t compromise yourself. You are all you''ve got.', 'Janis Joplin', 'en'),
('If you want to lift yourself up, lift up someone else.', 'Booker T. Washington', 'en'),
('The difference between successful people and others is how long they spend time feeling sorry for themselves.', 'Barbara Corcoran', 'en'),
('I didn''t get there by wishing for it or hoping for it, but by working for it.', 'Estée Lauder', 'en'),
('Think like a queen. A queen is not afraid to fail.', 'Oprah Winfrey', 'en'),
('Success isn''t about how much money you make, it''s about the difference you make in people''s lives.', 'Michelle Obama', 'en'),
('The secret of getting ahead is getting started.', 'Mark Twain', 'en'),
('Don''t wait for opportunity. Create it.', 'Unknown', 'en'),
('Life shrinks or expands in proportion to one''s courage.', 'Anaïs Nin', 'en'),
('You are enough just as you are.', 'Meghan Markle', 'en'),
('What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'Ralph Waldo Emerson', 'en'),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'en'),
('Believe you can and you''re halfway there.', 'Theodore Roosevelt', 'en'),
('She believed she could, so she did.', 'R.S. Grey', 'en'),
('You are braver than you believe, stronger than you seem, and smarter than you think.', 'A.A. Milne', 'en'),
('The only thing standing between you and your goal is the story you keep telling yourself.', 'Jordan Belfort', 'en'),
('You have been assigned this mountain to show others it can be moved.', 'Mel Robbins', 'en');