-- Insert Nature Love Probiona Kulturen Komplex product
INSERT INTO public.supplement_products (
  brand_id,
  supplement_id,
  product_name,
  pack_size,
  pack_unit,
  servings_per_pack,
  dose_per_serving,
  dose_unit,
  price_eur,
  price_per_serving,
  form,
  category,
  country_of_origin,
  is_vegan,
  is_verified,
  is_recommended,
  quality_tags,
  timing,
  amazon_asin,
  amazon_url,
  product_url,
  short_description,
  synergies,
  blockers
) VALUES (
  '2a3839ba-fbea-44f5-bd29-1b370482081f', -- Nature Love brand_id
  '12ae3995-c881-4eef-b9ea-3781a5073dc0', -- Probiona Kulturen Komplex supplement_id
  'Probiona Kulturen Komplex',
  180,
  'Kapseln',
  90,
  2,
  'Kapseln',
  26.99,
  0.30,
  'capsule',
  'Verdauung',
  'DE',
  true,
  true,
  true,
  ARRAY['20 Bakterienstämme', '20 Mrd KBE', 'Bio-Inulin', 'magensaftresistent', 'Made in Germany', 'vegan', 'laborgeprüft'],
  'morning',
  'B06XXGNMHB',
  'https://www.amazon.de/dp/B06XXGNMHB',
  'https://www.nature-love.de/products/probiona-kulturen-komplex-kapseln',
  '20 lebende Bakterienstämme mit Bio-Inulin aus Agave. 20 Mrd. KBE pro Tagesdosis in magensaftresistenten Kapseln. Premium-Rohstoff aus Italien.',
  ARRAY['praebiotika', 'ballaststoffe', 'zink'],
  ARRAY['antibiotika']
);