-- Phase 5 Task 6: Knowledge Taxonomy Topics Import
-- 100+ wissenschaftliche Topics für ARES Coach
-- category_path wird automatisch generiert

-- KATEGORIE 1: PEPTIDE & GLP-1 AGONISTEN

INSERT INTO knowledge_taxonomy (category_level1, category_level2, category_level3, title, description, summary, evidence_level, keywords, synonyms, relevant_bloodwork_markers, is_sensitive, is_active) VALUES

('Peptide', 'GLP-1 Agonisten', 'Semaglutid', 
'Semaglutid (Ozempic/Wegovy)', 
'Semaglutid ist ein GLP-1 Rezeptor-Agonist zur Behandlung von Typ-2-Diabetes und Adipositas. Es verlangsamt die Magenentleerung, reduziert den Appetit und verbessert die Blutzuckerkontrolle.',
'GLP-1 Agonist mit starker Evidenz für Gewichtsverlust (15-17% in STEP-Studien). Wöchentliche Injektion. Häufige Nebenwirkungen: Übelkeit, Verstopfung. Wichtig: langsame Dosissteigerung über 16-20 Wochen.',
'stark', 
ARRAY['semaglutid', 'glp1', 'gewichtsverlust', 'appetit', 'diabetes', 'adipositas', 'injektion'],
ARRAY['ozempic', 'wegovy', 'abnehmspritze', 'wunderspritze', 'abnehm-spritze', 'spritze'],
ARRAY['hba1c', 'fasting_glucose', 'fasting_insulin', 'homa_ir'],
true, true),

('Peptide', 'GLP-1 Agonisten', 'Tirzepatid',
'Tirzepatid (Mounjaro/Zepbound)',
'Tirzepatid ist ein dualer GIP/GLP-1 Rezeptor-Agonist mit stärkerer Wirkung als reine GLP-1 Agonisten. In SURMOUNT-Studien bis zu 22% Gewichtsverlust.',
'Dualer Agonist (GIP + GLP-1) mit bis zu 22% Gewichtsverlust in Studien. Wöchentliche Injektion. Stärkere Wirkung als Semaglutid, aber auch häufiger GI-Nebenwirkungen.',
'stark',
ARRAY['tirzepatid', 'gip', 'glp1', 'gewichtsverlust', 'dual', 'adipositas'],
ARRAY['mounjaro', 'zepbound', 'eli lilly'],
ARRAY['hba1c', 'fasting_glucose', 'fasting_insulin', 'homa_ir', 'triglycerides'],
true, true),

('Peptide', 'GLP-1 Agonisten', 'Retatrutid',
'Retatrutid (Triple-Agonist)',
'Retatrutid ist ein Triple-Agonist (GLP-1/GIP/Glucagon) in Phase-3-Studien. Frühe Daten zeigen bis zu 24% Gewichtsverlust.',
'Triple-Agonist in Entwicklung. Frühe Phase-2-Daten zeigen stärksten Gewichtsverlust aller Peptide (~24%). Noch nicht zugelassen, voraussichtlich 2025/2026.',
'moderat',
ARRAY['retatrutid', 'triple', 'glucagon', 'gip', 'glp1', 'gewichtsverlust'],
ARRAY['triple agonist', 'eli lilly'],
ARRAY['hba1c', 'fasting_glucose', 'triglycerides'],
true, true),

('Peptide', 'Regenerative Peptide', 'BPC-157',
'BPC-157 (Body Protection Compound)',
'BPC-157 ist ein Peptid aus Magensaft mit regenerativen Eigenschaften. Tierstudien zeigen beschleunigte Heilung von Sehnen, Muskeln und Darm.',
'Regeneratives Peptid mit Heilungspotenzial für Sehnen, Muskeln, Darm. Nur Tierstudien verfügbar. Dosierung typisch 250-500mcg/Tag. Subkutan oder oral. Keine Humanstudien!',
'anekdotisch',
ARRAY['bpc157', 'bpc-157', 'heilung', 'regeneration', 'sehnen', 'muskeln', 'darm', 'peptid'],
ARRAY['body protection compound', 'gastric pentadecapeptide'],
ARRAY[]::text[],
true, true),

('Peptide', 'Regenerative Peptide', 'TB-500',
'TB-500 (Thymosin Beta-4)',
'TB-500 ist ein synthetisches Peptid basierend auf Thymosin Beta-4. Es fördert Zellmigration und Angiogenese, was die Geweberegeneration unterstützen kann.',
'Synthetisches Peptid für Regeneration. Fördert Angiogenese und Zellmigration. Dosierung typisch 2-5mg/Woche. Wird oft mit BPC-157 kombiniert. Begrenzte Humanstudien.',
'anekdotisch',
ARRAY['tb500', 'tb-500', 'thymosin', 'regeneration', 'heilung', 'angiogenese'],
ARRAY['thymosin beta 4', 'thymosin beta-4'],
ARRAY[]::text[],
true, true),

('Peptide', 'Wachstumshormon-Peptide', 'CJC-1295',
'CJC-1295 (GHRH-Analogon)',
'CJC-1295 ist ein GHRH-Analogon, das die körpereigene Wachstumshormon-Ausschüttung stimuliert. Mit DAC hat es eine Halbwertszeit von 6-8 Tagen.',
'GHRH-Analogon zur GH-Stimulation. Version mit DAC: 1-2x/Woche. Ohne DAC: täglich dosieren. Erhöht IGF-1 und GH pulsatil. Oft kombiniert mit Ipamorelin oder GHRP-6.',
'moderat',
ARRAY['cjc1295', 'cjc-1295', 'ghrh', 'wachstumshormon', 'gh', 'dac'],
ARRAY['mod grf', 'modified grf'],
ARRAY['igf1'],
true, true),

('Peptide', 'Wachstumshormon-Peptide', 'Ipamorelin',
'Ipamorelin (GHRP)',
'Ipamorelin ist ein selektiver Ghrelin-Mimetikum, das GH-Freisetzung stimuliert ohne signifikante Cortisol- oder Prolaktin-Erhöhung.',
'Selektives GHRP ohne Cortisol/Prolaktin-Anstieg. Dosierung 100-300mcg vor dem Schlafen. Oft mit CJC-1295 kombiniert für synergistischen Effekt. Gut verträglich.',
'moderat',
ARRAY['ipamorelin', 'ghrp', 'wachstumshormon', 'gh', 'ghrelin'],
ARRAY['ipam'],
ARRAY['igf1', 'cortisol', 'prolactin'],
true, true),

('Peptide', 'Wachstumshormon-Peptide', 'Tesamorelin',
'Tesamorelin (Egrifta)',
'Tesamorelin ist ein FDA-zugelassenes GHRH-Analogon zur Reduktion von viszeralem Fett bei HIV-Lipodystrophie.',
'FDA-zugelassenes GHRH-Analogon. Reduziert viszerales Fett um 15-20% in Studien. Täglich 2mg subkutan. Teuer aber legal verfügbar. Erhöht IGF-1 um 50-100%.',
'stark',
ARRAY['tesamorelin', 'ghrh', 'viszerales fett', 'lipodystrophie', 'anti-aging'],
ARRAY['egrifta', 'theratechnologies'],
ARRAY['igf1'],
true, true),

('Peptide', 'Wachstumshormon-Peptide', 'MK-677',
'MK-677 (Ibutamoren)',
'MK-677 ist ein oraler Ghrelin-Mimetikum, der die GH-Sekretion erhöht. Keine Injektion nötig, aber kann Appetit und Blutzucker erhöhen.',
'Oraler GH-Secretagogue. 10-25mg täglich. Erhöht IGF-1 um 40-80%. Nebenwirkungen: erhöhter Appetit, Wassereinlagerung, leichte Blutzucker-Erhöhung.',
'moderat',
ARRAY['mk677', 'mk-677', 'ibutamoren', 'ghrelin', 'wachstumshormon', 'oral'],
ARRAY['nutrobal'],
ARRAY['igf1', 'fasting_glucose', 'fasting_insulin'],
true, true),

('Peptide', 'Melanocortin-Peptide', 'Melanotan II',
'Melanotan II (MT2)',
'Melanotan II ist ein Melanocortin-Analogon, das Bräunung ohne UV-Exposition fördert. Hat auch libido-steigernde Wirkung.',
'Melanocortin-Peptid für Bräunung ohne Sonne. Nebenwirkungen: Übelkeit, Gesichtsrötung, erhöhte Libido, Muttermale können dunkler werden. Nicht zugelassen.',
'anekdotisch',
ARRAY['melanotan', 'mt2', 'bräunung', 'melanin', 'libido'],
ARRAY['melanotan 2', 'melanotan ii', 'barbie drug'],
ARRAY[]::text[],
true, true);

-- KATEGORIE 2: HORMONE

INSERT INTO knowledge_taxonomy (category_level1, category_level2, category_level3, title, description, summary, evidence_level, keywords, synonyms, relevant_bloodwork_markers, is_sensitive, is_active) VALUES

('Hormone', 'Androgene', 'Testosteron',
'Testosteron-Optimierung (Männer)',
'Testosteron ist das wichtigste männliche Sexualhormon. Optimale Werte fördern Muskelmasse, Libido, Energie und kognitive Funktion.',
'Referenz: 300-1000 ng/dL, optimal 500-800. Natürliche Optimierung: Schlaf, Krafttraining, Stressreduktion, Zink, Vitamin D. TRT-Indikation bei <300 ng/dL mit Symptomen.',
'stark',
ARRAY['testosteron', 'testo', 'androgen', 'hypogonadismus', 'libido', 'muskeln', 'kraft'],
ARRAY['testo', 'test', 'männlichkeit', 'potenz'],
ARRAY['total_testosterone', 'free_testosterone', 'shbg', 'lh', 'fsh', 'estradiol'],
true, true),

('Hormone', 'Androgene', 'TRT',
'Testosteron-Ersatztherapie (TRT)',
'TRT ist die medizinische Behandlung von Hypogonadismus mit exogenem Testosteron. Verschiedene Darreichungsformen verfügbar.',
'Indikation: Testosteron <300 ng/dL + Symptome. Formen: Gel (täglich), Injektion (1-2x/Woche), Pellets (alle 3-6 Monate). Monitoring: Testosteron, Estradiol, Hämatokrit, PSA.',
'stark',
ARRAY['trt', 'testosteron', 'ersatztherapie', 'hypogonadismus', 'injektion', 'gel'],
ARRAY['hormonersatz', 'testosteron therapie', 'nebido', 'testogel'],
ARRAY['total_testosterone', 'free_testosterone', 'estradiol', 'hematocrit', 'psa', 'hemoglobin'],
true, true),

('Hormone', 'Östrogene', 'Estradiol Männer',
'Estradiol-Management bei Männern',
'Estradiol ist auch bei Männern wichtig für Knochen, Libido und Gehirnfunktion. Zu hoch oder zu niedrig ist problematisch.',
'Optimal: 20-35 pg/mL. Zu hoch (>50): Gynäkomastie, Wassereinlagerung. Zu niedrig (<15): Gelenkschmerzen, niedrige Libido. AI (Anastrozol) nur bei Bedarf.',
'stark',
ARRAY['estradiol', 'östrogen', 'aromatase', 'gynäkomastie', 'e2'],
ARRAY['e2', 'östrogenüberschuss', 'aromatasehemmer'],
ARRAY['estradiol', 'total_testosterone', 'shbg'],
true, true),

('Hormone', 'Bindungsproteine', 'SHBG',
'SHBG (Sexualhormon-bindendes Globulin)',
'SHBG bindet Testosteron und Estradiol im Blut. Hohe Werte reduzieren freies Testosteron, niedrige erhöhen es.',
'Referenz: 10-57 nmol/L. Erhöht durch: Hyperthyreose, Alter, Östrogene. Erniedrigt durch: Adipositas, Insulin, Androgene.',
'stark',
ARRAY['shbg', 'globulin', 'testosteron', 'bindung', 'frei'],
ARRAY['sexualhormon-bindendes globulin'],
ARRAY['shbg', 'total_testosterone', 'free_testosterone'],
false, true),

('Hormone', 'Schilddrüsenhormone', 'Schilddrüse',
'Schilddrüsenoptimierung',
'Die Schilddrüse reguliert den Stoffwechsel. Suboptimale Werte verursachen Müdigkeit, Gewichtsprobleme und kognitive Einschränkungen.',
'Optimal: TSH 0.5-2.0 mU/L, fT3 oberes Drittel, fT4 Mitte. Subklinische Hypothyreose: TSH 4-10 bei normalen fT3/fT4. Häufig: Jodmangel, Hashimoto.',
'stark',
ARRAY['schilddrüse', 'tsh', 'ft3', 'ft4', 'hypothyreose', 'stoffwechsel', 'müdigkeit'],
ARRAY['thyroid', 'hashimoto', 'unterfunktion'],
ARRAY['tsh', 'ft3', 'ft4'],
false, true),

('Hormone', 'Nebennierenhormone', 'Cortisol',
'Cortisol und Stressmanagement',
'Cortisol ist das Hauptstresshormon. Chronisch erhöhte Werte fördern Bauchfett, Muskelabbau und Immunschwäche.',
'Morgen-Cortisol: 10-20 µg/dL optimal. Chronisch erhöht: Bauchfett, Schlafstörungen, Immunschwäche. Senkung: Schlaf, Meditation, Adaptogene.',
'stark',
ARRAY['cortisol', 'stress', 'nebenniere', 'bauchfett', 'katabol'],
ARRAY['stresshormon', 'hydrocortison'],
ARRAY['cortisol', 'dhea_s'],
false, true),

('Hormone', 'Nebennierenhormone', 'DHEA-S',
'DHEA-S und Anti-Aging',
'DHEA-S ist ein Vorläuferhormon, das zu Testosteron und Östrogen umgewandelt wird. Sinkt mit dem Alter.',
'Peak mit 25-30, dann -2% pro Jahr. Niedrige Werte: Müdigkeit, geringe Stressresistenz. Supplementierung: 25-50mg/Tag.',
'moderat',
ARRAY['dhea', 'dheas', 'dhea-s', 'nebenniere', 'anti-aging', 'vorläufer'],
ARRAY['dehydroepiandrosteron'],
ARRAY['dhea_s', 'total_testosterone', 'estradiol'],
true, true),

('Hormone', 'Hypophysenhormone', 'Prolaktin',
'Prolaktin bei Männern',
'Erhöhtes Prolaktin bei Männern kann Libido, Erektionsfähigkeit und Testosteron senken. Ursachen: Stress, Medikamente, Tumor.',
'Normal: <15 ng/mL. Erhöht: Libidoverlust, erektile Dysfunktion, Gynäkomastie. Senkung: Vitamin B6, Vitamin E, Cabergolin.',
'stark',
ARRAY['prolaktin', 'libido', 'erektion', 'gynäkomastie', 'hypophyse'],
ARRAY['prl'],
ARRAY['prolactin', 'total_testosterone', 'lh'],
true, true),

('Hormone', 'Wachstumshormon', 'GH-IGF1',
'Wachstumshormon-Optimierung',
'GH und IGF-1 fördern Muskelaufbau, Fettabbau und Regeneration. Produktion sinkt mit dem Alter (Somatopause).',
'IGF-1 als Marker für GH-Status. Optimal: oberes Drittel für Alter. Natürliche Steigerung: Schlaf, Fasten, intensives Training.',
'stark',
ARRAY['wachstumshormon', 'gh', 'igf1', 'igf-1', 'regeneration', 'anti-aging'],
ARRAY['growth hormone', 'somatotropin', 'hgh'],
ARRAY['igf1'],
true, true),

('Hormone', 'Pankreashormone', 'Insulin',
'Insulinsensitivität optimieren',
'Insulinresistenz ist Vorstufe von Diabetes und fördert Fetteinlagerung. HOMA-IR ist der Goldstandard zur Messung.',
'HOMA-IR <1.0 optimal, >2.5 Insulinresistenz. Verbesserung: Krafttraining, Intervallfasten, Low-Carb, Berberine, Metformin.',
'stark',
ARRAY['insulin', 'insulinresistenz', 'homa', 'diabetes', 'blutzucker', 'sensitivität'],
ARRAY['homa-ir', 'nüchterninsulin'],
ARRAY['fasting_insulin', 'fasting_glucose', 'homa_ir', 'hba1c'],
false, true);

-- KATEGORIE 3: SUPPLEMENTS

INSERT INTO knowledge_taxonomy (category_level1, category_level2, category_level3, title, description, summary, evidence_level, keywords, synonyms, relevant_bloodwork_markers, is_sensitive, is_active) VALUES

('Supplements', 'Leistung', 'Kreatin',
'Kreatin-Monohydrat',
'Kreatin ist das am besten erforschte Supplement für Kraft und Muskelmasse. Es erhöht ATP-Regeneration und Zellhydratation.',
'5g/Tag Kreatin-Monohydrat, keine Ladephase nötig. Steigert Kraft um 5-10%, fördert Muskelmasse und kognitive Funktion.',
'stark',
ARRAY['kreatin', 'creatine', 'kraft', 'muskeln', 'atp', 'monohydrat'],
ARRAY['creatine monohydrate', 'creatin'],
ARRAY['creatinine'],
false, true),

('Supplements', 'Vitamine', 'Vitamin D',
'Vitamin D3 Supplementierung',
'Vitamin D ist eigentlich ein Hormon. Mangel ist weit verbreitet und beeinflusst Immunsystem, Muskeln, Knochen und Stimmung.',
'Zielwert: 40-60 ng/mL. Dosierung: 2000-5000 IE/Tag, bei Mangel initial höher. Mit Vitamin K2 kombinieren.',
'stark',
ARRAY['vitamin d', 'd3', 'cholecalciferol', 'sonne', 'knochen', 'immunsystem'],
ARRAY['vitamin d3', 'sonnenvitamin'],
ARRAY['vitamin_d'],
false, true),

('Supplements', 'Mineralstoffe', 'Magnesium',
'Magnesium-Supplementierung',
'Magnesium ist an über 300 Enzymreaktionen beteiligt. Mangel ist häufig und verursacht Krämpfe, Schlafstörungen und Stress.',
'RDA 400-420mg/Tag (Männer). Formen: Glycinat (Schlaf), Citrat (Verdauung), Threonat (Gehirn). Abends einnehmen.',
'stark',
ARRAY['magnesium', 'mineral', 'schlaf', 'krämpfe', 'stress', 'entspannung'],
ARRAY['mg', 'magnesiumcitrat', 'magnesiumglycinat'],
ARRAY['magnesium'],
false, true),

('Supplements', 'Mineralstoffe', 'Zink',
'Zink für Testosteron und Immunsystem',
'Zink ist essentiell für Testosteronsynthese, Immunfunktion und Wundheilung. Verlust durch Schweiß beim Training.',
'RDA 11mg/Tag, Athleten 25-45mg. Formen: Picolinat, Citrat gut bioverfügbar. Nicht mit Eisen kombinieren.',
'stark',
ARRAY['zink', 'testosteron', 'immunsystem', 'heilung', 'mineral'],
ARRAY['zinc', 'zn'],
ARRAY['zinc', 'total_testosterone'],
false, true),

('Supplements', 'Fettsäuren', 'Omega-3',
'Omega-3 Fettsäuren (EPA/DHA)',
'Omega-3 reduziert Entzündungen, unterstützt Herzgesundheit und Gehirnfunktion. Die meisten Menschen sind unterversorgt.',
'Mindestens 2g EPA+DHA/Tag. Verhältnis EPA:DHA 2:1 für Entzündungshemmung. Omega-3 Index >8% anstreben.',
'stark',
ARRAY['omega3', 'omega-3', 'fischöl', 'epa', 'dha', 'entzündung', 'herz'],
ARRAY['fish oil', 'fischoel', 'algenöl'],
ARRAY['crp', 'triglycerides'],
false, true),

('Supplements', 'Vitamine', 'Vitamin B12',
'Vitamin B12 Supplementierung',
'B12 ist essentiell für Nervenfunktion und Blutbildung. Mangel häufig bei Veganern, Älteren und PPI-Nutzern.',
'Zielwert: >500 pg/mL. Formen: Methylcobalamin bevorzugt. Dosierung: 1000-2000µg sublingual oder Injektion bei Mangel.',
'stark',
ARRAY['b12', 'vitamin b12', 'cobalamin', 'nerven', 'blutbildung', 'vegan'],
ARRAY['methylcobalamin', 'cyanocobalamin'],
ARRAY['vitamin_b12', 'hemoglobin', 'rbc'],
false, true),

('Supplements', 'Mineralstoffe', 'Eisen',
'Eisen und Ferritin-Optimierung',
'Eisen ist essentiell für Sauerstofftransport und Energie. Mangel häufig bei Frauen und Ausdauersportlern.',
'Ferritin optimal: 100-150 ng/mL. Bei Mangel: Eisen-Bisglycinat mit Vitamin C. Nicht bei Hämochromatose.',
'stark',
ARRAY['eisen', 'ferritin', 'anämie', 'müdigkeit', 'blutarmut', 'sauerstoff'],
ARRAY['iron', 'fe', 'eisenmangel'],
ARRAY['ferritin', 'iron', 'hemoglobin', 'hematocrit'],
false, true),

('Supplements', 'Adaptogene', 'Ashwagandha',
'Ashwagandha (KSM-66)',
'Ashwagandha ist ein Adaptogen, das Cortisol senkt, Stress reduziert und möglicherweise Testosteron leicht erhöht.',
'Dosierung: 300-600mg KSM-66 Extrakt täglich. Cortisol-Senkung um 25% in Studien. Testosteron-Erhöhung um 15% möglich.',
'moderat',
ARRAY['ashwagandha', 'ksm66', 'ksm-66', 'adaptogen', 'stress', 'cortisol'],
ARRAY['withania somnifera', 'schlafbeere', 'indian ginseng'],
ARRAY['cortisol', 'total_testosterone', 'tsh'],
false, true),

('Supplements', 'Testosteron-Booster', 'Tongkat Ali',
'Tongkat Ali (Eurycoma longifolia)',
'Tongkat Ali kann freies Testosteron erhöhen, indem es SHBG senkt. Auch ergogene Effekte möglich.',
'Dosierung: 200-400mg standardisierter Extrakt. Kann SHBG um 30% senken. Freies Testosteron steigt proportional.',
'moderat',
ARRAY['tongkat', 'tongkat ali', 'testosteron', 'shbg', 'libido', 'energie'],
ARRAY['eurycoma longifolia', 'longjack', 'malaysian ginseng'],
ARRAY['total_testosterone', 'free_testosterone', 'shbg'],
true, true),

('Supplements', 'Testosteron-Booster', 'Fadogia Agrestis',
'Fadogia Agrestis',
'Fadogia kann LH erhöhen und damit die körpereigene Testosteronproduktion steigern. Begrenzte Humanstudien.',
'Dosierung: 400-600mg/Tag. Wirkmechanismus: LH-Steigerung. Tierstudien zeigten Testosteron-Erhöhung. Zyklen empfohlen.',
'anekdotisch',
ARRAY['fadogia', 'fadogia agrestis', 'testosteron', 'lh', 'booster'],
ARRAY['bauchi'],
ARRAY['lh', 'total_testosterone'],
true, true),

('Supplements', 'Stoffwechsel', 'Berberin',
'Berberin für Blutzuckerkontrolle',
'Berberin aktiviert AMPK ähnlich wie Metformin und verbessert Insulinsensitivität und Blutfette.',
'Dosierung: 500mg 2-3x täglich vor Mahlzeiten. Senkt HbA1c um 0.5-1%. Verbessert Lipidprofil.',
'stark',
ARRAY['berberin', 'berberine', 'blutzucker', 'insulin', 'ampk', 'stoffwechsel'],
ARRAY['berberine hcl', 'goldenseal'],
ARRAY['fasting_glucose', 'fasting_insulin', 'hba1c', 'homa_ir', 'ldl', 'triglycerides'],
false, true),

('Supplements', 'Antioxidantien', 'NAC',
'N-Acetyl-Cystein (NAC)',
'NAC ist Vorläufer von Glutathion, dem wichtigsten körpereigenen Antioxidans. Unterstützt Leber und Atemwege.',
'Dosierung: 600-1200mg/Tag. Erhöht Glutathion um 30%. Leberschutz, Schleimlösung, mentale Klarheit.',
'stark',
ARRAY['nac', 'acetylcystein', 'glutathion', 'leber', 'antioxidans', 'entgiftung'],
ARRAY['n-acetyl cysteine', 'acetylcysteine'],
ARRAY['alt', 'ast', 'ggt'],
false, true),

('Supplements', 'Aminosäuren', 'Taurin',
'Taurin für Langlebigkeit',
'Taurin ist eine bedingt essentielle Aminosäure. Neue Forschung zeigt Zusammenhang mit Langlebigkeit und Herzgesundheit.',
'Dosierung: 1-3g/Tag. Science-Paper 2023: Taurin-Mangel beschleunigt Alterung. Unterstützt Herz, Augen, Gehirn.',
'moderat',
ARRAY['taurin', 'taurine', 'langlebigkeit', 'herz', 'aminosäure', 'anti-aging'],
ARRAY['2-aminoethansulfonsäure'],
ARRAY[]::text[],
false, true),

('Supplements', 'Aminosäuren', 'Glycin',
'Glycin für Schlaf und Kollagen',
'Glycin verbessert Schlafqualität, unterstützt Kollagensynthese und hat anti-inflammatorische Eigenschaften.',
'Dosierung: 3-5g vor dem Schlafen. Verbessert Schlafqualität und Tiefschlaf. Baustein für Kollagen und Glutathion.',
'moderat',
ARRAY['glycin', 'glycine', 'schlaf', 'kollagen', 'aminosäure'],
ARRAY['aminoessigsäure'],
ARRAY[]::text[],
false, true),

('Supplements', 'Proteine', 'Kollagen',
'Kollagen-Supplementierung',
'Kollagen unterstützt Haut, Gelenke, Sehnen und Darm. Hydrolysat wird besser absorbiert.',
'Dosierung: 10-15g hydrolysiertes Kollagen täglich. Typ I/III für Haut, Typ II für Gelenke. Mit Vitamin C kombinieren.',
'moderat',
ARRAY['kollagen', 'collagen', 'haut', 'gelenke', 'sehnen', 'bindegewebe'],
ARRAY['collagen peptides', 'hydrolyzed collagen'],
ARRAY[]::text[],
false, true);

-- KATEGORIE 4: ERNÄHRUNG

INSERT INTO knowledge_taxonomy (category_level1, category_level2, category_level3, title, description, summary, evidence_level, keywords, synonyms, relevant_bloodwork_markers, is_sensitive, is_active) VALUES

('Ernährung', 'Makronährstoffe', 'Protein',
'Optimaler Proteinbedarf',
'Proteinbedarf hängt von Aktivitätslevel und Zielen ab. Die meisten Menschen essen zu wenig Protein.',
'Minimum: 1.6g/kg, optimal 2.0-2.4g/kg für Muskelaufbau. Über 50 Jahre: höherer Bedarf. Gleichmäßig auf Mahlzeiten verteilen.',
'stark',
ARRAY['protein', 'eiweiß', 'aminosäuren', 'muskelaufbau', 'bedarf'],
ARRAY['eiweiss', 'proteinbedarf'],
ARRAY['albumin', 'creatinine'],
false, true),

('Ernährung', 'Gewichtsmanagement', 'Kaloriendefizit',
'Kaloriendefizit für Fettabbau',
'Ein kontrolliertes Kaloriendefizit ist die Grundlage für Fettabbau. Zu aggressives Defizit kann Muskelverlust verursachen.',
'Empfohlen: 300-500 kcal Defizit = 0.3-0.5kg/Woche Fettabbau. Protein hochhalten (2g/kg). Krafttraining beibehalten.',
'stark',
ARRAY['kaloriendefizit', 'abnehmen', 'fettabbau', 'diät', 'gewichtsverlust'],
ARRAY['deficit', 'kalorienmangel'],
ARRAY[]::text[],
false, true),

('Ernährung', 'Fastenprotokolle', 'Intervallfasten',
'Intervallfasten (16:8, OMAD)',
'Intervallfasten verbessert Insulinsensitivität und kann Autophagie fördern. Verschiedene Protokolle verfügbar.',
'16:8: 16h fasten, 8h essen. OMAD: eine Mahlzeit/Tag. Vorteile: bessere Insulinsensitivität, einfacheres Kaloriendefizit.',
'moderat',
ARRAY['intervallfasten', 'fasten', 'autophagie', 'insulin', 'omad'],
ARRAY['intermittent fasting', 'if', '16:8', 'one meal a day'],
ARRAY['fasting_glucose', 'fasting_insulin', 'homa_ir'],
false, true),

('Ernährung', 'Diätformen', 'Keto',
'Ketogene Diät',
'Die ketogene Diät nutzt Fett statt Kohlenhydrate als Hauptenergiequelle. Der Körper produziert Ketonkörper.',
'<50g Kohlenhydrate/Tag für Ketose. Vorteile: stabiler Blutzucker, Appetitreduktion. Nachteile: Anfangsphase schwierig.',
'moderat',
ARRAY['keto', 'ketogen', 'ketose', 'kohlenhydrate', 'fett', 'ketone'],
ARRAY['ketogenic', 'low carb', 'lchf'],
ARRAY['fasting_glucose', 'fasting_insulin', 'triglycerides', 'hdl', 'ldl'],
false, true),

('Ernährung', 'Nährstoff-Timing', 'Carb-Timing',
'Kohlenhydrat-Timing',
'Strategisches Carb-Timing kann Training und Regeneration optimieren. Vor/nach Training sind Kohlenhydrate besonders nützlich.',
'Pre-Workout: 30-60g Carbs 1-2h vorher. Post-Workout: 0.5-1g/kg in 2h nach Training. Insulin-Spike fördert Nährstoffaufnahme.',
'moderat',
ARRAY['kohlenhydrate', 'carbs', 'timing', 'training', 'insulin'],
ARRAY['carb timing', 'nutrient timing'],
ARRAY['fasting_glucose', 'fasting_insulin'],
false, true),

('Ernährung', 'Darmgesundheit', 'Mikrobiom',
'Darm-Mikrobiom optimieren',
'Ein gesundes Mikrobiom beeinflusst Immunsystem, Stimmung, Stoffwechsel und Gewicht.',
'Diversität fördern: 30+ Pflanzenarten/Woche. Fermentierte Lebensmittel täglich. Ballaststoffe 25-35g/Tag.',
'stark',
ARRAY['mikrobiom', 'darm', 'probiotika', 'ballaststoffe', 'fermentiert'],
ARRAY['gut health', 'darmflora', 'microbiome'],
ARRAY['crp'],
false, true),

('Ernährung', 'Genussmittel', 'Alkohol',
'Alkohol und Körperkomposition',
'Alkohol hemmt Fettverbrennung, Proteinsynthese und Testosteronproduktion. Jeder Drink hat Auswirkungen.',
'Alkohol hemmt Fettoxidation für 12-24h. Senkt Testosteron akut um 20%. Leere Kalorien ohne Nährwert.',
'stark',
ARRAY['alkohol', 'wein', 'bier', 'testosteron', 'fettabbau', 'leber'],
ARRAY['alcohol', 'spirituosen'],
ARRAY['alt', 'ast', 'ggt', 'total_testosterone', 'triglycerides'],
false, true),

('Ernährung', 'Genussmittel', 'Koffein',
'Koffein als Ergogenik',
'Koffein steigert Leistung, Fettoxidation und Fokus. Aber Timing und Dosierung sind wichtig.',
'3-6mg/kg Körpergewicht 30-60min vor Training. Halbwertszeit 5-6h - letzter Konsum 10h vor Schlaf.',
'stark',
ARRAY['koffein', 'kaffee', 'energie', 'leistung', 'fokus', 'schlaf'],
ARRAY['caffeine', 'coffee'],
ARRAY['cortisol'],
false, true);

-- KATEGORIE 5: TRAINING

INSERT INTO knowledge_taxonomy (category_level1, category_level2, category_level3, title, description, summary, evidence_level, keywords, synonyms, relevant_bloodwork_markers, is_sensitive, is_active) VALUES

('Training', 'Prinzipien', 'Progressive Overload',
'Progressive Überlastung',
'Progressive Overload ist das fundamentale Prinzip für Muskelaufbau. Ohne kontinuierliche Steigerung kein Wachstum.',
'Steigerung via: Gewicht, Wiederholungen, Sätze, ROM, TUT. Logbuch führen! Wöchentliche Progression realistisch.',
'stark',
ARRAY['progressive overload', 'progression', 'steigerung', 'muskelaufbau', 'kraft'],
ARRAY['überlastung', 'progressiv'],
ARRAY[]::text[],
false, true),

('Training', 'Programmierung', 'Volumen',
'Optimales Trainingsvolumen',
'Volumen ist Haupttreiber für Hypertrophie. Aber mehr ist nicht immer besser.',
'10-20 Sätze pro Muskelgruppe pro Woche. Anfänger: untere Grenze. Fortgeschrittene: obere Grenze. Qualität vor Quantität.',
'stark',
ARRAY['volumen', 'sätze', 'wiederholungen', 'hypertrophie', 'muskelaufbau'],
ARRAY['training volume', 'sets'],
ARRAY[]::text[],
false, true),

('Training', 'Erholung', 'Regeneration',
'Regeneration und Supercompensation',
'Muskeln wachsen in der Erholung, nicht im Training. Ohne adäquate Regeneration kein Fortschritt.',
'48-72h zwischen Training derselben Muskelgruppe. Schlaf 7-9h essenziell. Übertraining vermeiden.',
'stark',
ARRAY['regeneration', 'erholung', 'schlaf', 'übertraining', 'pause'],
ARRAY['recovery', 'supercompensation'],
ARRAY['cortisol', 'crp'],
false, true),

('Training', 'Intensitätssteuerung', 'RPE',
'RPE-basiertes Training',
'RPE (Rate of Perceived Exertion) ermöglicht autoreguliertes Training basierend auf Tagesform.',
'RPE 6-7: 3-4 Reps in Reserve. RPE 8-9: 1-2 RIR. RPE 10: Muskelversagen. Meiste Sätze bei RPE 7-8.',
'moderat',
ARRAY['rpe', 'intensität', 'autoregulation', 'gefühl', 'anstrengung'],
ARRAY['rate of perceived exertion', 'reps in reserve', 'rir'],
ARRAY[]::text[],
false, true),

('Training', 'Übungsauswahl', 'Grundübungen',
'Compound-Übungen (Grundübungen)',
'Mehrgelenkübungen trainieren mehr Muskelmasse pro Zeiteinheit und ermöglichen höhere Lasten.',
'Priorität: Kniebeuge, Kreuzheben, Bankdrücken, Rudern, Schulterdrücken, Klimmzüge. Diese 6 Übungen decken 80% des Trainingseffekts.',
'stark',
ARRAY['compound', 'grundübungen', 'kniebeuge', 'kreuzheben', 'bankdrücken'],
ARRAY['mehrgelenkübungen', 'big lifts'],
ARRAY[]::text[],
false, true),

('Training', 'Ausdauer', 'Cardio',
'Cardio für Körperkomposition',
'Cardio kann Fettabbau unterstützen, aber zu viel interferiert mit Muskelaufbau.',
'LISS: 2-4x/Woche 20-45min. HIIT: 1-2x/Woche. Cardio nach Krafttraining oder an separaten Tagen.',
'stark',
ARRAY['cardio', 'ausdauer', 'fettabbau', 'liss', 'hiit', 'herz'],
ARRAY['kardio', 'ausdauertraining', 'laufen'],
ARRAY['hdl', 'triglycerides'],
false, true),

('Training', 'Periodisierung', 'Deload',
'Deload-Wochen',
'Geplante Entlastungswochen ermöglichen Erholung und beugen Übertraining vor.',
'Alle 4-8 Wochen eine Deload-Woche: 50% Volumen oder 50% Intensität. Nicht beide reduzieren.',
'moderat',
ARRAY['deload', 'entlastung', 'periodisierung', 'erholung', 'plateau'],
ARRAY['entlastungswoche', 'recovery week'],
ARRAY[]::text[],
false, true),

('Training', 'Technik', 'Mind-Muscle',
'Mind-Muscle Connection',
'Bewusste Muskelansteuerung kann Hypertrophie verbessern, besonders bei Isolationsübungen.',
'Fokus auf Kontraktion des Zielmuskels. Langsamere Exzentrik (3-4 Sek). Weniger relevant bei schweren Compounds.',
'moderat',
ARRAY['mind-muscle', 'verbindung', 'ansteuerung', 'kontrolle', 'fokus'],
ARRAY['muscle connection', 'bewusste kontraktion'],
ARRAY[]::text[],
false, true);

-- KATEGORIE 6: LONGEVITY

INSERT INTO knowledge_taxonomy (category_level1, category_level2, category_level3, title, description, summary, evidence_level, keywords, synonyms, relevant_bloodwork_markers, is_sensitive, is_active) VALUES

('Longevity', 'Grundlagen', 'Hallmarks',
'Hallmarks of Aging',
'Die Wissenschaft hat 12 Kennzeichen des Alterns identifiziert, die therapeutisch adressierbar sind.',
'Hallmarks: Genomische Instabilität, Telomer-Verkürzung, Epigenetische Veränderungen, Mitochondriale Dysfunktion, Zelluläre Seneszenz.',
'stark',
ARRAY['aging', 'altern', 'hallmarks', 'langlebigkeit', 'anti-aging'],
ARRAY['alterung', 'kennzeichen'],
ARRAY[]::text[],
false, true),

('Longevity', 'Interventionen', 'Rapamycin',
'Rapamycin und mTOR-Hemmung',
'Rapamycin hemmt mTOR und ist das einzige Medikament, das in Säugetieren konsistent Lebensspanne verlängert.',
'Wirkmechanismus: mTOR-Hemmung aktiviert Autophagie. Dosierung für Longevity: 5-6mg 1x/Woche. Off-label Anwendung.',
'moderat',
ARRAY['rapamycin', 'mtor', 'sirolimus', 'autophagie', 'langlebigkeit'],
ARRAY['sirolimus', 'rapa'],
ARRAY['ldl', 'triglycerides', 'fasting_glucose'],
true, true),

('Longevity', 'Interventionen', 'Metformin',
'Metformin für Langlebigkeit',
'Metformin aktiviert AMPK und wird als potenzielles Anti-Aging-Medikament untersucht (TAME-Studie).',
'Standard-Diabetes-Medikament mit potenziellem Longevity-Benefit. 500-1500mg/Tag. Kann Muskelaufbau beeinträchtigen.',
'moderat',
ARRAY['metformin', 'ampk', 'blutzucker', 'langlebigkeit', 'diabetes'],
ARRAY['glucophage'],
ARRAY['fasting_glucose', 'hba1c', 'vitamin_b12'],
true, true),

('Longevity', 'Supplements', 'NAD+',
'NAD+ und NMN Supplementierung',
'NAD+ sinkt mit dem Alter. Vorläufer wie NMN oder NR können NAD+ erhöhen.',
'NMN: 500-1000mg/Tag. NR: 300-500mg/Tag. Erhöht NAD+ um 40-50%. Theoretischer Benefit für Energie und Alterung.',
'moderat',
ARRAY['nad', 'nmn', 'nr', 'nicotinamid', 'energie', 'mitochondrien'],
ARRAY['nicotinamide mononucleotide', 'nicotinamide riboside'],
ARRAY[]::text[],
true, true),

('Longevity', 'Interventionen', 'Senolytics',
'Senolytika (Seneszente Zellen)',
'Senolytika eliminieren seneszente Zombie-Zellen, die Entzündung und Alterung fördern.',
'Senolytika: Dasatinib + Quercetin, Fisetin. Protokoll: wenige Tage/Monat, nicht kontinuierlich.',
'anekdotisch',
ARRAY['senolytika', 'senolytics', 'seneszenz', 'zombie', 'zellen', 'fisetin'],
ARRAY['senescent cells', 'd+q'],
ARRAY['crp'],
true, true),

('Longevity', 'Biomarker', 'Telomere',
'Telomerlänge und biologisches Alter',
'Telomere schützen DNA-Enden und verkürzen sich mit jeder Zellteilung. Ein Biomarker für biologisches Alter.',
'Telomerlänge korreliert mit biologischem Alter. Lifestyle beeinflusst Verkürzungsrate: Bewegung/Meditation verlangsamt.',
'stark',
ARRAY['telomere', 'telomerase', 'alterung', 'dna', 'biologisches alter'],
ARRAY['telomerlänge'],
ARRAY[]::text[],
false, true),

('Longevity', 'Biomarker', 'Biologisches Alter',
'Biologisches Alter messen',
'Das biologische Alter kann vom chronologischen abweichen. Epigenetische Uhren sind der Goldstandard zur Messung.',
'Epigenetische Uhren (Horvath, GrimAge) messen DNA-Methylierung. Blutmarker: hsCRP, HbA1c, Lipide als Proxy-Marker.',
'stark',
ARRAY['biologisches alter', 'epigenetik', 'horvath', 'methylierung', 'biomarker'],
ARRAY['biological age', 'epigenetic clock'],
ARRAY['crp', 'hba1c', 'ldl', 'hdl', 'triglycerides'],
false, true),

('Longevity', 'Lifestyle', 'Blue Zones',
'Blue Zones Lebensstil',
'Blue Zones sind Regionen mit überdurchschnittlich vielen Hundertjährigen. Gemeinsame Lifestyle-Faktoren identifiziert.',
'9 Prinzipien: natürliche Bewegung, Purpose, Stressabbau, 80%-Regel, pflanzenbasiert, Gemeinschaft, Familie.',
'stark',
ARRAY['blue zones', 'langlebigkeit', 'lifestyle', 'hundertjährige', 'okinawa'],
ARRAY['centenarians', 'longevity'],
ARRAY[]::text[],
false, true);

-- KATEGORIE 7: BLUTWERTE-INTERPRETATION

INSERT INTO knowledge_taxonomy (category_level1, category_level2, category_level3, title, description, summary, evidence_level, keywords, synonyms, relevant_bloodwork_markers, is_sensitive, is_active) VALUES

('Blutwerte', 'Lipide', 'Lipidprofil',
'Lipidprofil interpretieren',
'Cholesterin-Werte sind komplexer als nur LDL. Triglyzeride/HDL-Ratio und ApoB sind aussagekräftiger.',
'Optimal: TG/HDL <2, LDL <100, HDL >50 (Männer), ApoB <80. Hohe LDL allein nicht aussagekräftig.',
'stark',
ARRAY['cholesterin', 'ldl', 'hdl', 'triglyzeride', 'lipide', 'apoB'],
ARRAY['cholesterol', 'blutfette'],
ARRAY['total_cholesterol', 'ldl', 'hdl', 'triglycerides'],
false, true),

('Blutwerte', 'Entzündung', 'CRP',
'Entzündungsmarker (hsCRP, Homocystein)',
'Chronische niedriggradige Entzündung ist Treiber vieler Erkrankungen. hsCRP und Homocystein sind Schlüsselmarker.',
'hsCRP optimal <1 mg/L. Homocystein <10 µmol/L. Erhöht durch: viszerales Fett, Schlafmangel, Stress.',
'stark',
ARRAY['crp', 'hscrp', 'homocystein', 'entzündung', 'inflammation'],
ARRAY['c-reaktives protein', 'hochsensitives crp'],
ARRAY['crp', 'homocysteine'],
false, true),

('Blutwerte', 'Organfunktion', 'Leber',
'Leberwerte interpretieren',
'ALT, AST und GGT zeigen Leberfunktion und können früh auf Probleme hinweisen.',
'ALT und AST optimal <30. GGT optimal <30. Erhöht durch: Alkohol, Medikamente, Fettleber, Übergewicht.',
'stark',
ARRAY['leberwerte', 'alt', 'ast', 'ggt', 'leber', 'fettleber'],
ARRAY['gpt', 'got', 'gamma-gt', 'transaminasen'],
ARRAY['alt', 'ast', 'ggt', 'albumin'],
false, true),

('Blutwerte', 'Organfunktion', 'Niere',
'Nierenwerte interpretieren',
'Kreatinin und eGFR zeigen Nierenfunktion. Wichtig bei hoher Proteinzufuhr oder Supplementierung.',
'eGFR >90 = normale Funktion. Kreatinin kann bei hoher Muskelmasse erhöht sein ohne Nierenprobleme.',
'stark',
ARRAY['niere', 'kreatinin', 'egfr', 'nierenfunktion', 'protein'],
ARRAY['creatinine', 'kidney'],
ARRAY['creatinine', 'egfr'],
false, true),

('Blutwerte', 'Hämatologie', 'Blutbild',
'Großes Blutbild verstehen',
'Das Blutbild zeigt rote und weiße Blutkörperchen, Hämoglobin und Thrombozyten.',
'Hämoglobin optimal: Männer 14-17, Frauen 12-15 g/dL. Hämatokrit <50% (wichtig bei TRT!). Leukozyten für Immunstatus.',
'stark',
ARRAY['blutbild', 'hämoglobin', 'hämatokrit', 'erythrozyten', 'leukozyten'],
ARRAY['cbc', 'blood count', 'rotes blutbild'],
ARRAY['hemoglobin', 'hematocrit', 'rbc', 'wbc', 'platelets'],
false, true),

('Blutwerte', 'Stoffwechsel', 'HbA1c',
'HbA1c und Langzeit-Blutzucker',
'HbA1c zeigt den durchschnittlichen Blutzucker der letzten 2-3 Monate. Wichtiger Stoffwechselmarker.',
'Optimal: <5.0%. Normal: <5.7%. Prädiabetes: 5.7-6.4%. Diabetes: >6.5%. Senkung durch Low-Carb, Bewegung.',
'stark',
ARRAY['hba1c', 'langzeitblutzucker', 'diabetes', 'glukose', 'stoffwechsel'],
ARRAY['glykiertes hämoglobin', 'glycated hemoglobin'],
ARRAY['hba1c', 'fasting_glucose', 'fasting_insulin'],
false, true);