-- Insert Nature Love Vitamin B Komplex Forte product
INSERT INTO public.supplement_products (
  brand_id,
  supplement_id,
  product_name,
  pack_size,
  pack_unit,
  servings_per_pack,
  dose_per_serving,
  dose_unit,
  price_eur,
  price_per_serving,
  form,
  category,
  country_of_origin,
  is_vegan,
  is_verified,
  is_recommended,
  quality_tags,
  timing,
  amazon_asin,
  amazon_url,
  product_url,
  short_description,
  synergies,
  blockers
) VALUES (
  '2a3839ba-fbea-44f5-bd29-1b370482081f', -- Nature Love brand_id
  'c1c57a03-e007-4c06-98cb-4017b83100e2', -- Vitamin B Komplex supplement_id
  'Vitamin B Komplex Forte',
  180,
  'Kapseln',
  180,
  1,
  'Kapsel',
  29.99,
  0.17,
  'capsule',
  'Energie',
  'DE',
  true,
  true,
  true,
  ARRAY['Quatrefolic', 'bioaktive Formen', '8 B-Vitamine', 'Made in Germany', 'vegan', 'laborgeprüft'],
  'morning',
  'B0725X1B5D',
  'https://www.amazon.de/dp/B0725X1B5D',
  'https://www.nature-love.de/products/vitamin-b-komplex-kapseln',
  'Hochdosierter Vitamin B Komplex mit allen 8 B-Vitaminen in bioaktiven Formen. Mit Methylcobalamin, Quatrefolic-Folat und Hydroxocobalamin als B12-Depot.',
  ARRAY['magnesium', 'vitamin c', 'omega 3'],
  ARRAY['alkohol', 'koffein in hohen mengen']
);